package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcpMesto generated by hbm2java
 */
@Entity
@Table(name="OCP_MESTO"
    ,schema="DAREX"
)
public class OcpMesto  implements java.io.Serializable {


     private int idMesta;
     private OcpMesto ocpMesto;
     private String naziv;
     private String pttBroj;
     private int teritorija;
     private Set ocpPoslovniPartners = new HashSet(0);
     private Set ocpMestos = new HashSet(0);

    public OcpMesto() {
    }

	
    public OcpMesto(int idMesta, String naziv, int teritorija) {
        this.idMesta = idMesta;
        this.naziv = naziv;
        this.teritorija = teritorija;
    }
    public OcpMesto(int idMesta, OcpMesto ocpMesto, String naziv, String pttBroj, int teritorija, Set ocpPoslovniPartners, Set ocpMestos) {
       this.idMesta = idMesta;
       this.ocpMesto = ocpMesto;
       this.naziv = naziv;
       this.pttBroj = pttBroj;
       this.teritorija = teritorija;
       this.ocpPoslovniPartners = ocpPoslovniPartners;
       this.ocpMestos = ocpMestos;
    }
   
     @Id 

    
    @Column(name="ID_MESTA", nullable=false, precision=6, scale=0)
    public int getIdMesta() {
        return this.idMesta;
    }
    
    public void setIdMesta(int idMesta) {
        this.idMesta = idMesta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="KORISTI_PTT_BROJ_MESTA")
    public OcpMesto getOcpMesto() {
        return this.ocpMesto;
    }
    
    public void setOcpMesto(OcpMesto ocpMesto) {
        this.ocpMesto = ocpMesto;
    }

    
    @Column(name="NAZIV", nullable=false, length=30)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="PTT_BROJ", length=20)
    public String getPttBroj() {
        return this.pttBroj;
    }
    
    public void setPttBroj(String pttBroj) {
        this.pttBroj = pttBroj;
    }

    
    @Column(name="TERITORIJA#", nullable=false, precision=6, scale=0)
    public int getTeritorija() {
        return this.teritorija;
    }
    
    public void setTeritorija(int teritorija) {
        this.teritorija = teritorija;
    }

@OneToMany(targetEntity=OcpPoslovniPartner.class, fetch=FetchType.LAZY, mappedBy="ocpMesto")
    public Set getOcpPoslovniPartners() {
        return this.ocpPoslovniPartners;
    }
    
    public void setOcpPoslovniPartners(Set ocpPoslovniPartners) {
        this.ocpPoslovniPartners = ocpPoslovniPartners;
    }

@OneToMany(targetEntity=OcpMesto.class, fetch=FetchType.LAZY, mappedBy="ocpMesto")
    public Set getOcpMestos() {
        return this.ocpMestos;
    }
    
    public void setOcpMestos(Set ocpMestos) {
        this.ocpMestos = ocpMestos;
    }




}


