package rs.invado.wo.domain.wo;

// Generated Dec 11, 2012 10:59:44 PM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WoAutentifikacijaId generated by hbm2java
 */
@Embeddable
public class WoAutentifikacijaId implements java.io.Serializable {

	private int partner;
	private Serializable vremeAutentifikacije;
	private String ip;
	private String dummy;
	private BigDecimal idwouser;
	private String sessionid;

	public WoAutentifikacijaId() {
	}

	public WoAutentifikacijaId(int partner, Serializable vremeAutentifikacije,
			String ip) {
		this.partner = partner;
		this.vremeAutentifikacije = vremeAutentifikacije;
		this.ip = ip;
	}

	public WoAutentifikacijaId(int partner, Serializable vremeAutentifikacije,
			String ip, String dummy, BigDecimal idwouser, String sessionid) {
		this.partner = partner;
		this.vremeAutentifikacije = vremeAutentifikacije;
		this.ip = ip;
		this.dummy = dummy;
		this.idwouser = idwouser;
		this.sessionid = sessionid;
	}

	@Column(name = "PARTNER", nullable = false, precision = 7, scale = 0)
	public int getPartner() {
		return this.partner;
	}

	public void setPartner(int partner) {
		this.partner = partner;
	}

	@Column(name = "VREME_AUTENTIFIKACIJE", nullable = false)
	public Serializable getVremeAutentifikacije() {
		return this.vremeAutentifikacije;
	}

	public void setVremeAutentifikacije(Serializable vremeAutentifikacije) {
		this.vremeAutentifikacije = vremeAutentifikacije;
	}

	@Column(name = "IP", nullable = false, length = 15)
	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	@Column(name = "DUMMY", length = 2000)
	public String getDummy() {
		return this.dummy;
	}

	public void setDummy(String dummy) {
		this.dummy = dummy;
	}

	@Column(name = "IDWOUSER", precision = 22, scale = 0)
	public BigDecimal getIdwouser() {
		return this.idwouser;
	}

	public void setIdwouser(BigDecimal idwouser) {
		this.idwouser = idwouser;
	}

	@Column(name = "SESSIONID", length = 2000)
	public String getSessionid() {
		return this.sessionid;
	}

	public void setSessionid(String sessionid) {
		this.sessionid = sessionid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WoAutentifikacijaId))
			return false;
		WoAutentifikacijaId castOther = (WoAutentifikacijaId) other;

		return (this.getPartner() == castOther.getPartner())
				&& ((this.getVremeAutentifikacije() == castOther
						.getVremeAutentifikacije()) || (this
						.getVremeAutentifikacije() != null
						&& castOther.getVremeAutentifikacije() != null && this
						.getVremeAutentifikacije().equals(
								castOther.getVremeAutentifikacije())))
				&& ((this.getIp() == castOther.getIp()) || (this.getIp() != null
						&& castOther.getIp() != null && this.getIp().equals(
						castOther.getIp())))
				&& ((this.getDummy() == castOther.getDummy()) || (this
						.getDummy() != null && castOther.getDummy() != null && this
						.getDummy().equals(castOther.getDummy())))
				&& ((this.getIdwouser() == castOther.getIdwouser()) || (this
						.getIdwouser() != null
						&& castOther.getIdwouser() != null && this
						.getIdwouser().equals(castOther.getIdwouser())))
				&& ((this.getSessionid() == castOther.getSessionid()) || (this
						.getSessionid() != null
						&& castOther.getSessionid() != null && this
						.getSessionid().equals(castOther.getSessionid())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getPartner();
		result = 37
				* result
				+ (getVremeAutentifikacije() == null ? 0 : this
						.getVremeAutentifikacije().hashCode());
		result = 37 * result + (getIp() == null ? 0 : this.getIp().hashCode());
		result = 37 * result
				+ (getDummy() == null ? 0 : this.getDummy().hashCode());
		result = 37 * result
				+ (getIdwouser() == null ? 0 : this.getIdwouser().hashCode());
		result = 37 * result
				+ (getSessionid() == null ? 0 : this.getSessionid().hashCode());
		return result;
	}

}
