package rs.invado.wo.domain.wo;
// Generated Jan 13, 2013 6:20:53 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;

/**
 * WoDownloadFiles generated by hbm2java
 */
@Entity
@Table(name = "WO_DOWNLOAD_FILES"
        , schema = "DAREX"
)
public class WoDownloadFiles implements java.io.Serializable {


    private WoDownloadFilesId id;
    private WoDownloadTip woDownloadTip;
    private String opis;
    private String naziv;
    private String fajlUrl;
    private BigDecimal vrstaKalsifikacija;
    private String klasifikacija;
    private Date vaziDo;
    private String aktuelno;
    private Integer sort;
    private WoDownloadGrupa woDownloadGrupa;

    public WoDownloadFiles() {
    }


    public WoDownloadFiles(WoDownloadFilesId id, WoDownloadTip woDownloadTip) {
        this.id = id;
        this.woDownloadTip = woDownloadTip;
    }

    public WoDownloadFiles(WoDownloadFilesId id, WoDownloadTip woDownloadTip, String opis, String naziv, String fajlUrl,
                           BigDecimal vrstaKalsifikacija, String klasifikacija, Date vaziDo) {
        this.id = id;
        this.woDownloadTip = woDownloadTip;
        this.opis = opis;
        this.naziv = naziv;
        this.fajlUrl = fajlUrl;
        this.vrstaKalsifikacija = vrstaKalsifikacija;
        this.klasifikacija = klasifikacija;
        this.vaziDo = vaziDo;
    }

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "idTipa", column = @Column(name = "ID_TIPA", nullable = false, precision = 22, scale = 0)),
            @AttributeOverride(name = "idFajla", column = @Column(name = "ID_FAJLA", nullable = false, precision = 22, scale = 0))})
    public WoDownloadFilesId getId() {
        return this.id;
    }

    public void setId(WoDownloadFilesId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_TIPA", nullable = false, insertable = false, updatable = false)
    public WoDownloadTip getWoDownloadTip() {
        return this.woDownloadTip;
    }

    public void setWoDownloadTip(WoDownloadTip woDownloadTip) {
        this.woDownloadTip = woDownloadTip;
    }


    @Column(name = "OPIS", length = 2000)
    public String getOpis() {
        return this.opis;
    }

    public void setOpis(String opis) {
        this.opis = opis;
    }


    @Column(name = "NAZIV", length = 500)
    public String getNaziv() {
        return this.naziv;
    }

    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }


    @Column(name = "FAJL_URL", length = 500)
    public String getFajlUrl() {
        return this.fajlUrl;
    }

    public void setFajlUrl(String fajlUrl) {
        this.fajlUrl = fajlUrl;
    }


    @Column(name = "VRSTA_KALSIFIKACIJA#", precision = 22, scale = 0)
    public BigDecimal getVrstaKalsifikacija() {
        return this.vrstaKalsifikacija;
    }

    public void setVrstaKalsifikacija(BigDecimal vrstaKalsifikacija) {
        this.vrstaKalsifikacija = vrstaKalsifikacija;
    }


    @Column(name = "KLASIFIKACIJA#", length = 500)
    public String getKlasifikacija() {
        return this.klasifikacija;
    }

    public void setKlasifikacija(String klasifikacija) {
        this.klasifikacija = klasifikacija;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "VAZI_DO", length = 7)
    public Date getVaziDo() {
        return this.vaziDo;
    }

    public void setVaziDo(Date vaziDo) {
        this.vaziDo = vaziDo;
    }

    @Column(name = "AKTUELNO")
    public String getAktuelno() {
        return aktuelno;
    }

    @Column(name = "SORT")
    public void setAktuelno(String aktuelno) {
        this.aktuelno = aktuelno;
    }

    @Column(name="SORT")
    public Integer getSort() {
        return sort;
    }

    public void setSort(Integer sort) {
        this.sort = sort;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "GRUPA_ID", nullable = false, insertable = false, updatable = false)
    public WoDownloadGrupa getWoDownloadGrupa() {
        return woDownloadGrupa;
    }

    public void setWoDownloadGrupa(WoDownloadGrupa woDownloadGrupa) {
        this.woDownloadGrupa = woDownloadGrupa;
    }
}


