package rs.invado.wo.domain.wo;

// Generated Jan 19, 2013 2:16:09 PM by Hibernate Tools 3.4.0.CR1

import rs.invado.wo.domain.prod.ProdNacinPlacanja;

import javax.persistence.*;

/**
 * WoSetPoNacinPlacanja generated by hbm2java
 */
@Entity
@Table(name = "WO_SET_PO_NACIN_PLACANJA", schema = "DAREX")
@SequenceGenerator(   name = "etailerRaw_seq",
        sequenceName = "WO_ID_SEQ", allocationSize = 1)
public class WoSetPoNacinPlacanja implements java.io.Serializable {

    private Integer id;
    private Integer idVdSkldok;
    private Integer vrstastavke;
    private Integer idVdFindok;

    private WoParametri parametri;
    private ProdNacinPlacanja prodNacinPlacanja;

    public WoSetPoNacinPlacanja() {
    }

    public WoSetPoNacinPlacanja(Integer id) {
        this.id = id;
    }

    public WoSetPoNacinPlacanja(Integer id, WoParametri prametri,
                                ProdNacinPlacanja nacinPlacanja, Integer idVdSkldok,
                                Integer vrstastavke, Integer idVdFindok) {
        this.id = id;
        this.parametri = prametri;
        this.prodNacinPlacanja = nacinPlacanja;
        this.idVdSkldok = idVdSkldok;
        this.vrstastavke = vrstastavke;
        this.idVdFindok = idVdFindok;
    }

    @Id
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    @GeneratedValue(strategy = GenerationType.SEQUENCE,
            generator = "etailerRaw_seq")
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PARAMETRI_ID", referencedColumnName = "ID", nullable = false, updatable = true, insertable = true)
    public WoParametri getParametri() {
        return this.parametri;
    }

    public void setParametri(WoParametri prametri) {
        this.parametri = prametri;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "NACIN_PLACANJA", referencedColumnName = "NACIN#", insertable = true, updatable = true)
    public ProdNacinPlacanja getProdNacinPlacanja() {
        return this.prodNacinPlacanja;
    }

    public void setProdNacinPlacanja(ProdNacinPlacanja prodNacinPlacanja) {
        this.prodNacinPlacanja = prodNacinPlacanja;
    }

    @Column(name = "ID_VD_SKLDOK", precision = 22, scale = 0)
    public Integer getIdVdSkldok() {
        return this.idVdSkldok;
    }

    public void setIdVdSkldok(Integer idVdSkldok) {
        this.idVdSkldok = idVdSkldok;
    }

    @Column(name = "VRSTASTAVKE", precision = 22, scale = 0)
    public Integer getVrstastavke() {
        return this.vrstastavke;
    }

    public void setVrstastavke(Integer vrstastavke) {
        this.vrstastavke = vrstastavke;
    }

    @Column(name = "ID_VD_FINDOK", precision = 22, scale = 0)
    public Integer getIdVdFindok() {
        return this.idVdFindok;
    }

    public void setIdVdFindok(Integer idVdFindok) {
        this.idVdFindok = idVdFindok;
    }

}
