package rs.invado.wo.domain.wo;

// Generated Mar 6, 2013 10:35:50 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WoUserRights generated by hbm2java
 */
@Entity
@Table(name = "WO_USER_RIGHTS", schema = "DAREX")
public class WoUserRights implements java.io.Serializable {

	private Integer id;
	private String abbreviation;
	private String description;

	public WoUserRights() {
	}

	public WoUserRights(Integer id) {
		this.id = id;
	}

	public WoUserRights(Integer id, String abbreviation, String description) {
		this.id = id;
		this.abbreviation = abbreviation;
		this.description = description;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "ABBREVIATION", length = 20)
	public String getAbbreviation() {
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation) {
		this.abbreviation = abbreviation;
	}

	@Column(name = "DESCRIPTION", length = 2000)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
