package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcpKlasifikacijaPpId generated by hbm2java
 */
@Embeddable
public class OcpKlasifikacijaPpId  implements java.io.Serializable {


     private int vrstaKlasifikacije;
     private String klasifikacija;
     private int poslovniPartner;

    public OcpKlasifikacijaPpId() {
    }

    public OcpKlasifikacijaPpId(int vrstaKlasifikacije, String klasifikacija, int poslovniPartner) {
       this.vrstaKlasifikacije = vrstaKlasifikacije;
       this.klasifikacija = klasifikacija;
       this.poslovniPartner = poslovniPartner;
    }
   


    @Column(name="VRSTA_KLASIFIKACIJE#", nullable=false, precision=6, scale=0)
    public int getVrstaKlasifikacije() {
        return this.vrstaKlasifikacije;
    }
    
    public void setVrstaKlasifikacije(int vrstaKlasifikacije) {
        this.vrstaKlasifikacije = vrstaKlasifikacije;
    }


    @Column(name="KLASIFIKACIJA#", nullable=false, length=15)
    public String getKlasifikacija() {
        return this.klasifikacija;
    }
    
    public void setKlasifikacija(String klasifikacija) {
        this.klasifikacija = klasifikacija;
    }


    @Column(name="POSLOVNI_PARTNER#", nullable=false, precision=7, scale=0)
    public int getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(int poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpKlasifikacijaPpId) ) return false;
		 OcpKlasifikacijaPpId castOther = ( OcpKlasifikacijaPpId ) other; 
         
		 return (this.getVrstaKlasifikacije()==castOther.getVrstaKlasifikacije())
 && ( (this.getKlasifikacija()==castOther.getKlasifikacija()) || ( this.getKlasifikacija()!=null && castOther.getKlasifikacija()!=null && this.getKlasifikacija().equals(castOther.getKlasifikacija()) ) )
 && (this.getPoslovniPartner()==castOther.getPoslovniPartner());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getVrstaKlasifikacije();
         result = 37 * result + ( getKlasifikacija() == null ? 0 : this.getKlasifikacija().hashCode() );
         result = 37 * result + this.getPoslovniPartner();
         return result;
   }   


}


