package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcpAtributZaKlasifikaciju generated by hbm2java
 */
@Entity
@Table(name = "OCP_ATRIBUT_ZA_KLASIFIKACIJU", schema = "DAREX")
public class OcpAtributZaKlasifikaciju implements java.io.Serializable {

	private OcpAtributZaKlasifikacijuId id;
	private OcpKlasifikacija ocpKlasifikacija;
	private String prefiksUNazivu;
	private Byte redosledUNazivu;
	private String jmUcestvujeUNazivu;

	public OcpAtributZaKlasifikaciju() {
	}

	public OcpAtributZaKlasifikaciju(OcpAtributZaKlasifikacijuId id,
			OcpKlasifikacija ocpKlasifikacija) {
		this.id = id;
		this.ocpKlasifikacija = ocpKlasifikacija;
	}

	public OcpAtributZaKlasifikaciju(OcpAtributZaKlasifikacijuId id,
			OcpKlasifikacija ocpKlasifikacija, String prefiksUNazivu,
			Byte redosledUNazivu, String jmUcestvujeUNazivu) {
		this.id = id;
		this.ocpKlasifikacija = ocpKlasifikacija;
		this.prefiksUNazivu = prefiksUNazivu;
		this.redosledUNazivu = redosledUNazivu;
		this.jmUcestvujeUNazivu = jmUcestvujeUNazivu;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "atribut", column = @Column(name = "ATRIBUT#", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "vrstaKlasifikacije", column = @Column(name = "VRSTA_KLASIFIKACIJE#", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "klasifikacija", column = @Column(name = "KLASIFIKACIJA#", nullable = false, length = 15)) })
	public OcpAtributZaKlasifikacijuId getId() {
		return this.id;
	}

	public void setId(OcpAtributZaKlasifikacijuId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "VRSTA_KLASIFIKACIJE#", referencedColumnName = "VRSTA_KLASIFIKACIJE#", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "KLASIFIKACIJA#", referencedColumnName = "KLASIFIKACIJA#", nullable = false, insertable = false, updatable = false) })
	public OcpKlasifikacija getOcpKlasifikacija() {
		return this.ocpKlasifikacija;
	}

	public void setOcpKlasifikacija(OcpKlasifikacija ocpKlasifikacija) {
		this.ocpKlasifikacija = ocpKlasifikacija;
	}

	@Column(name = "PREFIKS_U_NAZIVU", length = 20)
	public String getPrefiksUNazivu() {
		return this.prefiksUNazivu;
	}

	public void setPrefiksUNazivu(String prefiksUNazivu) {
		this.prefiksUNazivu = prefiksUNazivu;
	}

	@Column(name = "REDOSLED_U_NAZIVU", precision = 2, scale = 0)
	public Byte getRedosledUNazivu() {
		return this.redosledUNazivu;
	}

	public void setRedosledUNazivu(Byte redosledUNazivu) {
		this.redosledUNazivu = redosledUNazivu;
	}

	@Column(name = "JM_UCESTVUJE_U_NAZIVU", length = 1)
	public String getJmUcestvujeUNazivu() {
		return this.jmUcestvujeUNazivu;
	}

	public void setJmUcestvujeUNazivu(String jmUcestvujeUNazivu) {
		this.jmUcestvujeUNazivu = jmUcestvujeUNazivu;
	}

}
