package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcpKlasifikacijaSkladista generated by hbm2java
 */
@Entity
@Table(name = "OCP_KLASIFIKACIJA_SKLADISTA", schema = "DAREX")
public class OcpKlasifikacijaSkladista implements java.io.Serializable {

	private OcpKlasifikacijaSkladistaId id;

	public OcpKlasifikacijaSkladista() {
	}

	public OcpKlasifikacijaSkladista(OcpKlasifikacijaSkladistaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "vrstaKlasifikacije", column = @Column(name = "VRSTA_KLASIFIKACIJE#", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "klasifikacija", column = @Column(name = "KLASIFIKACIJA#", nullable = false, length = 15)),
			@AttributeOverride(name = "idSkladista", column = @Column(name = "ID_SKLADISTA", nullable = false, precision = 3, scale = 0)) })
	public OcpKlasifikacijaSkladistaId getId() {
		return this.id;
	}

	public void setId(OcpKlasifikacijaSkladistaId id) {
		this.id = id;
	}

}
