package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OcpRadnik generated by hbm2java
 */
@Entity
@Table(name="OCP_RADNIK"
    ,schema="DAREX"
    , uniqueConstraints = @UniqueConstraint(columnNames={"IME", "PREZIME", "RADNIK#"}) 
)
public class OcpRadnik  implements java.io.Serializable {


     private int radnik;
     private OcpPoslovniPartner ocpPoslovniPartner;
     private OcpOrganizacionaJedinica ocpOrganizacionaJedinica;
     private String ime;
     private String prezime;
     private String vrsta;
     private String sifraLd;
     private String ss;
     private Set ocpValutas = new HashSet(0);
     private Set ocpPoslovniPartners = new HashSet(0);

    public OcpRadnik() {
    }

	
    public OcpRadnik(int radnik, String ime, String prezime) {
        this.radnik = radnik;
        this.ime = ime;
        this.prezime = prezime;
    }
    public OcpRadnik(int radnik, OcpPoslovniPartner ocpPoslovniPartner, OcpOrganizacionaJedinica ocpOrganizacionaJedinica, String ime, String prezime, String vrsta, String sifraLd, String ss, Set ocpValutas, Set ocpPoslovniPartners) {
       this.radnik = radnik;
       this.ocpPoslovniPartner = ocpPoslovniPartner;
       this.ocpOrganizacionaJedinica = ocpOrganizacionaJedinica;
       this.ime = ime;
       this.prezime = prezime;
       this.vrsta = vrsta;
       this.sifraLd = sifraLd;
       this.ss = ss;
       this.ocpValutas = ocpValutas;
       this.ocpPoslovniPartners = ocpPoslovniPartners;
    }
   
     @Id 

    
    @Column(name="RADNIK#", unique=true, nullable=false, precision=6, scale=0)
    public int getRadnik() {
        return this.radnik;
    }
    
    public void setRadnik(int radnik) {
        this.radnik = radnik;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="PP_REF")
    public OcpPoslovniPartner getOcpPoslovniPartner() {
        return this.ocpPoslovniPartner;
    }
    
    public void setOcpPoslovniPartner(OcpPoslovniPartner ocpPoslovniPartner) {
        this.ocpPoslovniPartner = ocpPoslovniPartner;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ORGANIZACIONA_JEDINICA#")
    public OcpOrganizacionaJedinica getOcpOrganizacionaJedinica() {
        return this.ocpOrganizacionaJedinica;
    }
    
    public void setOcpOrganizacionaJedinica(OcpOrganizacionaJedinica ocpOrganizacionaJedinica) {
        this.ocpOrganizacionaJedinica = ocpOrganizacionaJedinica;
    }

    
    @Column(name="IME", nullable=false, length=20)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="PREZIME", nullable=false, length=20)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="VRSTA", length=1)
    public String getVrsta() {
        return this.vrsta;
    }
    
    public void setVrsta(String vrsta) {
        this.vrsta = vrsta;
    }

    
    @Column(name="SIFRA_LD", length=6)
    public String getSifraLd() {
        return this.sifraLd;
    }
    
    public void setSifraLd(String sifraLd) {
        this.sifraLd = sifraLd;
    }

    
    @Column(name="SS", length=2)
    public String getSs() {
        return this.ss;
    }
    
    public void setSs(String ss) {
        this.ss = ss;
    }

@OneToMany(targetEntity=OcpValuta.class,fetch=FetchType.LAZY, mappedBy="ocpRadnik")
    public Set getOcpValutas() {
        return this.ocpValutas;
    }
    
    public void setOcpValutas(Set ocpValutas) {
        this.ocpValutas = ocpValutas;
    }

@OneToMany(targetEntity=OcpPoslovniPartner.class,fetch=FetchType.LAZY, mappedBy="ocpRadnik")
    public Set getOcpPoslovniPartners() {
        return this.ocpPoslovniPartners;
    }
    
    public void setOcpPoslovniPartners(Set ocpPoslovniPartners) {
        this.ocpPoslovniPartners = ocpPoslovniPartners;
    }




}


