package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * OcpVrstaDokumenta generated by hbm2java
 */
@Entity
@Table(name="OCP_VRSTA_DOKUMENTA"
    ,schema="DAREX"
    , uniqueConstraints = @UniqueConstraint(columnNames="SKR_NAZIV_VD") 
)
public class OcpVrstaDokumenta  implements java.io.Serializable {


     private short idVd;
     private OcpVrstaDokumenta ocpVrstaDokumenta;
     private Integer brPoslDok;
     private String nazivVd;
     private String kodUI;
     private String onValidateRecord;
     private String skrNazivVd;
     private String kodUIMk;
     private String klasd;
     private String intext;
     private Short foVd;
     private Integer radnikTp;
     private Short idVdPo;
     private Short defVrstaStavke;
     private String kodId;
     private String nazivApl;
     private String nazivStampa;
     private Short idVdNad;
     private Short idVdGen;
     private Byte redosledKnjizenja;
     private String poRadnomNalogu;
     private String generiseOtpremnicu;
     private String isoOznaka;
     private String protivKontoDugovni;
     private String protivKontoPotrazni;
     private Set ocpVrstaDokumentas = new HashSet(0);
     private Set ocpKlasifikacijas = new HashSet(0);

    public OcpVrstaDokumenta() {
    }

	
    public OcpVrstaDokumenta(short idVd, String nazivVd) {
        this.idVd = idVd;
        this.nazivVd = nazivVd;
    }
    public OcpVrstaDokumenta(short idVd, OcpVrstaDokumenta ocpVrstaDokumenta, Integer brPoslDok, String nazivVd, String kodUI, String onValidateRecord, String skrNazivVd, String kodUIMk, String klasd, String intext, Short foVd, Integer radnikTp, Short idVdPo, Short defVrstaStavke, String kodId, String nazivApl, String nazivStampa, Short idVdNad, Short idVdGen, Byte redosledKnjizenja, String poRadnomNalogu, String generiseOtpremnicu, String isoOznaka, String protivKontoDugovni, String protivKontoPotrazni, Set ocpVrstaDokumentas, Set ocpKlasifikacijas) {
       this.idVd = idVd;
       this.ocpVrstaDokumenta = ocpVrstaDokumenta;
       this.brPoslDok = brPoslDok;
       this.nazivVd = nazivVd;
       this.kodUI = kodUI;
       this.onValidateRecord = onValidateRecord;
       this.skrNazivVd = skrNazivVd;
       this.kodUIMk = kodUIMk;
       this.klasd = klasd;
       this.intext = intext;
       this.foVd = foVd;
       this.radnikTp = radnikTp;
       this.idVdPo = idVdPo;
       this.defVrstaStavke = defVrstaStavke;
       this.kodId = kodId;
       this.nazivApl = nazivApl;
       this.nazivStampa = nazivStampa;
       this.idVdNad = idVdNad;
       this.idVdGen = idVdGen;
       this.redosledKnjizenja = redosledKnjizenja;
       this.poRadnomNalogu = poRadnomNalogu;
       this.generiseOtpremnicu = generiseOtpremnicu;
       this.isoOznaka = isoOznaka;
       this.protivKontoDugovni = protivKontoDugovni;
       this.protivKontoPotrazni = protivKontoPotrazni;
       this.ocpVrstaDokumentas = ocpVrstaDokumentas;
       this.ocpKlasifikacijas = ocpKlasifikacijas;
    }
   
     @Id 

    
    @Column(name="ID_VD", nullable=false, precision=3, scale=0)
    public short getIdVd() {
        return this.idVd;
    }
    
    public void setIdVd(short idVd) {
        this.idVd = idVd;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_VD_VRSTE")
    public OcpVrstaDokumenta getOcpVrstaDokumenta() {
        return this.ocpVrstaDokumenta;
    }
    
    public void setOcpVrstaDokumenta(OcpVrstaDokumenta ocpVrstaDokumenta) {
        this.ocpVrstaDokumenta = ocpVrstaDokumenta;
    }

    
    @Column(name="BR_POSL_DOK", precision=5, scale=0)
    public Integer getBrPoslDok() {
        return this.brPoslDok;
    }
    
    public void setBrPoslDok(Integer brPoslDok) {
        this.brPoslDok = brPoslDok;
    }

    
    @Column(name="NAZIV_VD", nullable=false, length=100)
    public String getNazivVd() {
        return this.nazivVd;
    }
    
    public void setNazivVd(String nazivVd) {
        this.nazivVd = nazivVd;
    }

    
    @Column(name="KOD_U_I", length=1)
    public String getKodUI() {
        return this.kodUI;
    }
    
    public void setKodUI(String kodUI) {
        this.kodUI = kodUI;
    }

    
    @Column(name="ON_VALIDATE_RECORD", length=30)
    public String getOnValidateRecord() {
        return this.onValidateRecord;
    }
    
    public void setOnValidateRecord(String onValidateRecord) {
        this.onValidateRecord = onValidateRecord;
    }

    
    @Column(name="SKR_NAZIV_VD", unique=true, length=6)
    public String getSkrNazivVd() {
        return this.skrNazivVd;
    }
    
    public void setSkrNazivVd(String skrNazivVd) {
        this.skrNazivVd = skrNazivVd;
    }

    
    @Column(name="KOD_U_I_MK", length=1)
    public String getKodUIMk() {
        return this.kodUIMk;
    }
    
    public void setKodUIMk(String kodUIMk) {
        this.kodUIMk = kodUIMk;
    }

    
    @Column(name="KLASD", length=2)
    public String getKlasd() {
        return this.klasd;
    }
    
    public void setKlasd(String klasd) {
        this.klasd = klasd;
    }

    
    @Column(name="INTEXT", length=1)
    public String getIntext() {
        return this.intext;
    }
    
    public void setIntext(String intext) {
        this.intext = intext;
    }

    
    @Column(name="FO_VD#", precision=3, scale=0)
    public Short getFoVd() {
        return this.foVd;
    }
    
    public void setFoVd(Short foVd) {
        this.foVd = foVd;
    }

    
    @Column(name="RADNIK#_TP", precision=6, scale=0)
    public Integer getRadnikTp() {
        return this.radnikTp;
    }
    
    public void setRadnikTp(Integer radnikTp) {
        this.radnikTp = radnikTp;
    }

    
    @Column(name="ID_VD_PO", precision=3, scale=0)
    public Short getIdVdPo() {
        return this.idVdPo;
    }
    
    public void setIdVdPo(Short idVdPo) {
        this.idVdPo = idVdPo;
    }

    
    @Column(name="DEF_VRSTA_STAVKE", precision=3, scale=0)
    public Short getDefVrstaStavke() {
        return this.defVrstaStavke;
    }
    
    public void setDefVrstaStavke(Short defVrstaStavke) {
        this.defVrstaStavke = defVrstaStavke;
    }

    
    @Column(name="KOD_ID", length=1)
    public String getKodId() {
        return this.kodId;
    }
    
    public void setKodId(String kodId) {
        this.kodId = kodId;
    }

    
    @Column(name="NAZIV_APL", length=40)
    public String getNazivApl() {
        return this.nazivApl;
    }
    
    public void setNazivApl(String nazivApl) {
        this.nazivApl = nazivApl;
    }

    
    @Column(name="NAZIV_STAMPA", length=40)
    public String getNazivStampa() {
        return this.nazivStampa;
    }
    
    public void setNazivStampa(String nazivStampa) {
        this.nazivStampa = nazivStampa;
    }

    
    @Column(name="ID_VD_NAD", precision=3, scale=0)
    public Short getIdVdNad() {
        return this.idVdNad;
    }
    
    public void setIdVdNad(Short idVdNad) {
        this.idVdNad = idVdNad;
    }

    
    @Column(name="ID_VD_GEN", precision=3, scale=0)
    public Short getIdVdGen() {
        return this.idVdGen;
    }
    
    public void setIdVdGen(Short idVdGen) {
        this.idVdGen = idVdGen;
    }

    
    @Column(name="REDOSLED_KNJIZENJA", precision=2, scale=0)
    public Byte getRedosledKnjizenja() {
        return this.redosledKnjizenja;
    }
    
    public void setRedosledKnjizenja(Byte redosledKnjizenja) {
        this.redosledKnjizenja = redosledKnjizenja;
    }

    
    @Column(name="PO_RADNOM_NALOGU", length=1)
    public String getPoRadnomNalogu() {
        return this.poRadnomNalogu;
    }
    
    public void setPoRadnomNalogu(String poRadnomNalogu) {
        this.poRadnomNalogu = poRadnomNalogu;
    }

    
    @Column(name="GENERISE_OTPREMNICU", length=1)
    public String getGeneriseOtpremnicu() {
        return this.generiseOtpremnicu;
    }
    
    public void setGeneriseOtpremnicu(String generiseOtpremnicu) {
        this.generiseOtpremnicu = generiseOtpremnicu;
    }

    
    @Column(name="ISO_OZNAKA", length=50)
    public String getIsoOznaka() {
        return this.isoOznaka;
    }
    
    public void setIsoOznaka(String isoOznaka) {
        this.isoOznaka = isoOznaka;
    }

    
    @Column(name="PROTIV_KONTO#_DUGOVNI", length=8)
    public String getProtivKontoDugovni() {
        return this.protivKontoDugovni;
    }
    
    public void setProtivKontoDugovni(String protivKontoDugovni) {
        this.protivKontoDugovni = protivKontoDugovni;
    }

    
    @Column(name="PROTIV_KONTO#_POTRAZNI", length=8)
    public String getProtivKontoPotrazni() {
        return this.protivKontoPotrazni;
    }
    
    public void setProtivKontoPotrazni(String protivKontoPotrazni) {
        this.protivKontoPotrazni = protivKontoPotrazni;
    }

@OneToMany(targetEntity=rs.invado.wo.domain.ocp.OcpVrstaDokumenta.class, fetch=FetchType.LAZY, mappedBy="ocpVrstaDokumenta")
    public Set getOcpVrstaDokumentas() {
        return this.ocpVrstaDokumentas;
    }
    
    public void setOcpVrstaDokumentas(Set ocpVrstaDokumentas) {
        this.ocpVrstaDokumentas = ocpVrstaDokumentas;
    }

@ManyToMany(targetEntity=rs.invado.wo.domain.ocp.OcpKlasifikacija.class, fetch=FetchType.LAZY, mappedBy="ocpVrstaDokumentas")
    public Set getOcpKlasifikacijas() {
        return this.ocpKlasifikacijas;
    }
    
    public void setOcpKlasifikacijas(Set ocpKlasifikacijas) {
        this.ocpKlasifikacijas = ocpKlasifikacijas;
    }




}


