package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import org.springframework.core.annotation.Order;

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.OrderBy;

/**
 * OcpVrAtrProizvodId generated by hbm2java
 */
@Embeddable
public class OcpVrAtrProizvodId  implements java.io.Serializable {


     private int proizvod;
     private String klasifikacija;
     private int vrstaKlasifikacije;
     private int atribut;

    public OcpVrAtrProizvodId() {
    }

    public OcpVrAtrProizvodId(int proizvod, String klasifikacija, int vrstaKlasifikacije, int atribut) {
       this.proizvod = proizvod;
       this.klasifikacija = klasifikacija;
       this.vrstaKlasifikacije = vrstaKlasifikacije;
       this.atribut = atribut;
    }
   


    @Column(name="PROIZVOD#", nullable=false, precision=7, scale=0)
    public int getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(int proizvod) {
        this.proizvod = proizvod;
    }


    @Column(name="KLASIFIKACIJA#", nullable=false, length=15)
    public String getKlasifikacija() {
        return this.klasifikacija;
    }
    
    public void setKlasifikacija(String klasifikacija) {
        this.klasifikacija = klasifikacija;
    }


    @Column(name="VRSTA_KLASIFIKACIJE#", nullable=false, precision=6, scale=0)
    public int getVrstaKlasifikacije() {
        return this.vrstaKlasifikacije;
    }
    
    public void setVrstaKlasifikacije(int vrstaKlasifikacije) {
        this.vrstaKlasifikacije = vrstaKlasifikacije;
    }


    @Column(name="ATRIBUT#", nullable=false, precision=6, scale=0)
    @OrderBy("atrbt desc")
    public int getAtribut() {
        return this.atribut;
    }
    
    public void setAtribut(int atribut) {
        this.atribut = atribut;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpVrAtrProizvodId) ) return false;
		 OcpVrAtrProizvodId castOther = ( OcpVrAtrProizvodId ) other; 
         
		 return (this.getProizvod()==castOther.getProizvod())
 && ( (this.getKlasifikacija()==castOther.getKlasifikacija()) || ( this.getKlasifikacija()!=null && castOther.getKlasifikacija()!=null && this.getKlasifikacija().equals(castOther.getKlasifikacija()) ) )
 && (this.getVrstaKlasifikacije()==castOther.getVrstaKlasifikacije())
 && (this.getAtribut()==castOther.getAtribut());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProizvod();
         result = 37 * result + ( getKlasifikacija() == null ? 0 : this.getKlasifikacija().hashCode() );
         result = 37 * result + this.getVrstaKlasifikacije();
         result = 37 * result + this.getAtribut();
         return result;
   }   


}


