package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import org.omg.CORBA.PRIVATE_MEMBER;
import rs.invado.wo.domain.prod.ProdKlasaCene;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * OcpValuta generated by hbm2java
 */
@Entity
@Table(name="OCP_VALUTA"
    ,schema="DAREX"
)
public class OcpValuta  implements java.io.Serializable {


     private short idValute;
     private OcpRadnik ocpRadnik;
     private String nazivValute;
     private String skrNazivValute;
     private BigDecimal vaziZa;
     private Integer drzava;
     private String naziv100TogDela;
     private Byte sort;
     private Set ocpZiroRacuns = new HashSet(0);
     private List<ProdKlasaCene> klaseZaValutu = new ArrayList<ProdKlasaCene>();

    public OcpValuta() {
    }

	
    public OcpValuta(short idValute, OcpRadnik ocpRadnik, String nazivValute, String skrNazivValute) {
        this.idValute = idValute;
        this.ocpRadnik = ocpRadnik;
        this.nazivValute = nazivValute;
        this.skrNazivValute = skrNazivValute;
    }
    public OcpValuta(short idValute, OcpRadnik ocpRadnik, String nazivValute, String skrNazivValute, BigDecimal vaziZa, Integer drzava, String naziv100TogDela, Byte sort, Set ocpZiroRacuns) {
       this.idValute = idValute;
       this.ocpRadnik = ocpRadnik;
       this.nazivValute = nazivValute;
       this.skrNazivValute = skrNazivValute;
       this.vaziZa = vaziZa;
       this.drzava = drzava;
       this.naziv100TogDela = naziv100TogDela;
       this.sort = sort;
       this.ocpZiroRacuns = ocpZiroRacuns;
    }
   
     @Id 

    
    @Column(name="ID_VALUTE", nullable=false, precision=3, scale=0)
    public short getIdValute() {
        return this.idValute;
    }
    
    public void setIdValute(short idValute) {
        this.idValute = idValute;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RADNIK#", nullable=false)
    public OcpRadnik getOcpRadnik() {
        return this.ocpRadnik;
    }
    
    public void setOcpRadnik(OcpRadnik ocpRadnik) {
        this.ocpRadnik = ocpRadnik;
    }

    
    @Column(name="NAZIV_VALUTE", nullable=false, length=15)
    public String getNazivValute() {
        return this.nazivValute;
    }
    
    public void setNazivValute(String nazivValute) {
        this.nazivValute = nazivValute;
    }

    
    @Column(name="SKR_NAZIV_VALUTE", nullable=false, length=4)
    public String getSkrNazivValute() {
        return this.skrNazivValute;
    }
    
    public void setSkrNazivValute(String skrNazivValute) {
        this.skrNazivValute = skrNazivValute;
    }

    
    @Column(name="VAZI_ZA", precision=12, scale=6)
    public BigDecimal getVaziZa() {
        return this.vaziZa;
    }
    
    public void setVaziZa(BigDecimal vaziZa) {
        this.vaziZa = vaziZa;
    }

    
    @Column(name="DRZAVA#", precision=6, scale=0)
    public Integer getDrzava() {
        return this.drzava;
    }
    
    public void setDrzava(Integer drzava) {
        this.drzava = drzava;
    }

    
    @Column(name="NAZIV_100_TOG_DELA", length=10)
    public String getNaziv100TogDela() {
        return this.naziv100TogDela;
    }
    
    public void setNaziv100TogDela(String naziv100TogDela) {
        this.naziv100TogDela = naziv100TogDela;
    }

    
    @Column(name="SORT", precision=2, scale=0)
    public Byte getSort() {
        return this.sort;
    }
    
    public void setSort(Byte sort) {
        this.sort = sort;
    }

@OneToMany(targetEntity=OcpZiroRacun.class,fetch=FetchType.LAZY, mappedBy="ocpValuta")
    public Set getOcpZiroRacuns() {
        return this.ocpZiroRacuns;
    }
    
    public void setOcpZiroRacuns(Set ocpZiroRacuns) {
        this.ocpZiroRacuns = ocpZiroRacuns;
    }

    @OneToMany(targetEntity = ProdKlasaCene.class, fetch = FetchType.LAZY, mappedBy = "ocpValuta")
    public List<ProdKlasaCene> getKlaseZaValutu() {
        return klaseZaValutu;
    }

    public void setKlaseZaValutu(List<ProdKlasaCene> klaseZaValutu) {
        this.klaseZaValutu = klaseZaValutu;
    }
}


