package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OcpZiroRacun generated by hbm2java
 */
@Entity
@Table(name="OCP_ZIRO_RACUN"
    ,schema="DAREX"
)
public class OcpZiroRacun  implements java.io.Serializable {


     private OcpZiroRacunId id;
     private OcpValuta ocpValuta;
     private OcpPoslovniPartner ocpPoslovniPartner;
     private String napomena;
     private Date datumOtvaranja;
     private Integer otvorioRadnik;
     private Date datumBrisanja;
     private Integer obrisaoRadnik;

    public OcpZiroRacun() {
    }

	
    public OcpZiroRacun(OcpZiroRacunId id, Date datumOtvaranja) {
        this.id = id;
        this.datumOtvaranja = datumOtvaranja;
    }
    public OcpZiroRacun(OcpZiroRacunId id, OcpValuta ocpValuta, OcpPoslovniPartner ocpPoslovniPartner, String napomena, Date datumOtvaranja, Integer otvorioRadnik, Date datumBrisanja, Integer obrisaoRadnik) {
       this.id = id;
       this.ocpValuta = ocpValuta;
       this.ocpPoslovniPartner = ocpPoslovniPartner;
       this.napomena = napomena;
       this.datumOtvaranja = datumOtvaranja;
       this.otvorioRadnik = otvorioRadnik;
       this.datumBrisanja = datumBrisanja;
       this.obrisaoRadnik = obrisaoRadnik;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="poslovniPartner", column=@Column(name="POSLOVNI_PARTNER#", nullable=false, precision=7, scale=0) ), 
        @AttributeOverride(name="ziroRacun", column=@Column(name="ZIRO_RACUN#", nullable=false, length=40) ) } )
    public OcpZiroRacunId getId() {
        return this.id;
    }
    
    public void setId(OcpZiroRacunId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_VALUTE")
    public OcpValuta getOcpValuta() {
        return this.ocpValuta;
    }
    
    public void setOcpValuta(OcpValuta ocpValuta) {
        this.ocpValuta = ocpValuta;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ID_POSLOVNE_BANKE")
    public OcpPoslovniPartner getOcpPoslovniPartner() {
        return this.ocpPoslovniPartner;
    }
    
    public void setOcpPoslovniPartner(OcpPoslovniPartner ocpPoslovniPartner) {
        this.ocpPoslovniPartner = ocpPoslovniPartner;
    }

    
    @Column(name="NAPOMENA", length=256)
    public String getNapomena() {
        return this.napomena;
    }
    
    public void setNapomena(String napomena) {
        this.napomena = napomena;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_OTVARANJA", nullable=false, length=7)
    public Date getDatumOtvaranja() {
        return this.datumOtvaranja;
    }
    
    public void setDatumOtvaranja(Date datumOtvaranja) {
        this.datumOtvaranja = datumOtvaranja;
    }

    
    @Column(name="OTVORIO_RADNIK#", precision=6, scale=0)
    public Integer getOtvorioRadnik() {
        return this.otvorioRadnik;
    }
    
    public void setOtvorioRadnik(Integer otvorioRadnik) {
        this.otvorioRadnik = otvorioRadnik;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_BRISANJA", length=7)
    public Date getDatumBrisanja() {
        return this.datumBrisanja;
    }
    
    public void setDatumBrisanja(Date datumBrisanja) {
        this.datumBrisanja = datumBrisanja;
    }

    
    @Column(name="OBRISAO_RADNIK#", precision=6, scale=0)
    public Integer getObrisaoRadnik() {
        return this.obrisaoRadnik;
    }
    
    public void setObrisaoRadnik(Integer obrisaoRadnik) {
        this.obrisaoRadnik = obrisaoRadnik;
    }




}


