package rs.invado.wo.domain.wo;
// Generated Jan 13, 2013 6:20:53 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * WoDownloadTip generated by hbm2java
 */
@Entity
@Table(name="WO_DOWNLOAD_TIP",schema="DAREX")
@SequenceGenerator(   name = "rezervacija_seq", sequenceName = "WO_SEQ_ID", allocationSize = 1)
public class WoDownloadTip  implements java.io.Serializable {


     private BigDecimal id;
     private String opis;
     private String naziv;
     private String imageUrl;
     private Date vaziDo;
     private BigDecimal idKompanijeKorisnik;
     private int organizacionaJedinica;
     private Set woDownloadFileses = new HashSet(0);

    public WoDownloadTip() {
    }

	
    public WoDownloadTip(BigDecimal id) {
        this.id = id;
    }
    public WoDownloadTip(BigDecimal id, String opis, String naziv, String imageUrl, Date vaziDo, BigDecimal idKompanijeKorisnik,
                         int organizacionaJedinica, Set woDownloadFileses) {
       this.id = id;
       this.opis = opis;
       this.naziv = naziv;
       this.imageUrl = imageUrl;
       this.vaziDo = vaziDo;
       this.idKompanijeKorisnik = idKompanijeKorisnik;
       this.organizacionaJedinica = organizacionaJedinica;
       this.woDownloadFileses = woDownloadFileses;
    }
   
     @Id 
    @Column(name="ID", unique=true, nullable=false, precision=22, scale=0)
     @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "rezervacija_seq")
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }

    
    @Column(name="OPIS", length=2000)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="NAZIV", length=400)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="IMAGE_URL", length=500)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="VAZI_DO", length=7)
    public Date getVaziDo() {
        return this.vaziDo;
    }
    
    public void setVaziDo(Date vaziDo) {
        this.vaziDo = vaziDo;
    }

    
    @Column(name="ID_KOMPANIJE_KORISNIK", precision=22, scale=0)
    public BigDecimal getIdKompanijeKorisnik() {
        return this.idKompanijeKorisnik;
    }
    
    public void setIdKompanijeKorisnik(BigDecimal idKompanijeKorisnik) {
        this.idKompanijeKorisnik = idKompanijeKorisnik;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#", precision=22, scale=0)
    public int getOrganizacionaJedinica() {
        return this.organizacionaJedinica;
    }
    
    public void setOrganizacionaJedinica(int organizacionaJedinica) {
        this.organizacionaJedinica = organizacionaJedinica;
    }

@OneToMany(targetEntity = WoDownloadFiles.class, fetch=FetchType.LAZY, mappedBy="woDownloadTip")
    public Set getWoDownloadFileses() {
        return this.woDownloadFileses;
    }
    
    public void setWoDownloadFileses(Set woDownloadFileses) {
        this.woDownloadFileses = woDownloadFileses;
    }




}


