package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcpAtributZaKlasifikacijuId generated by hbm2java
 */
@Embeddable
public class OcpAtributZaKlasifikacijuId  implements java.io.Serializable {


     private int atribut;
     private int vrstaKlasifikacije;
     private String klasifikacija;

    public OcpAtributZaKlasifikacijuId() {
    }

    public OcpAtributZaKlasifikacijuId(int atribut, int vrstaKlasifikacije, String klasifikacija) {
       this.atribut = atribut;
       this.vrstaKlasifikacije = vrstaKlasifikacije;
       this.klasifikacija = klasifikacija;
    }
   


    @Column(name="ATRIBUT#", nullable=false, precision=6, scale=0)
    public int getAtribut() {
        return this.atribut;
    }
    
    public void setAtribut(int atribut) {
        this.atribut = atribut;
    }


    @Column(name="VRSTA_KLASIFIKACIJE#", nullable=false, precision=6, scale=0)
    public int getVrstaKlasifikacije() {
        return this.vrstaKlasifikacije;
    }
    
    public void setVrstaKlasifikacije(int vrstaKlasifikacije) {
        this.vrstaKlasifikacije = vrstaKlasifikacije;
    }


    @Column(name="KLASIFIKACIJA#", nullable=false, length=15)
    public String getKlasifikacija() {
        return this.klasifikacija;
    }
    
    public void setKlasifikacija(String klasifikacija) {
        this.klasifikacija = klasifikacija;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpAtributZaKlasifikacijuId) ) return false;
		 OcpAtributZaKlasifikacijuId castOther = ( OcpAtributZaKlasifikacijuId ) other; 
         
		 return (this.getAtribut()==castOther.getAtribut())
 && (this.getVrstaKlasifikacije()==castOther.getVrstaKlasifikacije())
 && ( (this.getKlasifikacija()==castOther.getKlasifikacija()) || ( this.getKlasifikacija()!=null && castOther.getKlasifikacija()!=null && this.getKlasifikacija().equals(castOther.getKlasifikacija()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAtribut();
         result = 37 * result + this.getVrstaKlasifikacije();
         result = 37 * result + ( getKlasifikacija() == null ? 0 : this.getKlasifikacija().hashCode() );
         return result;
   }   


}


