package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcpZiroRacunId generated by hbm2java
 */
@Embeddable
public class OcpZiroRacunId  implements java.io.Serializable {


     private int poslovniPartner;
     private String ziroRacun;

    public OcpZiroRacunId() {
    }

    public OcpZiroRacunId(int poslovniPartner, String ziroRacun) {
       this.poslovniPartner = poslovniPartner;
       this.ziroRacun = ziroRacun;
    }
   


    @Column(name="POSLOVNI_PARTNER#", nullable=false, precision=7, scale=0)
    public int getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(int poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }


    @Column(name="ZIRO_RACUN#", nullable=false, length=40)
    public String getZiroRacun() {
        return this.ziroRacun;
    }
    
    public void setZiroRacun(String ziroRacun) {
        this.ziroRacun = ziroRacun;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpZiroRacunId) ) return false;
		 OcpZiroRacunId castOther = ( OcpZiroRacunId ) other; 
         
		 return (this.getPoslovniPartner()==castOther.getPoslovniPartner())
 && ( (this.getZiroRacun()==castOther.getZiroRacun()) || ( this.getZiroRacun()!=null && castOther.getZiroRacun()!=null && this.getZiroRacun().equals(castOther.getZiroRacun()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPoslovniPartner();
         result = 37 * result + ( getZiroRacun() == null ? 0 : this.getZiroRacun().hashCode() );
         return result;
   }   


}


