package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcpKontaktiLica generated by hbm2java
 */
@Entity
@Table(name = "OCP_KONTAKTI_LICA", schema = "DAREX")
public class OcpKontaktiLica implements java.io.Serializable {

	private OcpKontaktiLicaId id;
	private OcpLiceZaKontakt ocpLiceZaKontakt;

	public OcpKontaktiLica() {
	}

	public OcpKontaktiLica(OcpKontaktiLicaId id,
			OcpLiceZaKontakt ocpLiceZaKontakt) {
		this.id = id;
		this.ocpLiceZaKontakt = ocpLiceZaKontakt;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "broj", column = @Column(name = "BROJ", nullable = false, length = 50)),
			@AttributeOverride(name = "idVrsteTelefonskogBroja", column = @Column(name = "ID_VRSTE_TELEFONSKOG_BROJA", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "rbr", column = @Column(name = "RBR", nullable = false, precision = 4, scale = 0)),
			@AttributeOverride(name = "poslovniPartner", column = @Column(name = "POSLOVNI_PARTNER#", nullable = false, precision = 7, scale = 0)) })
	public OcpKontaktiLicaId getId() {
		return this.id;
	}

	public void setId(OcpKontaktiLicaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "POSLOVNI_PARTNER#", referencedColumnName = "POSLOVNI_PARTNER#", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "RBR", referencedColumnName = "RBR", nullable = false, insertable = false, updatable = false) })
	public OcpLiceZaKontakt getOcpLiceZaKontakt() {
		return this.ocpLiceZaKontakt;
	}

	public void setOcpLiceZaKontakt(OcpLiceZaKontakt ocpLiceZaKontakt) {
		this.ocpLiceZaKontakt = ocpLiceZaKontakt;
	}

}
