package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcpProizvodJeVrsteId generated by hbm2java
 */
@Embeddable
public class OcpProizvodJeVrsteId  implements java.io.Serializable {


     private int proizvod;
     private byte vrstaProizvoda;

    public OcpProizvodJeVrsteId() {
    }

    public OcpProizvodJeVrsteId(int proizvod, byte vrstaProizvoda) {
       this.proizvod = proizvod;
       this.vrstaProizvoda = vrstaProizvoda;
    }
   


    @Column(name="PROIZVOD#", nullable=false, precision=7, scale=0)
    public int getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(int proizvod) {
        this.proizvod = proizvod;
    }


    @Column(name="VRSTA_PROIZVODA#", nullable=false, precision=2, scale=0)
    public byte getVrstaProizvoda() {
        return this.vrstaProizvoda;
    }
    
    public void setVrstaProizvoda(byte vrstaProizvoda) {
        this.vrstaProizvoda = vrstaProizvoda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpProizvodJeVrsteId) ) return false;
		 OcpProizvodJeVrsteId castOther = ( OcpProizvodJeVrsteId ) other; 
         
		 return (this.getProizvod()==castOther.getProizvod())
 && (this.getVrstaProizvoda()==castOther.getVrstaProizvoda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProizvod();
         result = 37 * result + this.getVrstaProizvoda();
         return result;
   }   


}


