package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzDokumentId generated by hbm2java
 */
@Embeddable
public class UzDokumentId implements java.io.Serializable {

	private String idDokumenta;
	private int idVd;

	public UzDokumentId() {
	}

	public UzDokumentId(String idDokumenta, int idVd) {
		this.idDokumenta = idDokumenta;
		this.idVd = idVd;
	}

	@Column(name = "ID_DOKUMENTA", nullable = false, length = 30)
	public String getIdDokumenta() {
		return this.idDokumenta;
	}

	public void setIdDokumenta(String idDokumenta) {
		this.idDokumenta = idDokumenta;
	}

	@Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)
	public int getIdVd() {
		return this.idVd;
	}

	public void setIdVd(int idVd) {
		this.idVd = idVd;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzDokumentId))
			return false;
		UzDokumentId castOther = (UzDokumentId) other;

		return ((this.getIdDokumenta() == castOther.getIdDokumenta()) || (this
				.getIdDokumenta() != null && castOther.getIdDokumenta() != null && this
				.getIdDokumenta().equals(castOther.getIdDokumenta())))
				&& (this.getIdVd() == castOther.getIdVd());
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getIdDokumenta() == null ? 0 : this.getIdDokumenta()
						.hashCode());
		result = 37 * result + this.getIdVd();
		return result;
	}

}
