package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzDokumentStavkaPakovanjeId generated by hbm2java
 */
@Embeddable
public class UzDokumentStavkaPakovanjeId implements java.io.Serializable {

	private short rbStavke;
	private String idDokumenta;
	private int idVd;
	private BigDecimal kolPoPakovanju;
	private BigDecimal uskladistenaKol;
	private Integer idDokumentaOld;
	private Integer idJediniceSkladistenjaRef;
	private String idpalete;
    private long brojKomada;

	public UzDokumentStavkaPakovanjeId() {
	}

	public UzDokumentStavkaPakovanjeId(short rbStavke, String idDokumenta,
			short idVd, long brojKomada, BigDecimal kolPoPakovanju,
			BigDecimal uskladistenaKol) {
		this.rbStavke = rbStavke;
		this.idDokumenta = idDokumenta;
		this.idVd = idVd;
		this.brojKomada = brojKomada;
		this.kolPoPakovanju = kolPoPakovanju;
		this.uskladistenaKol = uskladistenaKol;
	}

	public UzDokumentStavkaPakovanjeId(short rbStavke, String idDokumenta,
			short idVd, long brojKomada, BigDecimal kolPoPakovanju,
			BigDecimal uskladistenaKol, Integer idDokumentaOld,
			Integer idJediniceSkladistenjaRef, String idpalete) {
		this.rbStavke = rbStavke;
		this.idDokumenta = idDokumenta;
		this.idVd = idVd;
		this.brojKomada = brojKomada;
		this.kolPoPakovanju = kolPoPakovanju;
		this.uskladistenaKol = uskladistenaKol;
		this.idDokumentaOld = idDokumentaOld;
		this.idJediniceSkladistenjaRef = idJediniceSkladistenjaRef;
		this.idpalete = idpalete;
	}

	@Column(name = "RB_STAVKE", nullable = false, precision = 3, scale = 0)
	public short getRbStavke() {
		return this.rbStavke;
	}

	public void setRbStavke(short rbStavke) {
		this.rbStavke = rbStavke;
	}

	@Column(name = "ID_DOKUMENTA", nullable = false, length = 30)
	public String getIdDokumenta() {
		return this.idDokumenta;
	}

	public void setIdDokumenta(String idDokumenta) {
		this.idDokumenta = idDokumenta;
	}

	@Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)
	public int getIdVd() {
		return this.idVd;
	}

	public void setIdVd(int idVd) {
		this.idVd = idVd;
	}

	@Column(name = "BROJ_KOMADA", nullable = false, precision = 15, scale = 0)
	public long getBrojKomada() {
		return this.brojKomada;
	}

	public void setBrojKomada(long brojKomada) {
		this.brojKomada = brojKomada;
	}

	@Column(name = "KOL_PO_PAKOVANJU", nullable = false, precision = 18, scale = 3)
	public BigDecimal getKolPoPakovanju() {
		return this.kolPoPakovanju;
	}

	public void setKolPoPakovanju(BigDecimal kolPoPakovanju) {
		this.kolPoPakovanju = kolPoPakovanju;
	}

	@Column(name = "USKLADISTENA_KOL", nullable = false, precision = 18, scale = 3)
	public BigDecimal getUskladistenaKol() {
		return this.uskladistenaKol;
	}

	public void setUskladistenaKol(BigDecimal uskladistenaKol) {
		this.uskladistenaKol = uskladistenaKol;
	}

	@Column(name = "ID_DOKUMENTA_OLD", precision = 7, scale = 0)
	public Integer getIdDokumentaOld() {
		return this.idDokumentaOld;
	}

	public void setIdDokumentaOld(Integer idDokumentaOld) {
		this.idDokumentaOld = idDokumentaOld;
	}

	@Column(name = "ID_JEDINICE_SKLADISTENJA_REF", precision = 6, scale = 0)
	public Integer getIdJediniceSkladistenjaRef() {
		return this.idJediniceSkladistenjaRef;
	}

	public void setIdJediniceSkladistenjaRef(Integer idJediniceSkladistenjaRef) {
		this.idJediniceSkladistenjaRef = idJediniceSkladistenjaRef;
	}

	@Column(name = "IDPALETE", length = 50)
	public String getIdpalete() {
		return this.idpalete;
	}

	public void setIdpalete(String idpalete) {
		this.idpalete = idpalete;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzDokumentStavkaPakovanjeId))
			return false;
		UzDokumentStavkaPakovanjeId castOther = (UzDokumentStavkaPakovanjeId) other;

		return (this.getRbStavke() == castOther.getRbStavke())
				&& ((this.getIdDokumenta() == castOther.getIdDokumenta()) || (this
						.getIdDokumenta() != null
						&& castOther.getIdDokumenta() != null && this
						.getIdDokumenta().equals(castOther.getIdDokumenta())))
				&& (this.getIdVd() == castOther.getIdVd())
				&& (this.getBrojKomada() == castOther.getBrojKomada())
				&& ((this.getKolPoPakovanju() == castOther.getKolPoPakovanju()) || (this
						.getKolPoPakovanju() != null
						&& castOther.getKolPoPakovanju() != null && this
						.getKolPoPakovanju().equals(
								castOther.getKolPoPakovanju())))
				&& ((this.getUskladistenaKol() == castOther
						.getUskladistenaKol()) || (this.getUskladistenaKol() != null
						&& castOther.getUskladistenaKol() != null && this
						.getUskladistenaKol().equals(
								castOther.getUskladistenaKol())))
				&& ((this.getIdDokumentaOld() == castOther.getIdDokumentaOld()) || (this
						.getIdDokumentaOld() != null
						&& castOther.getIdDokumentaOld() != null && this
						.getIdDokumentaOld().equals(
								castOther.getIdDokumentaOld())))
				&& ((this.getIdJediniceSkladistenjaRef() == castOther
						.getIdJediniceSkladistenjaRef()) || (this
						.getIdJediniceSkladistenjaRef() != null
						&& castOther.getIdJediniceSkladistenjaRef() != null && this
						.getIdJediniceSkladistenjaRef().equals(
								castOther.getIdJediniceSkladistenjaRef())))
				&& ((this.getIdpalete() == castOther.getIdpalete()) || (this
						.getIdpalete() != null
						&& castOther.getIdpalete() != null && this
						.getIdpalete().equals(castOther.getIdpalete())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRbStavke();
		result = 37
				* result
				+ (getIdDokumenta() == null ? 0 : this.getIdDokumenta()
						.hashCode());
		result = 37 * result + this.getIdVd();
		result = 37 * result + (int) this.getBrojKomada();
		result = 37
				* result
				+ (getKolPoPakovanju() == null ? 0 : this.getKolPoPakovanju()
						.hashCode());
		result = 37
				* result
				+ (getUskladistenaKol() == null ? 0 : this.getUskladistenaKol()
						.hashCode());
		result = 37
				* result
				+ (getIdDokumentaOld() == null ? 0 : this.getIdDokumentaOld()
						.hashCode());
		result = 37
				* result
				+ (getIdJediniceSkladistenjaRef() == null ? 0 : this
						.getIdJediniceSkladistenjaRef().hashCode());
		result = 37 * result
				+ (getIdpalete() == null ? 0 : this.getIdpalete().hashCode());
		return result;
	}

}
