package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzDozvPakovanjaId generated by hbm2java
 */
@Embeddable
public class UzDozvPakovanjaId implements java.io.Serializable {

	private Integer vrstaPakovanjaRef;
	private BigDecimal kolPoPakovanju;
	private BigDecimal maxKolPoPakovanju;
	private String transportno;
	private Integer proizvodRef;

	public UzDozvPakovanjaId() {
	}

	public UzDozvPakovanjaId(Integer vrstaPakovanjaRef,
			BigDecimal kolPoPakovanju, BigDecimal maxKolPoPakovanju,
			String transportno, Integer proizvodRef) {
		this.vrstaPakovanjaRef = vrstaPakovanjaRef;
		this.kolPoPakovanju = kolPoPakovanju;
		this.maxKolPoPakovanju = maxKolPoPakovanju;
		this.transportno = transportno;
		this.proizvodRef = proizvodRef;
	}

	@Column(name = "VRSTA_PAKOVANJA_REF", precision = 8, scale = 0)
	public Integer getVrstaPakovanjaRef() {
		return this.vrstaPakovanjaRef;
	}

	public void setVrstaPakovanjaRef(Integer vrstaPakovanjaRef) {
		this.vrstaPakovanjaRef = vrstaPakovanjaRef;
	}

	@Column(name = "KOL_PO_PAKOVANJU", precision = 18, scale = 3)
	public BigDecimal getKolPoPakovanju() {
		return this.kolPoPakovanju;
	}

	public void setKolPoPakovanju(BigDecimal kolPoPakovanju) {
		this.kolPoPakovanju = kolPoPakovanju;
	}

	@Column(name = "MAX_KOL_PO_PAKOVANJU", precision = 18, scale = 3)
	public BigDecimal getMaxKolPoPakovanju() {
		return this.maxKolPoPakovanju;
	}

	public void setMaxKolPoPakovanju(BigDecimal maxKolPoPakovanju) {
		this.maxKolPoPakovanju = maxKolPoPakovanju;
	}

	@Column(name = "TRANSPORTNO", length = 2)
	public String getTransportno() {
		return this.transportno;
	}

	public void setTransportno(String transportno) {
		this.transportno = transportno;
	}

	@Column(name = "PROIZVOD_REF", precision = 8, scale = 0)
	public Integer getProizvodRef() {
		return this.proizvodRef;
	}

	public void setProizvodRef(Integer proizvodRef) {
		this.proizvodRef = proizvodRef;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzDozvPakovanjaId))
			return false;
		UzDozvPakovanjaId castOther = (UzDozvPakovanjaId) other;

		return ((this.getVrstaPakovanjaRef() == castOther
				.getVrstaPakovanjaRef()) || (this.getVrstaPakovanjaRef() != null
				&& castOther.getVrstaPakovanjaRef() != null && this
				.getVrstaPakovanjaRef()
				.equals(castOther.getVrstaPakovanjaRef())))
				&& ((this.getKolPoPakovanju() == castOther.getKolPoPakovanju()) || (this
						.getKolPoPakovanju() != null
						&& castOther.getKolPoPakovanju() != null && this
						.getKolPoPakovanju().equals(
								castOther.getKolPoPakovanju())))
				&& ((this.getMaxKolPoPakovanju() == castOther
						.getMaxKolPoPakovanju()) || (this
						.getMaxKolPoPakovanju() != null
						&& castOther.getMaxKolPoPakovanju() != null && this
						.getMaxKolPoPakovanju().equals(
								castOther.getMaxKolPoPakovanju())))
				&& ((this.getTransportno() == castOther.getTransportno()) || (this
						.getTransportno() != null
						&& castOther.getTransportno() != null && this
						.getTransportno().equals(castOther.getTransportno())))
				&& ((this.getProizvodRef() == castOther.getProizvodRef()) || (this
						.getProizvodRef() != null
						&& castOther.getProizvodRef() != null && this
						.getProizvodRef().equals(castOther.getProizvodRef())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getVrstaPakovanjaRef() == null ? 0 : this
						.getVrstaPakovanjaRef().hashCode());
		result = 37
				* result
				+ (getKolPoPakovanju() == null ? 0 : this.getKolPoPakovanju()
						.hashCode());
		result = 37
				* result
				+ (getMaxKolPoPakovanju() == null ? 0 : this
						.getMaxKolPoPakovanju().hashCode());
		result = 37
				* result
				+ (getTransportno() == null ? 0 : this.getTransportno()
						.hashCode());
		result = 37
				* result
				+ (getProizvodRef() == null ? 0 : this.getProizvodRef()
						.hashCode());
		return result;
	}

}
