package rs.invado.wo.domain.uz;
// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzDozvoljenoSkladistenjeId generated by hbm2java
 */
@Embeddable
public class UzDozvoljenoSkladistenjeId  implements java.io.Serializable {


     private short idJediniceMere;
     private int proizvod;
     private short idTipaJedSklad;

    public UzDozvoljenoSkladistenjeId() {
    }

    public UzDozvoljenoSkladistenjeId(short idJediniceMere, int proizvod, short idTipaJedSklad) {
       this.idJediniceMere = idJediniceMere;
       this.proizvod = proizvod;
       this.idTipaJedSklad = idTipaJedSklad;
    }
   


    @Column(name="ID_JEDINICE_MERE", nullable=false, precision=3, scale=0)
    public short getIdJediniceMere() {
        return this.idJediniceMere;
    }
    
    public void setIdJediniceMere(short idJediniceMere) {
        this.idJediniceMere = idJediniceMere;
    }


    @Column(name="PROIZVOD#", nullable=false, precision=7, scale=0)
    public int getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(int proizvod) {
        this.proizvod = proizvod;
    }


    @Column(name="ID_TIPA_JED_SKLAD", nullable=false, precision=4, scale=0)
    public short getIdTipaJedSklad() {
        return this.idTipaJedSklad;
    }
    
    public void setIdTipaJedSklad(short idTipaJedSklad) {
        this.idTipaJedSklad = idTipaJedSklad;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UzDozvoljenoSkladistenjeId) ) return false;
		 UzDozvoljenoSkladistenjeId castOther = ( UzDozvoljenoSkladistenjeId ) other; 
         
		 return (this.getIdJediniceMere()==castOther.getIdJediniceMere())
 && (this.getProizvod()==castOther.getProizvod())
 && (this.getIdTipaJedSklad()==castOther.getIdTipaJedSklad());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdJediniceMere();
         result = 37 * result + this.getProizvod();
         result = 37 * result + this.getIdTipaJedSklad();
         return result;
   }   


}


