package rs.invado.wo.domain.uz;
// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.*;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UzDokument generated by hbm2java
 */
@Entity
@Table(name = "UZ_DOKUMENT"
        , schema = "DAREX"
)
@NamedNativeQueries({
        @NamedNativeQuery(name = "inserSklDokument", query = "{  ? = call woutil.I_SklDokument (:p_id_vd,:p_radnik_u,:p_status_dokumenta," +
                ":p_nivo_prioriteta,:p_radni_nalog,:p_radnik_s,:p_id_skladista," +
                ":p_radnik_r,:p_poslovni_partner_kd,:p_organizaciona_jedinica_kd,:p_organizaciona_jedinica_pk,:p_poslovni_partner_pk," +
                ":p_adresa_isporuke_robe,:p_datum_promene,:p_rok_vracanja,:p_spoljni_broj_dokumenta,:p_nacin_otpreme,:p_datum_overe," +
                ":p_datum_i_vreme_nki,:p_datum_i_vreme_nri,:p_status_dokumenta_po,:p_organizaciona_jedinica_c,:p_id_cenovnik," +
                ":p_id_klasa_cene,:p_id_skladista_2,:p_organizaciona_jedinica_real,:p_radnik_tp,:p_radnik_ov,:p_id_vd_ot," +
                ":p_poslovni_partner_ot,:p_godina_ot,:p_datum_dokumenta_ot,:p_id_vd_vrste,:p_proizvod,:p_rb_serije,:p_id_ciklusa," +
                ":p_id_rb_rn,:p_id_skladista_za,:p_radnik_z,:p_vlasnik,:p_br_rn_odr,:p_id_vd_odr,:p_organizaciona_jedinica_odr," +
                ":p_godina_odr,:p_vrsta_stavke,:p_godina,:p_napomena,:p_iddokumentug,:p_organizacionajedinicaug,:p_idvdug," +
                ":p_godinaug,:p_vrstaprevoza,:p_vozilo) }",
                resultClass = UzDokument.class, hints = {@javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true")}),
        @NamedNativeQuery(name = "inserQuSklDokument", query = "{  ? = call woutil.I_SklDokument (?,?,?," +
                "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?," +
                "?,?,?,?, ?) }",
                resultClass = UzDokument.class, hints = {@javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true")}),
        @NamedNativeQuery(name = "inserSklDokumentNull", query = "{  ? = call woutil.I_SklDokument (:p_id_vd,:p_radnik_u,:p_status_dokumenta," +
                "null,null,:p_radnik_s,:p_id_skladista, null,:p_poslovni_partner_kd,:p_organizaciona_jedinica_kd,:p_organizaciona_jedinica_pk," +
                " :p_poslovni_partner_pk, :p_adresa_isporuke_robe,:p_datum_promene,null,:p_spoljni_broj_dokumenta,null,:p_datum_overe," +
                "null,null,null,:p_organizaciona_jedinica_c,:p_id_cenovnik,:p_id_klasa_cene,null,:p_organizaciona_jedinica_real,:p_radnik_tp," +
                ":p_radnik_ov,null,null,null,null,null,null,null,null,null,:p_id_skladista_za,null,null,null,null,null," +
                "null,:p_vrsta_stavke,:p_godina,null,null,null,null,null,:p_vrstaprevoza,null) }",
                resultClass = UzDokument.class, hints = {@javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true")}),
        @NamedNativeQuery(name = "chkSklDOkument", query = " select u.* from uz_dokument u where u.id_dokumenta = :iddok ",
                resultClass = UzDokument.class)})


public class UzDokument implements java.io.Serializable {


    private UzDokumentId id;
    private UzSkladiste uzSkladiste;
    private short brojPoslednjeStavke;
    private int radnikU;
    private String statusDokumenta;
    private Short nivoPrioriteta;
    private Long radniNalog;
    private Integer radnikS;
    private Integer radnikR;
    private Integer poslovniPartnerKd;
    private Integer organizacionaJedinicaKd;
    private Integer organizacionaJedinicaPk;
    private Integer poslovniPartnerPk;
    private String adresaIsporukeRobe;
    private Date datumPromene;
    private Date rokVracanja;
    private String spoljniBrojDokumenta;
    private String nacinOtpreme;
    private Date datumOvere;
    private Date datumIVremeNki;
    private Date datumIVremeNri;
    private String statusDokumentaPo;
    private Integer organizacionaJedinicaC;
    private Integer idCenovnik;
    private Integer idKlasaCene;
    private Integer organizacionaJedinicaReal;
    private Integer radnikTp;
    private Integer radnikOv;
    private Short idVdOt;
    private Integer poslovniPartnerOt;
    private Short godinaOt;
    private Date datumDokumentaOt;
    private Short idVdVrste;
    private Date sysDatumIVreme;
    private Integer proizvod;
    private BigDecimal rbSerije;
    private BigDecimal idCiklusa;
    private BigDecimal idRbRn;
    private Integer idSkladistaZa;
    private String napomena;
    private String radnikZ;
    private Integer brojRnOdr;
    private Short idVdOdr;
    private Integer organizacionaJedinicaOdr;
    private Short godinaOdr;
    private Integer vrstaStavke;
    private Integer vlasnikPp;
    private String idDokumentaUg;
    private Integer organizacionaJedinicaUg;
    private Short idVdUg;
    private Short godinaUg;
    private Integer godina;
    private Integer idDokumentaOld;
    private String internaNapomena;
    private Integer vrstaPrevoza;
    private BigDecimal redosledPakovanja;
    private Date datumRp;
    private BigDecimal proizvodJedOdrRef;
    private Set uzDokumentStavkas = new HashSet(0);
    private UzDokumentUsloviPlacanja uzDokumentUsloviPlacanja;

    public UzDokument() {
    }


    public UzDokument(UzDokumentId id, short brojPoslednjeStavke, int radnikU, String statusDokumenta) {
        this.id = id;
        this.brojPoslednjeStavke = brojPoslednjeStavke;
        this.radnikU = radnikU;
        this.statusDokumenta = statusDokumenta;
    }

    public UzDokument(UzDokumentId id, UzSkladiste uzSkladiste, short brojPoslednjeStavke, int radnikU, String statusDokumenta, Short nivoPrioriteta, Long radniNalog, Integer radnikS, Integer radnikR, Integer poslovniPartnerKd, Integer organizacionaJedinicaKd, Integer organizacionaJedinicaPk, Integer poslovniPartnerPk, String adresaIsporukeRobe, Date datumPromene, Date rokVracanja, String spoljniBrojDokumenta, String nacinOtpreme, Date datumOvere, Date datumIVremeNki, Date datumIVremeNri, String statusDokumentaPo, Integer organizacionaJedinicaC, Integer idCenovnik, Integer idKlasaCene, Integer organizacionaJedinicaReal, Integer radnikTp, Integer radnikOv, Short idVdOt, Integer poslovniPartnerOt, Short godinaOt, Date datumDokumentaOt, Short idVdVrste, Date sysDatumIVreme, Integer proizvod, BigDecimal rbSerije, BigDecimal idCiklusa, BigDecimal idRbRn, Integer idSkladistaZa, String napomena, String radnikZ, Integer brojRnOdr, Short idVdOdr, Integer organizacionaJedinicaOdr, Short godinaOdr, Integer vrstaStavke, Integer vlasnikPp, String idDokumentaUg, Integer organizacionaJedinicaUg, Short idVdUg, Short godinaUg, Integer godina, Integer idDokumentaOld, String internaNapomena, Integer vrstaPrevoza, BigDecimal redosledPakovanja, Date datumRp, BigDecimal proizvodJedOdrRef, Set uzDokumentStavkas, UzDokumentUsloviPlacanja uzDokumentUsloviPlacanja) {
        this.id = id;
        this.uzSkladiste = uzSkladiste;
        this.brojPoslednjeStavke = brojPoslednjeStavke;
        this.radnikU = radnikU;
        this.statusDokumenta = statusDokumenta;
        this.nivoPrioriteta = nivoPrioriteta;
        this.radniNalog = radniNalog;
        this.radnikS = radnikS;
        this.radnikR = radnikR;
        this.poslovniPartnerKd = poslovniPartnerKd;
        this.organizacionaJedinicaKd = organizacionaJedinicaKd;
        this.organizacionaJedinicaPk = organizacionaJedinicaPk;
        this.poslovniPartnerPk = poslovniPartnerPk;
        this.adresaIsporukeRobe = adresaIsporukeRobe;
        this.datumPromene = datumPromene;
        this.rokVracanja = rokVracanja;
        this.spoljniBrojDokumenta = spoljniBrojDokumenta;
        this.nacinOtpreme = nacinOtpreme;
        this.datumOvere = datumOvere;
        this.datumIVremeNki = datumIVremeNki;
        this.datumIVremeNri = datumIVremeNri;
        this.statusDokumentaPo = statusDokumentaPo;
        this.organizacionaJedinicaC = organizacionaJedinicaC;
        this.idCenovnik = idCenovnik;
        this.idKlasaCene = idKlasaCene;
        this.organizacionaJedinicaReal = organizacionaJedinicaReal;
        this.radnikTp = radnikTp;
        this.radnikOv = radnikOv;
        this.idVdOt = idVdOt;
        this.poslovniPartnerOt = poslovniPartnerOt;
        this.godinaOt = godinaOt;
        this.datumDokumentaOt = datumDokumentaOt;
        this.idVdVrste = idVdVrste;
        this.sysDatumIVreme = sysDatumIVreme;
        this.proizvod = proizvod;
        this.rbSerije = rbSerije;
        this.idCiklusa = idCiklusa;
        this.idRbRn = idRbRn;
        this.idSkladistaZa = idSkladistaZa;
        this.napomena = napomena;
        this.radnikZ = radnikZ;
        this.brojRnOdr = brojRnOdr;
        this.idVdOdr = idVdOdr;
        this.organizacionaJedinicaOdr = organizacionaJedinicaOdr;
        this.godinaOdr = godinaOdr;
        this.vrstaStavke = vrstaStavke;
        this.vlasnikPp = vlasnikPp;
        this.idDokumentaUg = idDokumentaUg;
        this.organizacionaJedinicaUg = organizacionaJedinicaUg;
        this.idVdUg = idVdUg;
        this.godinaUg = godinaUg;
        this.godina = godina;
        this.idDokumentaOld = idDokumentaOld;
        this.internaNapomena = internaNapomena;
        this.vrstaPrevoza = vrstaPrevoza;
        this.redosledPakovanja = redosledPakovanja;
        this.datumRp = datumRp;
        this.proizvodJedOdrRef = proizvodJedOdrRef;
        this.uzDokumentStavkas = uzDokumentStavkas;
        this.uzDokumentUsloviPlacanja = uzDokumentUsloviPlacanja;
    }

    @EmbeddedId


    @AttributeOverrides({
            @AttributeOverride(name = "idDokumenta", column = @Column(name = "ID_DOKUMENTA", nullable = false, length = 30)),
            @AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0))})
    public UzDokumentId getId() {
        return this.id;
    }

    public void setId(UzDokumentId id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_SKLADISTA")
    public UzSkladiste getUzSkladiste() {
        return this.uzSkladiste;
    }

    public void setUzSkladiste(UzSkladiste uzSkladiste) {
        this.uzSkladiste = uzSkladiste;
    }


    @Column(name = "BROJ_POSLEDNJE_STAVKE", nullable = false, precision = 3, scale = 0)
    public short getBrojPoslednjeStavke() {
        return this.brojPoslednjeStavke;
    }

    public void setBrojPoslednjeStavke(short brojPoslednjeStavke) {
        this.brojPoslednjeStavke = brojPoslednjeStavke;
    }


    @Column(name = "RADNIK_U", nullable = false, precision = 6, scale = 0)
    public int getRadnikU() {
        return this.radnikU;
    }

    public void setRadnikU(int radnikU) {
        this.radnikU = radnikU;
    }


    @Column(name = "STATUS_DOKUMENTA", nullable = false, length = 1)
    public String getStatusDokumenta() {
        return this.statusDokumenta;
    }

    public void setStatusDokumenta(String statusDokumenta) {
        this.statusDokumenta = statusDokumenta;
    }


    @Column(name = "NIVO_PRIORITETA", precision = 4, scale = 0)
    public Short getNivoPrioriteta() {
        return this.nivoPrioriteta;
    }

    public void setNivoPrioriteta(Short nivoPrioriteta) {
        this.nivoPrioriteta = nivoPrioriteta;
    }


    @Column(name = "RADNI_NALOG", precision = 13, scale = 0)
    public Long getRadniNalog() {
        return this.radniNalog;
    }

    public void setRadniNalog(Long radniNalog) {
        this.radniNalog = radniNalog;
    }


    @Column(name = "RADNIK_S", precision = 6, scale = 0)
    public Integer getRadnikS() {
        return this.radnikS;
    }

    public void setRadnikS(Integer radnikS) {
        this.radnikS = radnikS;
    }


    @Column(name = "RADNIK_R", precision = 6, scale = 0)
    public Integer getRadnikR() {
        return this.radnikR;
    }

    public void setRadnikR(Integer radnikR) {
        this.radnikR = radnikR;
    }


    @Column(name = "POSLOVNI_PARTNER#_KD", precision = 7, scale = 0)
    public Integer getPoslovniPartnerKd() {
        return this.poslovniPartnerKd;
    }

    public void setPoslovniPartnerKd(Integer poslovniPartnerKd) {
        this.poslovniPartnerKd = poslovniPartnerKd;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_KD", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaKd() {
        return this.organizacionaJedinicaKd;
    }

    public void setOrganizacionaJedinicaKd(Integer organizacionaJedinicaKd) {
        this.organizacionaJedinicaKd = organizacionaJedinicaKd;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_PK", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaPk() {
        return this.organizacionaJedinicaPk;
    }

    public void setOrganizacionaJedinicaPk(Integer organizacionaJedinicaPk) {
        this.organizacionaJedinicaPk = organizacionaJedinicaPk;
    }


    @Column(name = "POSLOVNI_PARTNER#_PK", precision = 7, scale = 0)
    public Integer getPoslovniPartnerPk() {
        return this.poslovniPartnerPk;
    }

    public void setPoslovniPartnerPk(Integer poslovniPartnerPk) {
        this.poslovniPartnerPk = poslovniPartnerPk;
    }


    @Column(name = "ADRESA_ISPORUKE_ROBE", length = 80)
    public String getAdresaIsporukeRobe() {
        return this.adresaIsporukeRobe;
    }

    public void setAdresaIsporukeRobe(String adresaIsporukeRobe) {
        this.adresaIsporukeRobe = adresaIsporukeRobe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_PROMENE", length = 7)
    public Date getDatumPromene() {
        return this.datumPromene;
    }

    public void setDatumPromene(Date datumPromene) {
        this.datumPromene = datumPromene;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ROK_VRACANJA", length = 7)
    public Date getRokVracanja() {
        return this.rokVracanja;
    }

    public void setRokVracanja(Date rokVracanja) {
        this.rokVracanja = rokVracanja;
    }


    @Column(name = "SPOLJNI_BROJ_DOKUMENTA", length = 50)
    public String getSpoljniBrojDokumenta() {
        return this.spoljniBrojDokumenta;
    }

    public void setSpoljniBrojDokumenta(String spoljniBrojDokumenta) {
        this.spoljniBrojDokumenta = spoljniBrojDokumenta;
    }


    @Column(name = "NACIN_OTPREME")
    public String getNacinOtpreme() {
        return this.nacinOtpreme;
    }

    public void setNacinOtpreme(String nacinOtpreme) {
        this.nacinOtpreme = nacinOtpreme;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_OVERE", length = 7)
    public Date getDatumOvere() {
        return this.datumOvere;
    }

    public void setDatumOvere(Date datumOvere) {
        this.datumOvere = datumOvere;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_I_VREME_NKI", length = 7)
    public Date getDatumIVremeNki() {
        return this.datumIVremeNki;
    }

    public void setDatumIVremeNki(Date datumIVremeNki) {
        this.datumIVremeNki = datumIVremeNki;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_I_VREME_NRI", length = 7)
    public Date getDatumIVremeNri() {
        return this.datumIVremeNri;
    }

    public void setDatumIVremeNri(Date datumIVremeNri) {
        this.datumIVremeNri = datumIVremeNri;
    }


    @Column(name = "STATUS_DOKUMENTA_PO", length = 2)
    public String getStatusDokumentaPo() {
        return this.statusDokumentaPo;
    }

    public void setStatusDokumentaPo(String statusDokumentaPo) {
        this.statusDokumentaPo = statusDokumentaPo;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_C", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaC() {
        return this.organizacionaJedinicaC;
    }

    public void setOrganizacionaJedinicaC(Integer organizacionaJedinicaC) {
        this.organizacionaJedinicaC = organizacionaJedinicaC;
    }


    @Column(name = "ID_CENOVNIK", precision = 5, scale = 0)
    public Integer getIdCenovnik() {
        return this.idCenovnik;
    }

    public void setIdCenovnik(Integer idCenovnik) {
        this.idCenovnik = idCenovnik;
    }


    @Column(name = "ID_KLASA_CENE", precision = 2, scale = 0, nullable = true)
    public Integer getIdKlasaCene() {
        return this.idKlasaCene;
    }

    public void setIdKlasaCene(Integer idKlasaCene) {
        this.idKlasaCene = idKlasaCene;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_REAL", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaReal() {
        return this.organizacionaJedinicaReal;
    }

    public void setOrganizacionaJedinicaReal(Integer organizacionaJedinicaReal) {
        this.organizacionaJedinicaReal = organizacionaJedinicaReal;
    }


    @Column(name = "RADNIK#_TP", precision = 6, scale = 0)
    public Integer getRadnikTp() {
        return this.radnikTp;
    }

    public void setRadnikTp(Integer radnikTp) {
        this.radnikTp = radnikTp;
    }


    @Column(name = "RADNIK#_OV", precision = 6, scale = 0)
    public Integer getRadnikOv() {
        return this.radnikOv;
    }

    public void setRadnikOv(Integer radnikOv) {
        this.radnikOv = radnikOv;
    }


    @Column(name = "ID_VD_OT", precision = 3, scale = 0)
    public Short getIdVdOt() {
        return this.idVdOt;
    }

    public void setIdVdOt(Short idVdOt) {
        this.idVdOt = idVdOt;
    }


    @Column(name = "POSLOVNI_PARTNER#_OT", precision = 7, scale = 0)
    public Integer getPoslovniPartnerOt() {
        return this.poslovniPartnerOt;
    }

    public void setPoslovniPartnerOt(Integer poslovniPartnerOt) {
        this.poslovniPartnerOt = poslovniPartnerOt;
    }


    @Column(name = "GODINA_OT", precision = 4, scale = 0)
    public Short getGodinaOt() {
        return this.godinaOt;
    }

    public void setGodinaOt(Short godinaOt) {
        this.godinaOt = godinaOt;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_DOKUMENTA_OT", length = 7)
    public Date getDatumDokumentaOt() {
        return this.datumDokumentaOt;
    }

    public void setDatumDokumentaOt(Date datumDokumentaOt) {
        this.datumDokumentaOt = datumDokumentaOt;
    }


    @Column(name = "ID_VD_VRSTE", precision = 3, scale = 0)
    public Short getIdVdVrste() {
        return this.idVdVrste;
    }

    public void setIdVdVrste(Short idVdVrste) {
        this.idVdVrste = idVdVrste;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "SYS_DATUM_I_VREME", length = 7)
    public Date getSysDatumIVreme() {
        return this.sysDatumIVreme;
    }

    public void setSysDatumIVreme(Date sysDatumIVreme) {
        this.sysDatumIVreme = sysDatumIVreme;
    }


    @Column(name = "PROIZVOD#", precision = 7, scale = 0)
    public Integer getProizvod() {
        return this.proizvod;
    }

    public void setProizvod(Integer proizvod) {
        this.proizvod = proizvod;
    }


    @Column(name = "RB_SERIJE", precision = 38, scale = 0)
    public BigDecimal getRbSerije() {
        return this.rbSerije;
    }

    public void setRbSerije(BigDecimal rbSerije) {
        this.rbSerije = rbSerije;
    }


    @Column(name = "ID_CIKLUSA", precision = 38, scale = 0)
    public BigDecimal getIdCiklusa() {
        return this.idCiklusa;
    }

    public void setIdCiklusa(BigDecimal idCiklusa) {
        this.idCiklusa = idCiklusa;
    }


    @Column(name = "ID_RB_RN", precision = 38, scale = 0)
    public BigDecimal getIdRbRn() {
        return this.idRbRn;
    }

    public void setIdRbRn(BigDecimal idRbRn) {
        this.idRbRn = idRbRn;
    }


    @Column(name = "ID_SKLADISTA_ZA", precision = 5, scale = 0)
    public Integer getIdSkladistaZa() {
        return this.idSkladistaZa;
    }

    public void setIdSkladistaZa(Integer idSkladistaZa) {
        this.idSkladistaZa = idSkladistaZa;
    }


    @Column(name = "NAPOMENA", length = 2000)
    public String getNapomena() {
        return this.napomena;
    }

    public void setNapomena(String napomena) {
        this.napomena = napomena;
    }


    @Column(name = "RADNIK_Z", length = 6)
    public String getRadnikZ() {
        return this.radnikZ;
    }

    public void setRadnikZ(String radnikZ) {
        this.radnikZ = radnikZ;
    }


    @Column(name = "BROJ_RN_ODR", precision = 6, scale = 0)
    public Integer getBrojRnOdr() {
        return this.brojRnOdr;
    }

    public void setBrojRnOdr(Integer brojRnOdr) {
        this.brojRnOdr = brojRnOdr;
    }


    @Column(name = "ID_VD_ODR", precision = 3, scale = 0)
    public Short getIdVdOdr() {
        return this.idVdOdr;
    }

    public void setIdVdOdr(Short idVdOdr) {
        this.idVdOdr = idVdOdr;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_ODR", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaOdr() {
        return this.organizacionaJedinicaOdr;
    }

    public void setOrganizacionaJedinicaOdr(Integer organizacionaJedinicaOdr) {
        this.organizacionaJedinicaOdr = organizacionaJedinicaOdr;
    }


    @Column(name = "GODINA_ODR", precision = 4, scale = 0)
    public Short getGodinaOdr() {
        return this.godinaOdr;
    }

    public void setGodinaOdr(Short godinaOdr) {
        this.godinaOdr = godinaOdr;
    }


    @Column(name = "VRSTA_STAVKE#", precision = 3, scale = 0)
    public Integer getVrstaStavke() {
        return this.vrstaStavke;
    }

    public void setVrstaStavke(Integer vrstaStavke) {
        this.vrstaStavke = vrstaStavke;
    }


    @Column(name = "VLASNIK_PP", precision = 7, scale = 0)
    public Integer getVlasnikPp() {
        return this.vlasnikPp;
    }

    public void setVlasnikPp(Integer vlasnikPp) {
        this.vlasnikPp = vlasnikPp;
    }


    @Column(name = "ID_DOKUMENTA_UG", length = 30)
    public String getIdDokumentaUg() {
        return this.idDokumentaUg;
    }

    public void setIdDokumentaUg(String idDokumentaUg) {
        this.idDokumentaUg = idDokumentaUg;
    }


    @Column(name = "ORGANIZACIONA_JEDINICA#_UG", precision = 5, scale = 0)
    public Integer getOrganizacionaJedinicaUg() {
        return this.organizacionaJedinicaUg;
    }

    public void setOrganizacionaJedinicaUg(Integer organizacionaJedinicaUg) {
        this.organizacionaJedinicaUg = organizacionaJedinicaUg;
    }


    @Column(name = "ID_VD_UG", precision = 3, scale = 0)
    public Short getIdVdUg() {
        return this.idVdUg;
    }

    public void setIdVdUg(Short idVdUg) {
        this.idVdUg = idVdUg;
    }


    @Column(name = "GODINA_UG", precision = 4, scale = 0)
    public Short getGodinaUg() {
        return this.godinaUg;
    }

    public void setGodinaUg(Short godinaUg) {
        this.godinaUg = godinaUg;
    }


    @Column(name = "GODINA", precision = 4, scale = 0)
    public Integer getGodina() {
        return this.godina;
    }

    public void setGodina(Integer godina) {
        this.godina = godina;
    }


    @Column(name = "ID_DOKUMENTA_OLD", precision = 7, scale = 0)
    public Integer getIdDokumentaOld() {
        return this.idDokumentaOld;
    }

    public void setIdDokumentaOld(Integer idDokumentaOld) {
        this.idDokumentaOld = idDokumentaOld;
    }


    @Column(name = "INTERNA_NAPOMENA", length = 4000)
    public String getInternaNapomena() {
        return this.internaNapomena;
    }

    public void setInternaNapomena(String internaNapomena) {
        this.internaNapomena = internaNapomena;
    }


    @Column(name = "VRSTA_PREVOZA#", precision = 2, scale = 0)
    public Integer getVrstaPrevoza() {
        return this.vrstaPrevoza;
    }

    public void setVrstaPrevoza(Integer vrstaPrevoza) {
        this.vrstaPrevoza = vrstaPrevoza;
    }


    @Column(name = "REDOSLED_PAKOVANJA", precision = 22, scale = 0)
    public BigDecimal getRedosledPakovanja() {
        return this.redosledPakovanja;
    }

    public void setRedosledPakovanja(BigDecimal redosledPakovanja) {
        this.redosledPakovanja = redosledPakovanja;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATUM_RP", length = 7)
    public Date getDatumRp() {
        return this.datumRp;
    }

    public void setDatumRp(Date datumRp) {
        this.datumRp = datumRp;
    }


    @Column(name = "PROIZVOD_JED_ODR_REF", precision = 22, scale = 0)
    public BigDecimal getProizvodJedOdrRef() {
        return this.proizvodJedOdrRef;
    }

    public void setProizvodJedOdrRef(BigDecimal proizvodJedOdrRef) {
        this.proizvodJedOdrRef = proizvodJedOdrRef;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy= "uzDokument")
    public Set<UzDokumentStavka> getUzDokumentStavkas() {
        return this.uzDokumentStavkas;
    }

    public void setUzDokumentStavkas(Set uzDokumentStavkas) {
        this.uzDokumentStavkas = uzDokumentStavkas;
    }

    //@OneToOne(fetch = FetchType.LAZY, mappedBy = "uzDokument")
    @Transient
    public UzDokumentUsloviPlacanja getUzDokumentUsloviPlacanja() {
        return this.uzDokumentUsloviPlacanja;
    }

    public void setUzDokumentUsloviPlacanja(UzDokumentUsloviPlacanja uzDokumentUsloviPlacanja) {
        this.uzDokumentUsloviPlacanja = uzDokumentUsloviPlacanja;
    }


}


