package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzOperacijeNaDokumentuId generated by hbm2java
 */
@Embeddable
public class UzOperacijeNaDokumentuId implements java.io.Serializable {

	private short idVd;
	private String vrstaPromene;
	private Short zaliheJskl;
	private Short zaliheNaPaleti;
	private Short stanjeZalihaSkladista;
	private Short izuzimanjePoZahtevima;
	private Short transakcijaSkladista;
	private Short porucenaKolicina;
	private Short kolicinaPromenePo;
	private Short sprovodniList;
	private Short kolicinaPromener;
	private Short dokumentDobavljaca;
	private Short poCenovniku;
	private Short vrstaPromeneStavke;
	private Short internaEksternaPromena;
	private Short finansiskiDokument;
	private Short porudzbenica;
	private BigDecimal rootoj;
	private BigDecimal maxbrojstavki;
	private String delimicnoizdavanje;

	public UzOperacijeNaDokumentuId() {
	}

	public UzOperacijeNaDokumentuId(short idVd, String vrstaPromene) {
		this.idVd = idVd;
		this.vrstaPromene = vrstaPromene;
	}

	public UzOperacijeNaDokumentuId(short idVd, String vrstaPromene,
			Short zaliheJskl, Short zaliheNaPaleti,
			Short stanjeZalihaSkladista, Short izuzimanjePoZahtevima,
			Short transakcijaSkladista, Short porucenaKolicina,
			Short kolicinaPromenePo, Short sprovodniList,
			Short kolicinaPromener, Short dokumentDobavljaca,
			Short poCenovniku, Short vrstaPromeneStavke,
			Short internaEksternaPromena, Short finansiskiDokument,
			Short porudzbenica, BigDecimal rootoj, BigDecimal maxbrojstavki,
			String delimicnoizdavanje) {
		this.idVd = idVd;
		this.vrstaPromene = vrstaPromene;
		this.zaliheJskl = zaliheJskl;
		this.zaliheNaPaleti = zaliheNaPaleti;
		this.stanjeZalihaSkladista = stanjeZalihaSkladista;
		this.izuzimanjePoZahtevima = izuzimanjePoZahtevima;
		this.transakcijaSkladista = transakcijaSkladista;
		this.porucenaKolicina = porucenaKolicina;
		this.kolicinaPromenePo = kolicinaPromenePo;
		this.sprovodniList = sprovodniList;
		this.kolicinaPromener = kolicinaPromener;
		this.dokumentDobavljaca = dokumentDobavljaca;
		this.poCenovniku = poCenovniku;
		this.vrstaPromeneStavke = vrstaPromeneStavke;
		this.internaEksternaPromena = internaEksternaPromena;
		this.finansiskiDokument = finansiskiDokument;
		this.porudzbenica = porudzbenica;
		this.rootoj = rootoj;
		this.maxbrojstavki = maxbrojstavki;
		this.delimicnoizdavanje = delimicnoizdavanje;
	}

	@Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)
	public short getIdVd() {
		return this.idVd;
	}

	public void setIdVd(short idVd) {
		this.idVd = idVd;
	}

	@Column(name = "VRSTA_PROMENE", nullable = false, length = 1)
	public String getVrstaPromene() {
		return this.vrstaPromene;
	}

	public void setVrstaPromene(String vrstaPromene) {
		this.vrstaPromene = vrstaPromene;
	}

	@Column(name = "ZALIHE_JSKL", precision = 3, scale = 0)
	public Short getZaliheJskl() {
		return this.zaliheJskl;
	}

	public void setZaliheJskl(Short zaliheJskl) {
		this.zaliheJskl = zaliheJskl;
	}

	@Column(name = "ZALIHE_NA_PALETI", precision = 3, scale = 0)
	public Short getZaliheNaPaleti() {
		return this.zaliheNaPaleti;
	}

	public void setZaliheNaPaleti(Short zaliheNaPaleti) {
		this.zaliheNaPaleti = zaliheNaPaleti;
	}

	@Column(name = "STANJE_ZALIHA_SKLADISTA", precision = 3, scale = 0)
	public Short getStanjeZalihaSkladista() {
		return this.stanjeZalihaSkladista;
	}

	public void setStanjeZalihaSkladista(Short stanjeZalihaSkladista) {
		this.stanjeZalihaSkladista = stanjeZalihaSkladista;
	}

	@Column(name = "IZUZIMANJE_PO_ZAHTEVIMA", precision = 3, scale = 0)
	public Short getIzuzimanjePoZahtevima() {
		return this.izuzimanjePoZahtevima;
	}

	public void setIzuzimanjePoZahtevima(Short izuzimanjePoZahtevima) {
		this.izuzimanjePoZahtevima = izuzimanjePoZahtevima;
	}

	@Column(name = "TRANSAKCIJA_SKLADISTA", precision = 3, scale = 0)
	public Short getTransakcijaSkladista() {
		return this.transakcijaSkladista;
	}

	public void setTransakcijaSkladista(Short transakcijaSkladista) {
		this.transakcijaSkladista = transakcijaSkladista;
	}

	@Column(name = "PORUCENA_KOLICINA", precision = 3, scale = 0)
	public Short getPorucenaKolicina() {
		return this.porucenaKolicina;
	}

	public void setPorucenaKolicina(Short porucenaKolicina) {
		this.porucenaKolicina = porucenaKolicina;
	}

	@Column(name = "KOLICINA_PROMENE_PO", precision = 3, scale = 0)
	public Short getKolicinaPromenePo() {
		return this.kolicinaPromenePo;
	}

	public void setKolicinaPromenePo(Short kolicinaPromenePo) {
		this.kolicinaPromenePo = kolicinaPromenePo;
	}

	@Column(name = "SPROVODNI_LIST", precision = 3, scale = 0)
	public Short getSprovodniList() {
		return this.sprovodniList;
	}

	public void setSprovodniList(Short sprovodniList) {
		this.sprovodniList = sprovodniList;
	}

	@Column(name = "KOLICINA_PROMENER", precision = 3, scale = 0)
	public Short getKolicinaPromener() {
		return this.kolicinaPromener;
	}

	public void setKolicinaPromener(Short kolicinaPromener) {
		this.kolicinaPromener = kolicinaPromener;
	}

	@Column(name = "DOKUMENT_DOBAVLJACA", precision = 3, scale = 0)
	public Short getDokumentDobavljaca() {
		return this.dokumentDobavljaca;
	}

	public void setDokumentDobavljaca(Short dokumentDobavljaca) {
		this.dokumentDobavljaca = dokumentDobavljaca;
	}

	@Column(name = "PO_CENOVNIKU", precision = 3, scale = 0)
	public Short getPoCenovniku() {
		return this.poCenovniku;
	}

	public void setPoCenovniku(Short poCenovniku) {
		this.poCenovniku = poCenovniku;
	}

	@Column(name = "VRSTA_PROMENE_STAVKE", precision = 3, scale = 0)
	public Short getVrstaPromeneStavke() {
		return this.vrstaPromeneStavke;
	}

	public void setVrstaPromeneStavke(Short vrstaPromeneStavke) {
		this.vrstaPromeneStavke = vrstaPromeneStavke;
	}

	@Column(name = "INTERNA_EKSTERNA_PROMENA", precision = 3, scale = 0)
	public Short getInternaEksternaPromena() {
		return this.internaEksternaPromena;
	}

	public void setInternaEksternaPromena(Short internaEksternaPromena) {
		this.internaEksternaPromena = internaEksternaPromena;
	}

	@Column(name = "FINANSISKI_DOKUMENT", precision = 3, scale = 0)
	public Short getFinansiskiDokument() {
		return this.finansiskiDokument;
	}

	public void setFinansiskiDokument(Short finansiskiDokument) {
		this.finansiskiDokument = finansiskiDokument;
	}

	@Column(name = "PORUDZBENICA", precision = 3, scale = 0)
	public Short getPorudzbenica() {
		return this.porudzbenica;
	}

	public void setPorudzbenica(Short porudzbenica) {
		this.porudzbenica = porudzbenica;
	}

	@Column(name = "ROOTOJ", precision = 22, scale = 0)
	public BigDecimal getRootoj() {
		return this.rootoj;
	}

	public void setRootoj(BigDecimal rootoj) {
		this.rootoj = rootoj;
	}

	@Column(name = "MAXBROJSTAVKI", precision = 22, scale = 0)
	public BigDecimal getMaxbrojstavki() {
		return this.maxbrojstavki;
	}

	public void setMaxbrojstavki(BigDecimal maxbrojstavki) {
		this.maxbrojstavki = maxbrojstavki;
	}

	@Column(name = "DELIMICNOIZDAVANJE", length = 2)
	public String getDelimicnoizdavanje() {
		return this.delimicnoizdavanje;
	}

	public void setDelimicnoizdavanje(String delimicnoizdavanje) {
		this.delimicnoizdavanje = delimicnoizdavanje;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzOperacijeNaDokumentuId))
			return false;
		UzOperacijeNaDokumentuId castOther = (UzOperacijeNaDokumentuId) other;

		return (this.getIdVd() == castOther.getIdVd())
				&& ((this.getVrstaPromene() == castOther.getVrstaPromene()) || (this
						.getVrstaPromene() != null
						&& castOther.getVrstaPromene() != null && this
						.getVrstaPromene().equals(castOther.getVrstaPromene())))
				&& ((this.getZaliheJskl() == castOther.getZaliheJskl()) || (this
						.getZaliheJskl() != null
						&& castOther.getZaliheJskl() != null && this
						.getZaliheJskl().equals(castOther.getZaliheJskl())))
				&& ((this.getZaliheNaPaleti() == castOther.getZaliheNaPaleti()) || (this
						.getZaliheNaPaleti() != null
						&& castOther.getZaliheNaPaleti() != null && this
						.getZaliheNaPaleti().equals(
								castOther.getZaliheNaPaleti())))
				&& ((this.getStanjeZalihaSkladista() == castOther
						.getStanjeZalihaSkladista()) || (this
						.getStanjeZalihaSkladista() != null
						&& castOther.getStanjeZalihaSkladista() != null && this
						.getStanjeZalihaSkladista().equals(
								castOther.getStanjeZalihaSkladista())))
				&& ((this.getIzuzimanjePoZahtevima() == castOther
						.getIzuzimanjePoZahtevima()) || (this
						.getIzuzimanjePoZahtevima() != null
						&& castOther.getIzuzimanjePoZahtevima() != null && this
						.getIzuzimanjePoZahtevima().equals(
								castOther.getIzuzimanjePoZahtevima())))
				&& ((this.getTransakcijaSkladista() == castOther
						.getTransakcijaSkladista()) || (this
						.getTransakcijaSkladista() != null
						&& castOther.getTransakcijaSkladista() != null && this
						.getTransakcijaSkladista().equals(
								castOther.getTransakcijaSkladista())))
				&& ((this.getPorucenaKolicina() == castOther
						.getPorucenaKolicina()) || (this.getPorucenaKolicina() != null
						&& castOther.getPorucenaKolicina() != null && this
						.getPorucenaKolicina().equals(
								castOther.getPorucenaKolicina())))
				&& ((this.getKolicinaPromenePo() == castOther
						.getKolicinaPromenePo()) || (this
						.getKolicinaPromenePo() != null
						&& castOther.getKolicinaPromenePo() != null && this
						.getKolicinaPromenePo().equals(
								castOther.getKolicinaPromenePo())))
				&& ((this.getSprovodniList() == castOther.getSprovodniList()) || (this
						.getSprovodniList() != null
						&& castOther.getSprovodniList() != null && this
						.getSprovodniList()
						.equals(castOther.getSprovodniList())))
				&& ((this.getKolicinaPromener() == castOther
						.getKolicinaPromener()) || (this.getKolicinaPromener() != null
						&& castOther.getKolicinaPromener() != null && this
						.getKolicinaPromener().equals(
								castOther.getKolicinaPromener())))
				&& ((this.getDokumentDobavljaca() == castOther
						.getDokumentDobavljaca()) || (this
						.getDokumentDobavljaca() != null
						&& castOther.getDokumentDobavljaca() != null && this
						.getDokumentDobavljaca().equals(
								castOther.getDokumentDobavljaca())))
				&& ((this.getPoCenovniku() == castOther.getPoCenovniku()) || (this
						.getPoCenovniku() != null
						&& castOther.getPoCenovniku() != null && this
						.getPoCenovniku().equals(castOther.getPoCenovniku())))
				&& ((this.getVrstaPromeneStavke() == castOther
						.getVrstaPromeneStavke()) || (this
						.getVrstaPromeneStavke() != null
						&& castOther.getVrstaPromeneStavke() != null && this
						.getVrstaPromeneStavke().equals(
								castOther.getVrstaPromeneStavke())))
				&& ((this.getInternaEksternaPromena() == castOther
						.getInternaEksternaPromena()) || (this
						.getInternaEksternaPromena() != null
						&& castOther.getInternaEksternaPromena() != null && this
						.getInternaEksternaPromena().equals(
								castOther.getInternaEksternaPromena())))
				&& ((this.getFinansiskiDokument() == castOther
						.getFinansiskiDokument()) || (this
						.getFinansiskiDokument() != null
						&& castOther.getFinansiskiDokument() != null && this
						.getFinansiskiDokument().equals(
								castOther.getFinansiskiDokument())))
				&& ((this.getPorudzbenica() == castOther.getPorudzbenica()) || (this
						.getPorudzbenica() != null
						&& castOther.getPorudzbenica() != null && this
						.getPorudzbenica().equals(castOther.getPorudzbenica())))
				&& ((this.getRootoj() == castOther.getRootoj()) || (this
						.getRootoj() != null && castOther.getRootoj() != null && this
						.getRootoj().equals(castOther.getRootoj())))
				&& ((this.getMaxbrojstavki() == castOther.getMaxbrojstavki()) || (this
						.getMaxbrojstavki() != null
						&& castOther.getMaxbrojstavki() != null && this
						.getMaxbrojstavki()
						.equals(castOther.getMaxbrojstavki())))
				&& ((this.getDelimicnoizdavanje() == castOther
						.getDelimicnoizdavanje()) || (this
						.getDelimicnoizdavanje() != null
						&& castOther.getDelimicnoizdavanje() != null && this
						.getDelimicnoizdavanje().equals(
								castOther.getDelimicnoizdavanje())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVd();
		result = 37
				* result
				+ (getVrstaPromene() == null ? 0 : this.getVrstaPromene()
						.hashCode());
		result = 37
				* result
				+ (getZaliheJskl() == null ? 0 : this.getZaliheJskl()
						.hashCode());
		result = 37
				* result
				+ (getZaliheNaPaleti() == null ? 0 : this.getZaliheNaPaleti()
						.hashCode());
		result = 37
				* result
				+ (getStanjeZalihaSkladista() == null ? 0 : this
						.getStanjeZalihaSkladista().hashCode());
		result = 37
				* result
				+ (getIzuzimanjePoZahtevima() == null ? 0 : this
						.getIzuzimanjePoZahtevima().hashCode());
		result = 37
				* result
				+ (getTransakcijaSkladista() == null ? 0 : this
						.getTransakcijaSkladista().hashCode());
		result = 37
				* result
				+ (getPorucenaKolicina() == null ? 0 : this
						.getPorucenaKolicina().hashCode());
		result = 37
				* result
				+ (getKolicinaPromenePo() == null ? 0 : this
						.getKolicinaPromenePo().hashCode());
		result = 37
				* result
				+ (getSprovodniList() == null ? 0 : this.getSprovodniList()
						.hashCode());
		result = 37
				* result
				+ (getKolicinaPromener() == null ? 0 : this
						.getKolicinaPromener().hashCode());
		result = 37
				* result
				+ (getDokumentDobavljaca() == null ? 0 : this
						.getDokumentDobavljaca().hashCode());
		result = 37
				* result
				+ (getPoCenovniku() == null ? 0 : this.getPoCenovniku()
						.hashCode());
		result = 37
				* result
				+ (getVrstaPromeneStavke() == null ? 0 : this
						.getVrstaPromeneStavke().hashCode());
		result = 37
				* result
				+ (getInternaEksternaPromena() == null ? 0 : this
						.getInternaEksternaPromena().hashCode());
		result = 37
				* result
				+ (getFinansiskiDokument() == null ? 0 : this
						.getFinansiskiDokument().hashCode());
		result = 37
				* result
				+ (getPorudzbenica() == null ? 0 : this.getPorudzbenica()
						.hashCode());
		result = 37 * result
				+ (getRootoj() == null ? 0 : this.getRootoj().hashCode());
		result = 37
				* result
				+ (getMaxbrojstavki() == null ? 0 : this.getMaxbrojstavki()
						.hashCode());
		result = 37
				* result
				+ (getDelimicnoizdavanje() == null ? 0 : this
						.getDelimicnoizdavanje().hashCode());
		return result;
	}

}
