package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UzSklNaVd generated by hbm2java
 */
@Entity
@Table(name = "UZ_SKL_NA_VD", schema = "DAREX")
public class UzSklNaVd implements java.io.Serializable {

	private UzSklNaVdId id;

	public UzSklNaVd() {
	}

	public UzSklNaVd(UzSklNaVdId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "idSkladista", column = @Column(name = "ID_SKLADISTA", nullable = false, precision = 3, scale = 0)) })
	public UzSklNaVdId getId() {
		return this.id;
	}

	public void setId(UzSklNaVdId id) {
		this.id = id;
	}

}
