package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UzStanjeZalihaProizvoda generated by hbm2java
 */
@Entity
@Table(name = "UZ_STANJE_ZALIHA_PROIZVODA", schema = "DAREX")
public class UzStanjeZalihaProizvoda implements java.io.Serializable {

	private UzStanjeZalihaProizvodaId id;
	private BigDecimal kolicinaPoStanju;

	public UzStanjeZalihaProizvoda() {
	}

	public UzStanjeZalihaProizvoda(UzStanjeZalihaProizvodaId id,
			BigDecimal kolicinaPoStanju) {
		this.id = id;
		this.kolicinaPoStanju = kolicinaPoStanju;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proizvod", column = @Column(name = "PROIZVOD#", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "idSkladista", column = @Column(name = "ID_SKLADISTA", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "idStanjaProizvoda", column = @Column(name = "ID_STANJA_PROIZVODA", nullable = false, length = 2)) })
	public UzStanjeZalihaProizvodaId getId() {
		return this.id;
	}

	public void setId(UzStanjeZalihaProizvodaId id) {
		this.id = id;
	}

	@Column(name = "KOLICINA_PO_STANJU", nullable = false, precision = 18, scale = 3)
	public BigDecimal getKolicinaPoStanju() {
		return this.kolicinaPoStanju;
	}

	public void setKolicinaPoStanju(BigDecimal kolicinaPoStanju) {
		this.kolicinaPoStanju = kolicinaPoStanju;
	}

}
