package rs.invado.wo.domain.uz;
// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzStanjeZalihaProizvodaId generated by hbm2java
 */
@Embeddable
public class UzStanjeZalihaProizvodaId  implements java.io.Serializable {


     private int proizvod;
     private short idSkladista;
     private String idStanjaProizvoda;

    public UzStanjeZalihaProizvodaId() {
    }

    public UzStanjeZalihaProizvodaId(int proizvod, short idSkladista, String idStanjaProizvoda) {
       this.proizvod = proizvod;
       this.idSkladista = idSkladista;
       this.idStanjaProizvoda = idStanjaProizvoda;
    }
   


    @Column(name="PROIZVOD#", nullable=false, precision=7, scale=0)
    public int getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(int proizvod) {
        this.proizvod = proizvod;
    }


    @Column(name="ID_SKLADISTA", nullable=false, precision=3, scale=0)
    public short getIdSkladista() {
        return this.idSkladista;
    }
    
    public void setIdSkladista(short idSkladista) {
        this.idSkladista = idSkladista;
    }


    @Column(name="ID_STANJA_PROIZVODA", nullable=false, length=2)
    public String getIdStanjaProizvoda() {
        return this.idStanjaProizvoda;
    }
    
    public void setIdStanjaProizvoda(String idStanjaProizvoda) {
        this.idStanjaProizvoda = idStanjaProizvoda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UzStanjeZalihaProizvodaId) ) return false;
		 UzStanjeZalihaProizvodaId castOther = ( UzStanjeZalihaProizvodaId ) other; 
         
		 return (this.getProizvod()==castOther.getProizvod())
 && (this.getIdSkladista()==castOther.getIdSkladista())
 && ( (this.getIdStanjaProizvoda()==castOther.getIdStanjaProizvoda()) || ( this.getIdStanjaProizvoda()!=null && castOther.getIdStanjaProizvoda()!=null && this.getIdStanjaProizvoda().equals(castOther.getIdStanjaProizvoda()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProizvod();
         result = 37 * result + this.getIdSkladista();
         result = 37 * result + ( getIdStanjaProizvoda() == null ? 0 : this.getIdStanjaProizvoda().hashCode() );
         return result;
   }   


}


