package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UzDokumentStavkaPakovanje generated by hbm2java
 */
@Entity
@Table(name = "UZ_DOKUMENT_STAVKA_PAKOVANJE", schema = "DAREX")
public class UzDokumentStavkaPakovanje implements java.io.Serializable {

	private UzDokumentStavkaPakovanjeId id;
	private UzDokumentStavka uzDokumentStavka;

	public UzDokumentStavkaPakovanje() {
	}

	public UzDokumentStavkaPakovanje(UzDokumentStavkaPakovanjeId id,
			UzDokumentStavka uzDokumentStavka) {
		this.id = id;
		this.uzDokumentStavka = uzDokumentStavka;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "rbStavke", column = @Column(name = "RB_STAVKE", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "idDokumenta", column = @Column(name = "ID_DOKUMENTA", nullable = false, length = 30)),
			@AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "brojKomada", column = @Column(name = "BROJ_KOMADA", nullable = false, precision = 15, scale = 0)),
			@AttributeOverride(name = "kolPoPakovanju", column = @Column(name = "KOL_PO_PAKOVANJU", nullable = false, precision = 18, scale = 3)),
			@AttributeOverride(name = "uskladistenaKol", column = @Column(name = "USKLADISTENA_KOL", nullable = false, precision = 18, scale = 3)),
			@AttributeOverride(name = "idDokumentaOld", column = @Column(name = "ID_DOKUMENTA_OLD", precision = 7, scale = 0)),
			@AttributeOverride(name = "idJediniceSkladistenjaRef", column = @Column(name = "ID_JEDINICE_SKLADISTENJA_REF", precision = 6, scale = 0)),
			@AttributeOverride(name = "idpalete", column = @Column(name = "IDPALETE", length = 50)) })
	public UzDokumentStavkaPakovanjeId getId() {
		return this.id;
	}

	public void setId(UzDokumentStavkaPakovanjeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_DOKUMENTA", referencedColumnName = "ID_DOKUMENTA", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_VD", referencedColumnName = "ID_VD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "RB_STAVKE", referencedColumnName = "RB_STAVKE", nullable = false, insertable = false, updatable = false) })
	public UzDokumentStavka getUzDokumentStavka() {
		return this.uzDokumentStavka;
	}

	public void setUzDokumentStavka(UzDokumentStavka uzDokumentStavka) {
		this.uzDokumentStavka = uzDokumentStavka;
	}

}
