package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * UzOperacijeNaDokumentu generated by hbm2java
 */
@Entity
@Table(name = "UZ_OPERACIJE_NA_DOKUMENTU", schema = "DAREX")
public class UzOperacijeNaDokumentu implements java.io.Serializable {

	private UzOperacijeNaDokumentuId id;

	public UzOperacijeNaDokumentu() {
	}

	public UzOperacijeNaDokumentu(UzOperacijeNaDokumentuId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "vrstaPromene", column = @Column(name = "VRSTA_PROMENE", nullable = false, length = 1)),
			@AttributeOverride(name = "zaliheJskl", column = @Column(name = "ZALIHE_JSKL", precision = 3, scale = 0)),
			@AttributeOverride(name = "zaliheNaPaleti", column = @Column(name = "ZALIHE_NA_PALETI", precision = 3, scale = 0)),
			@AttributeOverride(name = "stanjeZalihaSkladista", column = @Column(name = "STANJE_ZALIHA_SKLADISTA", precision = 3, scale = 0)),
			@AttributeOverride(name = "izuzimanjePoZahtevima", column = @Column(name = "IZUZIMANJE_PO_ZAHTEVIMA", precision = 3, scale = 0)),
			@AttributeOverride(name = "transakcijaSkladista", column = @Column(name = "TRANSAKCIJA_SKLADISTA", precision = 3, scale = 0)),
			@AttributeOverride(name = "porucenaKolicina", column = @Column(name = "PORUCENA_KOLICINA", precision = 3, scale = 0)),
			@AttributeOverride(name = "kolicinaPromenePo", column = @Column(name = "KOLICINA_PROMENE_PO", precision = 3, scale = 0)),
			@AttributeOverride(name = "sprovodniList", column = @Column(name = "SPROVODNI_LIST", precision = 3, scale = 0)),
			@AttributeOverride(name = "kolicinaPromener", column = @Column(name = "KOLICINA_PROMENER", precision = 3, scale = 0)),
			@AttributeOverride(name = "dokumentDobavljaca", column = @Column(name = "DOKUMENT_DOBAVLJACA", precision = 3, scale = 0)),
			@AttributeOverride(name = "poCenovniku", column = @Column(name = "PO_CENOVNIKU", precision = 3, scale = 0)),
			@AttributeOverride(name = "vrstaPromeneStavke", column = @Column(name = "VRSTA_PROMENE_STAVKE", precision = 3, scale = 0)),
			@AttributeOverride(name = "internaEksternaPromena", column = @Column(name = "INTERNA_EKSTERNA_PROMENA", precision = 3, scale = 0)),
			@AttributeOverride(name = "finansiskiDokument", column = @Column(name = "FINANSISKI_DOKUMENT", precision = 3, scale = 0)),
			@AttributeOverride(name = "porudzbenica", column = @Column(name = "PORUDZBENICA", precision = 3, scale = 0)),
			@AttributeOverride(name = "rootoj", column = @Column(name = "ROOTOJ", precision = 22, scale = 0)),
			@AttributeOverride(name = "maxbrojstavki", column = @Column(name = "MAXBROJSTAVKI", precision = 22, scale = 0)),
			@AttributeOverride(name = "delimicnoizdavanje", column = @Column(name = "DELIMICNOIZDAVANJE", length = 2)) })
	public UzOperacijeNaDokumentuId getId() {
		return this.id;
	}

	public void setId(UzOperacijeNaDokumentuId id) {
		this.id = id;
	}

}
