package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.Formula;
import rs.invado.wo.domain.ocp.OcpProizvod;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UzStanjeZalihaSkladista generated by hbm2java
 */
@Entity
@Table(name = "UZ_STANJE_ZALIHA_SKLADISTA", schema = "DAREX")
public class UzStanjeZalihaSkladista implements java.io.Serializable {

	private UzStanjeZalihaSkladistaId id;
	private UzSkladiste uzSkladiste;
	private Date datumPoslednjegPrijema;
	private BigDecimal rezervisanaKol;
	private BigDecimal ukupnoPrimljenaKol;
	private BigDecimal ukupnoIzdataKol;
	private BigDecimal pocStProizvodaUSkl;
	private BigDecimal kolicinaPoStanjuZ;
	private Date datumZadnjegIzdavanja;
	private Date datumZadnjegPopisa;
	private BigDecimal minNivoZaliha;
	private BigDecimal maxNivoZaliha;
	private BigDecimal optimalniNivoZaliha;
    private OcpProizvod ocpProizvod;

    //Formula
    private BigDecimal raspolozivoStanje;

	public UzStanjeZalihaSkladista() {
	}

	public UzStanjeZalihaSkladista(UzStanjeZalihaSkladistaId id,
			UzSkladiste uzSkladiste, BigDecimal rezervisanaKol,
			BigDecimal ukupnoPrimljenaKol, BigDecimal ukupnoIzdataKol,
			BigDecimal pocStProizvodaUSkl, BigDecimal kolicinaPoStanjuZ) {
		this.id = id;
		this.uzSkladiste = uzSkladiste;
		this.rezervisanaKol = rezervisanaKol;
		this.ukupnoPrimljenaKol = ukupnoPrimljenaKol;
		this.ukupnoIzdataKol = ukupnoIzdataKol;
		this.pocStProizvodaUSkl = pocStProizvodaUSkl;
		this.kolicinaPoStanjuZ = kolicinaPoStanjuZ;
	}

	public UzStanjeZalihaSkladista(UzStanjeZalihaSkladistaId id,
			UzSkladiste uzSkladiste, Date datumPoslednjegPrijema,
			BigDecimal rezervisanaKol, BigDecimal ukupnoPrimljenaKol,
			BigDecimal ukupnoIzdataKol, BigDecimal pocStProizvodaUSkl,
			BigDecimal kolicinaPoStanjuZ, Date datumZadnjegIzdavanja,
			Date datumZadnjegPopisa, BigDecimal minNivoZaliha,
			BigDecimal maxNivoZaliha, BigDecimal optimalniNivoZaliha) {
		this.id = id;
		this.uzSkladiste = uzSkladiste;
		this.datumPoslednjegPrijema = datumPoslednjegPrijema;
		this.rezervisanaKol = rezervisanaKol;
		this.ukupnoPrimljenaKol = ukupnoPrimljenaKol;
		this.ukupnoIzdataKol = ukupnoIzdataKol;
		this.pocStProizvodaUSkl = pocStProizvodaUSkl;
		this.kolicinaPoStanjuZ = kolicinaPoStanjuZ;
		this.datumZadnjegIzdavanja = datumZadnjegIzdavanja;
		this.datumZadnjegPopisa = datumZadnjegPopisa;
		this.minNivoZaliha = minNivoZaliha;
		this.maxNivoZaliha = maxNivoZaliha;
		this.optimalniNivoZaliha = optimalniNivoZaliha;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proizvod", column = @Column(name = "PROIZVOD#", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "idSkladista", column = @Column(name = "ID_SKLADISTA", nullable = false, precision = 3, scale = 0)) })
	public UzStanjeZalihaSkladistaId getId() {
		return this.id;
	}

	public void setId(UzStanjeZalihaSkladistaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_SKLADISTA", nullable = false, insertable = false, updatable = false)
	public UzSkladiste getUzSkladiste() {
		return this.uzSkladiste;
	}

	    public void setUzSkladiste(UzSkladiste uzSkladiste) {
		this.uzSkladiste = uzSkladiste;
	}

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROIZVOD#", nullable = false, insertable = false, updatable = false)
    public OcpProizvod getOcpProizvod() {
        return ocpProizvod;
    }

    public void setOcpProizvod(OcpProizvod ocpProizvod) {
        this.ocpProizvod = ocpProizvod;
    }

    @Temporal(TemporalType.DATE)
	@Column(name = "DATUM_POSLEDNJEG_PRIJEMA", length = 7)
	public Date getDatumPoslednjegPrijema() {
		return this.datumPoslednjegPrijema;
	}

	public void setDatumPoslednjegPrijema(Date datumPoslednjegPrijema) {
		this.datumPoslednjegPrijema = datumPoslednjegPrijema;
	}

	@Column(name = "REZERVISANA_KOL", nullable = false, precision = 18, scale = 3)
	public BigDecimal getRezervisanaKol() {
		return this.rezervisanaKol;
	}

	public void setRezervisanaKol(BigDecimal rezervisanaKol) {
		this.rezervisanaKol = rezervisanaKol;
	}

	@Column(name = "UKUPNO_PRIMLJENA_KOL", nullable = false, precision = 18, scale = 3)
	public BigDecimal getUkupnoPrimljenaKol() {
		return this.ukupnoPrimljenaKol;
	}

	public void setUkupnoPrimljenaKol(BigDecimal ukupnoPrimljenaKol) {
		this.ukupnoPrimljenaKol = ukupnoPrimljenaKol;
	}

	@Column(name = "UKUPNO_IZDATA_KOL", nullable = false, precision = 18, scale = 3)
	public BigDecimal getUkupnoIzdataKol() {
		return this.ukupnoIzdataKol;
	}

	public void setUkupnoIzdataKol(BigDecimal ukupnoIzdataKol) {
		this.ukupnoIzdataKol = ukupnoIzdataKol;
	}

	@Column(name = "POC_ST_PROIZVODA_U_SKL", nullable = false, precision = 18, scale = 3)
	public BigDecimal getPocStProizvodaUSkl() {
		return this.pocStProizvodaUSkl;
	}

	public void setPocStProizvodaUSkl(BigDecimal pocStProizvodaUSkl) {
		this.pocStProizvodaUSkl = pocStProizvodaUSkl;
	}

	@Column(name = "KOLICINA_PO_STANJU_Z", nullable = false, precision = 18, scale = 3)
	public BigDecimal getKolicinaPoStanjuZ() {
		return this.kolicinaPoStanjuZ;
	}

	public void setKolicinaPoStanjuZ(BigDecimal kolicinaPoStanjuZ) {
		this.kolicinaPoStanjuZ = kolicinaPoStanjuZ;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATUM_ZADNJEG_IZDAVANJA", length = 7)
	public Date getDatumZadnjegIzdavanja() {
		return this.datumZadnjegIzdavanja;
	}

	public void setDatumZadnjegIzdavanja(Date datumZadnjegIzdavanja) {
		this.datumZadnjegIzdavanja = datumZadnjegIzdavanja;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATUM_ZADNJEG_POPISA", length = 7)
	public Date getDatumZadnjegPopisa() {
		return this.datumZadnjegPopisa;
	}

	public void setDatumZadnjegPopisa(Date datumZadnjegPopisa) {
		this.datumZadnjegPopisa = datumZadnjegPopisa;
	}

	@Column(name = "MIN_NIVO_ZALIHA", precision = 18, scale = 3)
	public BigDecimal getMinNivoZaliha() {
		return this.minNivoZaliha;
	}

	public void setMinNivoZaliha(BigDecimal minNivoZaliha) {
		this.minNivoZaliha = minNivoZaliha;
	}

	@Column(name = "MAX_NIVO_ZALIHA", precision = 18, scale = 3)
	public BigDecimal getMaxNivoZaliha() {
		return this.maxNivoZaliha;
	}

	public void setMaxNivoZaliha(BigDecimal maxNivoZaliha) {
		this.maxNivoZaliha = maxNivoZaliha;
	}

	@Column(name = "OPTIMALNI_NIVO_ZALIHA", precision = 18, scale = 3)
	public BigDecimal getOptimalniNivoZaliha() {
		return this.optimalniNivoZaliha;
	}

	public void setOptimalniNivoZaliha(BigDecimal optimalniNivoZaliha) {
		this.optimalniNivoZaliha = optimalniNivoZaliha;
	}

    @Formula(("KOLICINA_PO_STANJU_Z-REZERVISANA_KOL"))
    public BigDecimal getRaspolozivoStanje() {
        return raspolozivoStanje;
    }

    public void setRaspolozivoStanje(BigDecimal raspolozivoStanje) {
        this.raspolozivoStanje = raspolozivoStanje;
    }
}
