package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.*;

/**
 * UzDokumentOj generated by hbm2java
 */
@Entity
@Table(name = "UZ_DOKUMENT_OJ", schema = "DAREX")
@NamedNativeQuery(name = "spkSklDokumentSlozen", query = "{ ? =  call woutil.SPK_SklDokument_Slozen_hib (:p_IdVd, :p_oj, :p_godina, :p_idskladista)}",
        resultClass = UzDokumentOj.class, hints = { @javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true") })
public class UzDokumentOj implements java.io.Serializable {

	private UzDokumentOjId id;
	private int poslBrDokNab;

	public UzDokumentOj() {
	}

	public UzDokumentOj(UzDokumentOjId id, int poslBrDokNab) {
		this.id = id;
		this.poslBrDokNab = poslBrDokNab;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "organizacionaJedinica", column = @Column(name = "ORGANIZACIONA_JEDINICA#", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "godina", column = @Column(name = "GODINA", nullable = false, precision = 4, scale = 0)) })
	public UzDokumentOjId getId() {
		return this.id;
	}

	public void setId(UzDokumentOjId id) {
		this.id = id;
	}

	@Column(name = "POSL_BR_DOK_NAB", nullable = false, precision = 5, scale = 0)
	public int getPoslBrDokNab() {
		return this.poslBrDokNab;
	}

	public void setPoslBrDokNab(int poslBrDokNab) {
		this.poslBrDokNab = poslBrDokNab;
	}

}
