package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzZaliheJsklId generated by hbm2java
 */
@Embeddable
public class UzZaliheJsklId implements java.io.Serializable {

	private int idJediniceSkladistenja;
	private int redniBrojJskl;

	public UzZaliheJsklId() {
	}

	public UzZaliheJsklId(int idJediniceSkladistenja, int redniBrojJskl) {
		this.idJediniceSkladistenja = idJediniceSkladistenja;
		this.redniBrojJskl = redniBrojJskl;
	}

	@Column(name = "ID_JEDINICE_SKLADISTENJA", nullable = false, precision = 6, scale = 0)
	public int getIdJediniceSkladistenja() {
		return this.idJediniceSkladistenja;
	}

	public void setIdJediniceSkladistenja(int idJediniceSkladistenja) {
		this.idJediniceSkladistenja = idJediniceSkladistenja;
	}

	@Column(name = "REDNI_BROJ_JSKL", nullable = false, precision = 6, scale = 0)
	public int getRedniBrojJskl() {
		return this.redniBrojJskl;
	}

	public void setRedniBrojJskl(int redniBrojJskl) {
		this.redniBrojJskl = redniBrojJskl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzZaliheJsklId))
			return false;
		UzZaliheJsklId castOther = (UzZaliheJsklId) other;

		return (this.getIdJediniceSkladistenja() == castOther
				.getIdJediniceSkladistenja())
				&& (this.getRedniBrojJskl() == castOther.getRedniBrojJskl());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdJediniceSkladistenja();
		result = 37 * result + this.getRedniBrojJskl();
		return result;
	}

}
