package rs.invado.wo.domain.hr;
// Generated Jan 15, 2013 10:02:28 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * KeRadnici generated by hbm2java
 */
@Entity
@Table(name="KE_RADNICI"
    ,schema="DAREX"
    , uniqueConstraints = {@UniqueConstraint(columnNames="LBO"), @UniqueConstraint(columnNames="EXTERNAL_USERNAME"), @UniqueConstraint(columnNames={"PREZIME", "SR_SLOVO", "IME", "RADBR"})} 
)
public class KeRadnici  implements java.io.Serializable {


     private String radbr;
     private KeRadnici keRadnici;
     private Integer pretStazBen;
     private Byte stazYyBen;
     private Byte stazMmBen;
     private Byte stazDdBen;
     private Integer pretStazFir;
     private Byte stazYyFir;
     private Byte stazMmFir;
     private Byte stazDdFir;
     private String bracnoStanje;
     private String prezime;
     private String ime;
     private String srSlovo;
     private String roditelj;
     private String devPrez;
     private Date datrodj;
     private String opsrbr;
     private String adresa;
     private String telefon;
     private String opsbr;
     private String mzbr;
     private String pol;
     private String licniBr;
     private String spremabr;
     private String radnaKnj;
     private Integer pretStaz;
     private Byte stazYy;
     private Byte stazMm;
     private Byte stazDd;
     private Date datum;
     private String brojlk;
     private String verabr;
     private String nacbr;
     private String statusbr;
     private String slavabr;
     private String stevbr;
     private Date datumDol;
     private Date datumOdl;
     private String zastareo;
     private String organizacionaJedinica;
     private String radnaObaveza;
     private Date datumRadneObavezeOd;
     private String slika;
     private String opsbrRada;
     private String username;
     private BigDecimal nadzor;
     private String obrJedinica;
     private String sortniPojam;
     private String samohran;
     private String titula;
     private String geoSeg;
     private String racunovodstvo;
     private String lbo;
     private String externalUsername;
     private String mail;
     private String jeStranac;

    public KeRadnici() {
    }

	
    public KeRadnici(String radbr, String prezime, String ime, Date datrodj, String opsbr, String mzbr, String pol, String licniBr, String spremabr, Date datum, String statusbr, String opsbrRada) {
        this.radbr = radbr;
        this.prezime = prezime;
        this.ime = ime;
        this.datrodj = datrodj;
        this.opsbr = opsbr;
        this.mzbr = mzbr;
        this.pol = pol;
        this.licniBr = licniBr;
        this.spremabr = spremabr;
        this.datum = datum;
        this.statusbr = statusbr;
        this.opsbrRada = opsbrRada;
    }
    public KeRadnici(String radbr, KeRadnici keRadnici, Integer pretStazBen, Byte stazYyBen, Byte stazMmBen, Byte stazDdBen, Integer pretStazFir, Byte stazYyFir, Byte stazMmFir, Byte stazDdFir, String bracnoStanje, String prezime, String ime, String srSlovo, String roditelj, String devPrez, Date datrodj, String opsrbr, String adresa, String telefon, String opsbr, String mzbr, String pol, String licniBr, String spremabr, String radnaKnj, Integer pretStaz, Byte stazYy, Byte stazMm, Byte stazDd, Date datum, String brojlk, String verabr, String nacbr, String statusbr, String slavabr, String stevbr, Date datumDol, Date datumOdl, String zastareo, String organizacionaJedinica, String radnaObaveza, Date datumRadneObavezeOd, String slika, String opsbrRada, String username, BigDecimal nadzor, String obrJedinica, String sortniPojam, String samohran, String titula, String geoSeg, String racunovodstvo, String lbo, String externalUsername, String mail, String jeStranac, Set keRadnicis) {
       this.radbr = radbr;
       this.keRadnici = keRadnici;
       this.pretStazBen = pretStazBen;
       this.stazYyBen = stazYyBen;
       this.stazMmBen = stazMmBen;
       this.stazDdBen = stazDdBen;
       this.pretStazFir = pretStazFir;
       this.stazYyFir = stazYyFir;
       this.stazMmFir = stazMmFir;
       this.stazDdFir = stazDdFir;
       this.bracnoStanje = bracnoStanje;
       this.prezime = prezime;
       this.ime = ime;
       this.srSlovo = srSlovo;
       this.roditelj = roditelj;
       this.devPrez = devPrez;
       this.datrodj = datrodj;
       this.opsrbr = opsrbr;
       this.adresa = adresa;
       this.telefon = telefon;
       this.opsbr = opsbr;
       this.mzbr = mzbr;
       this.pol = pol;
       this.licniBr = licniBr;
       this.spremabr = spremabr;
       this.radnaKnj = radnaKnj;
       this.pretStaz = pretStaz;
       this.stazYy = stazYy;
       this.stazMm = stazMm;
       this.stazDd = stazDd;
       this.datum = datum;
       this.brojlk = brojlk;
       this.verabr = verabr;
       this.nacbr = nacbr;
       this.statusbr = statusbr;
       this.slavabr = slavabr;
       this.stevbr = stevbr;
       this.datumDol = datumDol;
       this.datumOdl = datumOdl;
       this.zastareo = zastareo;
       this.organizacionaJedinica= organizacionaJedinica;
       this.radnaObaveza = radnaObaveza;
       this.datumRadneObavezeOd = datumRadneObavezeOd;
       this.slika = slika;
       this.opsbrRada = opsbrRada;
       this.username = username;
       this.nadzor = nadzor;
       this.obrJedinica = obrJedinica;
       this.sortniPojam = sortniPojam;
       this.samohran = samohran;
       this.titula = titula;
       this.geoSeg = geoSeg;
       this.racunovodstvo = racunovodstvo;
       this.lbo = lbo;
       this.externalUsername = externalUsername;
       this.mail = mail;
       this.jeStranac = jeStranac;
    }
   
     @Id 

    
    @Column(name="RADBR", unique=true, nullable=false, length=6)
    public String getRadbr() {
        return this.radbr;
    }
    
    public void setRadbr(String radbr) {
        this.radbr = radbr;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="RADBRREF")
    public KeRadnici getKeRadnici() {
        return this.keRadnici;
    }
    
    public void setKeRadnici(KeRadnici keRadnici) {
        this.keRadnici = keRadnici;
    }

    
    @Column(name="PRET_STAZ_BEN", precision=5, scale=0)
    public Integer getPretStazBen() {
        return this.pretStazBen;
    }
    
    public void setPretStazBen(Integer pretStazBen) {
        this.pretStazBen = pretStazBen;
    }

    
    @Column(name="STAZ_YY_BEN", precision=2, scale=0)
    public Byte getStazYyBen() {
        return this.stazYyBen;
    }
    
    public void setStazYyBen(Byte stazYyBen) {
        this.stazYyBen = stazYyBen;
    }

    
    @Column(name="STAZ_MM_BEN", precision=2, scale=0)
    public Byte getStazMmBen() {
        return this.stazMmBen;
    }
    
    public void setStazMmBen(Byte stazMmBen) {
        this.stazMmBen = stazMmBen;
    }

    
    @Column(name="STAZ_DD_BEN", precision=2, scale=0)
    public Byte getStazDdBen() {
        return this.stazDdBen;
    }
    
    public void setStazDdBen(Byte stazDdBen) {
        this.stazDdBen = stazDdBen;
    }

    
    @Column(name="PRET_STAZ_FIR", precision=5, scale=0)
    public Integer getPretStazFir() {
        return this.pretStazFir;
    }
    
    public void setPretStazFir(Integer pretStazFir) {
        this.pretStazFir = pretStazFir;
    }

    
    @Column(name="STAZ_YY_FIR", precision=2, scale=0)
    public Byte getStazYyFir() {
        return this.stazYyFir;
    }
    
    public void setStazYyFir(Byte stazYyFir) {
        this.stazYyFir = stazYyFir;
    }

    
    @Column(name="STAZ_MM_FIR", precision=2, scale=0)
    public Byte getStazMmFir() {
        return this.stazMmFir;
    }
    
    public void setStazMmFir(Byte stazMmFir) {
        this.stazMmFir = stazMmFir;
    }

    
    @Column(name="STAZ_DD_FIR", precision=2, scale=0)
    public Byte getStazDdFir() {
        return this.stazDdFir;
    }
    
    public void setStazDdFir(Byte stazDdFir) {
        this.stazDdFir = stazDdFir;
    }

    
    @Column(name="BRACNO_STANJE", length=1)
    public String getBracnoStanje() {
        return this.bracnoStanje;
    }
    
    public void setBracnoStanje(String bracnoStanje) {
        this.bracnoStanje = bracnoStanje;
    }

    
    @Column(name="PREZIME", nullable=false, length=100)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="IME", nullable=false, length=100)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="SR_SLOVO", length=2)
    public String getSrSlovo() {
        return this.srSlovo;
    }
    
    public void setSrSlovo(String srSlovo) {
        this.srSlovo = srSlovo;
    }

    
    @Column(name="RODITELJ", length=20)
    public String getRoditelj() {
        return this.roditelj;
    }
    
    public void setRoditelj(String roditelj) {
        this.roditelj = roditelj;
    }

    
    @Column(name="DEV_PREZ", length=20)
    public String getDevPrez() {
        return this.devPrez;
    }
    
    public void setDevPrez(String devPrez) {
        this.devPrez = devPrez;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATRODJ", nullable=false, length=7)
    public Date getDatrodj() {
        return this.datrodj;
    }
    
    public void setDatrodj(Date datrodj) {
        this.datrodj = datrodj;
    }

    
    @Column(name="OPSRBR", length=5)
    public String getOpsrbr() {
        return this.opsrbr;
    }
    
    public void setOpsrbr(String opsrbr) {
        this.opsrbr = opsrbr;
    }

    
    @Column(name="ADRESA", length=60)
    public String getAdresa() {
        return this.adresa;
    }
    
    public void setAdresa(String adresa) {
        this.adresa = adresa;
    }

    
    @Column(name="TELEFON", length=15)
    public String getTelefon() {
        return this.telefon;
    }
    
    public void setTelefon(String telefon) {
        this.telefon = telefon;
    }

    
    @Column(name="OPSBR", nullable=false, length=5)
    public String getOpsbr() {
        return this.opsbr;
    }
    
    public void setOpsbr(String opsbr) {
        this.opsbr = opsbr;
    }

    
    @Column(name="MZBR", nullable=false, length=4)
    public String getMzbr() {
        return this.mzbr;
    }
    
    public void setMzbr(String mzbr) {
        this.mzbr = mzbr;
    }

    
    @Column(name="POL", nullable=false, length=1)
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }

    
    @Column(name="LICNI_BR", nullable=false, length=13)
    public String getLicniBr() {
        return this.licniBr;
    }
    
    public void setLicniBr(String licniBr) {
        this.licniBr = licniBr;
    }

    
    @Column(name="SPREMABR", nullable=false, length=3)
    public String getSpremabr() {
        return this.spremabr;
    }
    
    public void setSpremabr(String spremabr) {
        this.spremabr = spremabr;
    }

    
    @Column(name="RADNA_KNJ", length=20)
    public String getRadnaKnj() {
        return this.radnaKnj;
    }
    
    public void setRadnaKnj(String radnaKnj) {
        this.radnaKnj = radnaKnj;
    }

    
    @Column(name="PRET_STAZ", precision=5, scale=0)
    public Integer getPretStaz() {
        return this.pretStaz;
    }
    
    public void setPretStaz(Integer pretStaz) {
        this.pretStaz = pretStaz;
    }

    
    @Column(name="STAZ_YY", precision=2, scale=0)
    public Byte getStazYy() {
        return this.stazYy;
    }
    
    public void setStazYy(Byte stazYy) {
        this.stazYy = stazYy;
    }

    
    @Column(name="STAZ_MM", precision=2, scale=0)
    public Byte getStazMm() {
        return this.stazMm;
    }
    
    public void setStazMm(Byte stazMm) {
        this.stazMm = stazMm;
    }

    
    @Column(name="STAZ_DD", precision=2, scale=0)
    public Byte getStazDd() {
        return this.stazDd;
    }
    
    public void setStazDd(Byte stazDd) {
        this.stazDd = stazDd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", nullable=false, length=7)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="BROJLK", length=8)
    public String getBrojlk() {
        return this.brojlk;
    }
    
    public void setBrojlk(String brojlk) {
        this.brojlk = brojlk;
    }

    
    @Column(name="VERABR", length=3)
    public String getVerabr() {
        return this.verabr;
    }
    
    public void setVerabr(String verabr) {
        this.verabr = verabr;
    }

    
    @Column(name="NACBR", length=3)
    public String getNacbr() {
        return this.nacbr;
    }
    
    public void setNacbr(String nacbr) {
        this.nacbr = nacbr;
    }

    
    @Column(name="STATUSBR", nullable=false, length=1)
    public String getStatusbr() {
        return this.statusbr;
    }
    
    public void setStatusbr(String statusbr) {
        this.statusbr = statusbr;
    }

    
    @Column(name="SLAVABR", length=3)
    public String getSlavabr() {
        return this.slavabr;
    }
    
    public void setSlavabr(String slavabr) {
        this.slavabr = slavabr;
    }

    
    @Column(name="STEVBR", length=5)
    public String getStevbr() {
        return this.stevbr;
    }
    
    public void setStevbr(String stevbr) {
        this.stevbr = stevbr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_DOL", length=7)
    public Date getDatumDol() {
        return this.datumDol;
    }
    
    public void setDatumDol(Date datumDol) {
        this.datumDol = datumDol;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_ODL", length=7)
    public Date getDatumOdl() {
        return this.datumOdl;
    }
    
    public void setDatumOdl(Date datumOdl) {
        this.datumOdl = datumOdl;
    }

    
    @Column(name="ZASTAREO", length=1)
    public String getZastareo() {
        return this.zastareo;
    }
    
    public void setZastareo(String zastareo) {
        this.zastareo = zastareo;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#", length=12)
    public String getOrganizacionaJedinica() {
        return this.organizacionaJedinica;
    }
    
    public void setOrganizacionaJedinica(String organizacionaJedinica) {
        this.organizacionaJedinica = organizacionaJedinica;
    }

    
    @Column(name="RADNA_OBAVEZA", length=1)
    public String getRadnaObaveza() {
        return this.radnaObaveza;
    }
    
    public void setRadnaObaveza(String radnaObaveza) {
        this.radnaObaveza = radnaObaveza;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_RADNE_OBAVEZE_OD", length=7)
    public Date getDatumRadneObavezeOd() {
        return this.datumRadneObavezeOd;
    }
    
    public void setDatumRadneObavezeOd(Date datumRadneObavezeOd) {
        this.datumRadneObavezeOd = datumRadneObavezeOd;
    }

    
    @Column(name="SLIKA#", length=3)
    public String getSlika() {
        return this.slika;
    }
    
    public void setSlika(String slika) {
        this.slika = slika;
    }

    
    @Column(name="OPSBR_RADA", nullable=false, length=5)
    public String getOpsbrRada() {
        return this.opsbrRada;
    }
    
    public void setOpsbrRada(String opsbrRada) {
        this.opsbrRada = opsbrRada;
    }

    
    @Column(name="USERNAME", length=30)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="NADZOR", precision=7, scale=3)
    public BigDecimal getNadzor() {
        return this.nadzor;
    }
    
    public void setNadzor(BigDecimal nadzor) {
        this.nadzor = nadzor;
    }

    
    @Column(name="OBR_JEDINICA#", length=12)
    public String getObrJedinica() {
        return this.obrJedinica;
    }
    
    public void setObrJedinica(String obrJedinica) {
        this.obrJedinica = obrJedinica;
    }

    
    @Column(name="SORTNI_POJAM", length=90)
    public String getSortniPojam() {
        return this.sortniPojam;
    }
    
    public void setSortniPojam(String sortniPojam) {
        this.sortniPojam = sortniPojam;
    }

    
    @Column(name="SAMOHRAN", length=1)
    public String getSamohran() {
        return this.samohran;
    }
    
    public void setSamohran(String samohran) {
        this.samohran = samohran;
    }

    
    @Column(name="TITULA", length=10)
    public String getTitula() {
        return this.titula;
    }
    
    public void setTitula(String titula) {
        this.titula = titula;
    }

    
    @Column(name="GEO_SEG", length=2)
    public String getGeoSeg() {
        return this.geoSeg;
    }
    
    public void setGeoSeg(String geoSeg) {
        this.geoSeg = geoSeg;
    }

    
    @Column(name="RACUNOVODSTVO", length=2)
    public String getRacunovodstvo() {
        return this.racunovodstvo;
    }
    
    public void setRacunovodstvo(String racunovodstvo) {
        this.racunovodstvo = racunovodstvo;
    }

    
    @Column(name="LBO", unique=true, length=11)
    public String getLbo() {
        return this.lbo;
    }
    
    public void setLbo(String lbo) {
        this.lbo = lbo;
    }

    
    @Column(name="EXTERNAL_USERNAME", unique=true)
    public String getExternalUsername() {
        return this.externalUsername;
    }
    
    public void setExternalUsername(String externalUsername) {
        this.externalUsername = externalUsername;
    }

    
    @Column(name="MAIL")
    public String getMail() {
        return this.mail;
    }
    
    public void setMail(String mail) {
        this.mail = mail;
    }

    
    @Column(name="JE_STRANAC", length=1)
    public String getJeStranac() {
        return this.jeStranac;
    }
    
    public void setJeStranac(String jeStranac) {
        this.jeStranac = jeStranac;
    }


}


