package rs.invado.wo.domain.uz;
// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * UzDokumentStavka generated by hbm2java
 */
@Entity
@Table(name="UZ_DOKUMENT_STAVKA"
    ,schema="DAREX"
)
@NamedNativeQuery(name = "inserStavkaSklDokumenta", query = "{call avr_util.I_StavkaSklDokumenta (:p_id_vd,:p_id_dokumenta, :p_status_stavke, " +
        " :p_id_jedinice_mere, :p_proizvod, :p_nivo_kvaliteta, :p_vrsta_promene, :p_id_kontrolnog_broja, :p_id_lota_pp, :p_ispor_kol, " +
        ":p_naved_kol, :p_jedinicna_cena, :p_vrednost, :p_id_porudzbenice, :p_rb_stavke_porudzbenice,:p_kolicina_promener,:p_id_vd_po, " +
        ":p_id_dokumenta_po, :p_rb_stavke_po, :p_kolicina_promene_po,:p_poslovni_partner#,:p_jedinicna_tezina, :p_rb_sarze, :p_serijskibroj," +
        " :p_vrstaproizvoda :p_godina, :p_rabat, :p_kol01  )}",
        resultClass = UzDokumentStavka.class, hints = { @javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true") })

public class UzDokumentStavka  implements java.io.Serializable {


     private UzDokumentStavkaId id;
     private UzDokument uzDokument;
     private String statusStavke;
     private int idJediniceMere;
     private int proizvod;
     private String nivoKvaliteta;
     private int vrstaPromene;
     private Integer idKontrolnogBroja;
     private String idLotaPp;
     private BigDecimal isporKol;
     private BigDecimal navedKol;
     private BigDecimal jedinicnaCena;
     private BigDecimal vrednost;
     private Integer idPorudzbenice;
     private Short rbStavkePorudzbenice;
     private BigDecimal kolicinaPromener;
     private Short idVdPo;
     private String idDokumentaPo;
     private Short rbStavkePo;
     private BigDecimal kolicinaPromenePo;
     private Integer poslovniPartner;
     private BigDecimal jedinicnaTezina;
     private Short rbSarze;
     private String serijskiBroj;
     private int vrstaProizvoda;
     private int godina;
     private BigDecimal knjVrednost;
     private Integer idDokumentaOld;
     private BigDecimal rabat;
     private BigDecimal kol1;
     private BigDecimal kol2;
     private BigDecimal kol3;
     private BigDecimal kol4;
     private BigDecimal kol5;
     private String kol6;
     private String kol7;
     private String kol8;
     private String kol9;
     private String kol10;
     private String col02;
     private Set uzDokumentStavkaPakovanjes = new HashSet(0);

    public UzDokumentStavka() {
    }

	
    public UzDokumentStavka(UzDokumentStavkaId id, UzDokument uzDokument, String statusStavke, int idJediniceMere, int proizvod, String nivoKvaliteta, int vrstaPromene) {
        this.id = id;
        this.uzDokument = uzDokument;
        this.statusStavke = statusStavke;
        this.idJediniceMere = idJediniceMere;
        this.proizvod = proizvod;
        this.nivoKvaliteta = nivoKvaliteta;
        this.vrstaPromene = vrstaPromene;
    }
    public UzDokumentStavka(UzDokumentStavkaId id, UzDokument uzDokument, String statusStavke, int idJediniceMere, int proizvod, String nivoKvaliteta, int vrstaPromene, Integer idKontrolnogBroja, String idLotaPp, BigDecimal isporKol, BigDecimal navedKol, BigDecimal jedinicnaCena, BigDecimal vrednost, Integer idPorudzbenice, Short rbStavkePorudzbenice, BigDecimal kolicinaPromener, Short idVdPo, String idDokumentaPo, Short rbStavkePo, BigDecimal kolicinaPromenePo, Integer poslovniPartner, BigDecimal jedinicnaTezina, Short rbSarze, String serijskiBroj, int vrstaProizvoda, int godina, BigDecimal knjVrednost, Integer idDokumentaOld, BigDecimal rabat, BigDecimal kol1, BigDecimal kol2, BigDecimal kol3, BigDecimal kol4, BigDecimal kol5, String kol6, String kol7, String kol8, String kol9, String kol10, String col02, Set uzDokumentStavkaPakovanjes) {
       this.id = id;
       this.uzDokument = uzDokument;
       this.statusStavke = statusStavke;
       this.idJediniceMere = idJediniceMere;
       this.proizvod = proizvod;
       this.nivoKvaliteta = nivoKvaliteta;
       this.vrstaPromene = vrstaPromene;
       this.idKontrolnogBroja = idKontrolnogBroja;
       this.idLotaPp = idLotaPp;
       this.isporKol = isporKol;
       this.navedKol = navedKol;
       this.jedinicnaCena = jedinicnaCena;
       this.vrednost = vrednost;
       this.idPorudzbenice = idPorudzbenice;
       this.rbStavkePorudzbenice = rbStavkePorudzbenice;
       this.kolicinaPromener = kolicinaPromener;
       this.idVdPo = idVdPo;
       this.idDokumentaPo = idDokumentaPo;
       this.rbStavkePo = rbStavkePo;
       this.kolicinaPromenePo = kolicinaPromenePo;
       this.poslovniPartner = poslovniPartner;
       this.jedinicnaTezina = jedinicnaTezina;
       this.rbSarze = rbSarze;
       this.serijskiBroj = serijskiBroj;
       this.vrstaProizvoda = vrstaProizvoda;
       this.godina = godina;
       this.knjVrednost = knjVrednost;
       this.idDokumentaOld = idDokumentaOld;
       this.rabat = rabat;
       this.kol1 = kol1;
       this.kol2 = kol2;
       this.kol3 = kol3;
       this.kol4 = kol4;
       this.kol5 = kol5;
       this.kol6 = kol6;
       this.kol7 = kol7;
       this.kol8 = kol8;
       this.kol9 = kol9;
       this.kol10 = kol10;
       this.col02 = col02;
       this.uzDokumentStavkaPakovanjes = uzDokumentStavkaPakovanjes;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idDokumenta", column=@Column(name="ID_DOKUMENTA", nullable=false, length=30) ), 
        @AttributeOverride(name="idVd", column=@Column(name="ID_VD", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="rbStavke", column=@Column(name="RB_STAVKE", nullable=false, precision=3, scale=0) ) } )
    public UzDokumentStavkaId getId() {
        return this.id;
    }
    
    public void setId(UzDokumentStavkaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_DOKUMENTA", referencedColumnName="ID_DOKUMENTA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ID_VD", referencedColumnName="ID_VD", nullable=false, insertable=false, updatable=false) } )
    public UzDokument getUzDokument() {
        return this.uzDokument;
    }
    
    public void setUzDokument(UzDokument uzDokument) {
        this.uzDokument = uzDokument;
    }

    
    @Column(name="STATUS_STAVKE", nullable=false, length=1)
    public String getStatusStavke() {
        return this.statusStavke;
    }
    
    public void setStatusStavke(String statusStavke) {
        this.statusStavke = statusStavke;
    }

    
    @Column(name="ID_JEDINICE_MERE", nullable=false, precision=3, scale=0)
    public int getIdJediniceMere() {
        return this.idJediniceMere;
    }
    
    public void setIdJediniceMere(int idJediniceMere) {
        this.idJediniceMere = idJediniceMere;
    }

    
    @Column(name="PROIZVOD", nullable=false, precision=7, scale=0)
    public int getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(int proizvod) {
        this.proizvod = proizvod;
    }

    
    @Column(name="NIVO_KVALITETA", nullable=false, length=2)
    public String getNivoKvaliteta() {
        return this.nivoKvaliteta;
    }
    
    public void setNivoKvaliteta(String nivoKvaliteta) {
        this.nivoKvaliteta = nivoKvaliteta;
    }

    
    @Column(name="VRSTA_PROMENE", nullable=false, precision=2, scale=0)
    public int getVrstaPromene() {
        return this.vrstaPromene;
    }
    
    public void setVrstaPromene(int vrstaPromene) {
        this.vrstaPromene = vrstaPromene;
    }

    
    @Column(name="ID_KONTROLNOG_BROJA", precision=5, scale=0)
    public Integer getIdKontrolnogBroja() {
        return this.idKontrolnogBroja;
    }
    
    public void setIdKontrolnogBroja(Integer idKontrolnogBroja) {
        this.idKontrolnogBroja = idKontrolnogBroja;
    }

    
    @Column(name="ID_LOTA_PP", length=20)
    public String getIdLotaPp() {
        return this.idLotaPp;
    }
    
    public void setIdLotaPp(String idLotaPp) {
        this.idLotaPp = idLotaPp;
    }

    
    @Column(name="ISPOR_KOL", precision=18, scale=3)
    public BigDecimal getIsporKol() {
        return this.isporKol;
    }
    
    public void setIsporKol(BigDecimal isporKol) {
        this.isporKol = isporKol;
    }

    
    @Column(name="NAVED_KOL", precision=18, scale=3)
    public BigDecimal getNavedKol() {
        return this.navedKol;
    }
    
    public void setNavedKol(BigDecimal navedKol) {
        this.navedKol = navedKol;
    }

    
    @Column(name="JEDINICNA_CENA", scale=4)
    public BigDecimal getJedinicnaCena() {
        return this.jedinicnaCena;
    }
    
    public void setJedinicnaCena(BigDecimal jedinicnaCena) {
        this.jedinicnaCena = jedinicnaCena;
    }

    
    @Column(name="VREDNOST", precision=17, scale=4)
    public BigDecimal getVrednost() {
        return this.vrednost;
    }
    
    public void setVrednost(BigDecimal vrednost) {
        this.vrednost = vrednost;
    }

    
    @Column(name="ID_PORUDZBENICE", precision=6, scale=0)
    public Integer getIdPorudzbenice() {
        return this.idPorudzbenice;
    }
    
    public void setIdPorudzbenice(Integer idPorudzbenice) {
        this.idPorudzbenice = idPorudzbenice;
    }

    
    @Column(name="RB_STAVKE_PORUDZBENICE", precision=3, scale=0)
    public Short getRbStavkePorudzbenice() {
        return this.rbStavkePorudzbenice;
    }
    
    public void setRbStavkePorudzbenice(Short rbStavkePorudzbenice) {
        this.rbStavkePorudzbenice = rbStavkePorudzbenice;
    }

    
    @Column(name="KOLICINA_PROMENER", precision=18, scale=3)
    public BigDecimal getKolicinaPromener() {
        return this.kolicinaPromener;
    }
    
    public void setKolicinaPromener(BigDecimal kolicinaPromener) {
        this.kolicinaPromener = kolicinaPromener;
    }

    
    @Column(name="ID_VD_PO", precision=3, scale=0)
    public Short getIdVdPo() {
        return this.idVdPo;
    }
    
    public void setIdVdPo(Short idVdPo) {
        this.idVdPo = idVdPo;
    }

    
    @Column(name="ID_DOKUMENTA_PO", length=30)
    public String getIdDokumentaPo() {
        return this.idDokumentaPo;
    }
    
    public void setIdDokumentaPo(String idDokumentaPo) {
        this.idDokumentaPo = idDokumentaPo;
    }

    
    @Column(name="RB_STAVKE_PO", precision=3, scale=0)
    public Short getRbStavkePo() {
        return this.rbStavkePo;
    }
    
    public void setRbStavkePo(Short rbStavkePo) {
        this.rbStavkePo = rbStavkePo;
    }

    
    @Column(name="KOLICINA_PROMENE_PO", precision=18, scale=3)
    public BigDecimal getKolicinaPromenePo() {
        return this.kolicinaPromenePo;
    }
    
    public void setKolicinaPromenePo(BigDecimal kolicinaPromenePo) {
        this.kolicinaPromenePo = kolicinaPromenePo;
    }

    
    @Column(name="POSLOVNI_PARTNER#", precision=7, scale=0)
    public Integer getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(Integer poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }

    
    @Column(name="JEDINICNA_TEZINA", precision=7, scale=3)
    public BigDecimal getJedinicnaTezina() {
        return this.jedinicnaTezina;
    }
    
    public void setJedinicnaTezina(BigDecimal jedinicnaTezina) {
        this.jedinicnaTezina = jedinicnaTezina;
    }

    
    @Column(name="RB_SARZE", precision=3, scale=0)
    public Short getRbSarze() {
        return this.rbSarze;
    }
    
    public void setRbSarze(Short rbSarze) {
        this.rbSarze = rbSarze;
    }

    
    @Column(name="SERIJSKI_BROJ", length=20)
    public String getSerijskiBroj() {
        return this.serijskiBroj;
    }
    
    public void setSerijskiBroj(String serijskiBroj) {
        this.serijskiBroj = serijskiBroj;
    }

    
    @Column(name="VRSTA_PROIZVODA#", precision=2, scale=0)
    public int getVrstaProizvoda() {
        return this.vrstaProizvoda;
    }
    
    public void setVrstaProizvoda(int vrstaProizvoda) {
        this.vrstaProizvoda = vrstaProizvoda;
    }

    
    @Column(name="GODINA", precision=4, scale=0)
    public int getGodina() {
        return this.godina;
    }
    
    public void setGodina(int godina) {
        this.godina = godina;
    }

    
    @Column(name="KNJ_VREDNOST", precision=16)
    public BigDecimal getKnjVrednost() {
        return this.knjVrednost;
    }
    
    public void setKnjVrednost(BigDecimal knjVrednost) {
        this.knjVrednost = knjVrednost;
    }

    
    @Column(name="ID_DOKUMENTA_OLD", precision=7, scale=0)
    public Integer getIdDokumentaOld() {
        return this.idDokumentaOld;
    }
    
    public void setIdDokumentaOld(Integer idDokumentaOld) {
        this.idDokumentaOld = idDokumentaOld;
    }

    
    @Column(name="RABAT", precision=16, scale=3)
    public BigDecimal getRabat() {
        return this.rabat;
    }
    
    public void setRabat(BigDecimal rabat) {
        this.rabat = rabat;
    }

    
    @Column(name="KOL1", precision=18, scale=3)
    public BigDecimal getKol1() {
        return this.kol1;
    }
    
    public void setKol1(BigDecimal kol1) {
        this.kol1 = kol1;
    }

    
    @Column(name="KOL2", precision=18, scale=3)
    public BigDecimal getKol2() {
        return this.kol2;
    }
    
    public void setKol2(BigDecimal kol2) {
        this.kol2 = kol2;
    }

    
    @Column(name="KOL3", precision=18, scale=3)
    public BigDecimal getKol3() {
        return this.kol3;
    }
    
    public void setKol3(BigDecimal kol3) {
        this.kol3 = kol3;
    }

    
    @Column(name="KOL4", precision=18, scale=3)
    public BigDecimal getKol4() {
        return this.kol4;
    }
    
    public void setKol4(BigDecimal kol4) {
        this.kol4 = kol4;
    }

    
    @Column(name="KOL5", precision=18, scale=3)
    public BigDecimal getKol5() {
        return this.kol5;
    }
    
    public void setKol5(BigDecimal kol5) {
        this.kol5 = kol5;
    }

    
    @Column(name="KOL6", length=100)
    public String getKol6() {
        return this.kol6;
    }
    
    public void setKol6(String kol6) {
        this.kol6 = kol6;
    }

    
    @Column(name="KOL7", length=100)
    public String getKol7() {
        return this.kol7;
    }
    
    public void setKol7(String kol7) {
        this.kol7 = kol7;
    }

    
    @Column(name="KOL8", length=100)
    public String getKol8() {
        return this.kol8;
    }
    
    public void setKol8(String kol8) {
        this.kol8 = kol8;
    }

    
    @Column(name="KOL9", length=100)
    public String getKol9() {
        return this.kol9;
    }
    
    public void setKol9(String kol9) {
        this.kol9 = kol9;
    }

    
    @Column(name="KOL10", length=100)
    public String getKol10() {
        return this.kol10;
    }
    
    public void setKol10(String kol10) {
        this.kol10 = kol10;
    }

    
    @Column(name="COL02", length=10)
    public String getCol02() {
        return this.col02;
    }
    
    public void setCol02(String col02) {
        this.col02 = col02;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="uzDokumentStavka")
    public Set<UzDokumentStavkaPakovanje> getUzDokumentStavkaPakovanjes() {
        return this.uzDokumentStavkaPakovanjes;
    }
    
    public void setUzDokumentStavkaPakovanjes(Set uzDokumentStavkaPakovanjes) {
        this.uzDokumentStavkaPakovanjes = uzDokumentStavkaPakovanjes;
    }




}


