package rs.invado.wo.domain.wo;

// Generated Jan 13, 2013 6:20:53 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WoDownloadFilesId generated by hbm2java
 */
@Embeddable
public class WoDownloadFilesId implements java.io.Serializable {

	private BigDecimal idTipa;
	private BigDecimal idFajla;

	public WoDownloadFilesId() {
	}

	public WoDownloadFilesId(BigDecimal idTipa, BigDecimal idFajla) {
		this.idTipa = idTipa;
		this.idFajla = idFajla;
	}

	@Column(name = "ID_TIPA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdTipa() {
		return this.idTipa;
	}

	public void setIdTipa(BigDecimal idTipa) {
		this.idTipa = idTipa;
	}

	@Column(name = "ID_FAJLA", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdFajla() {
		return this.idFajla;
	}

	public void setIdFajla(BigDecimal idFajla) {
		this.idFajla = idFajla;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WoDownloadFilesId))
			return false;
		WoDownloadFilesId castOther = (WoDownloadFilesId) other;

		return ((this.getIdTipa() == castOther.getIdTipa()) || (this
				.getIdTipa() != null && castOther.getIdTipa() != null && this
				.getIdTipa().equals(castOther.getIdTipa())))
				&& ((this.getIdFajla() == castOther.getIdFajla()) || (this
						.getIdFajla() != null && castOther.getIdFajla() != null && this
						.getIdFajla().equals(castOther.getIdFajla())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdTipa() == null ? 0 : this.getIdTipa().hashCode());
		result = 37 * result
				+ (getIdFajla() == null ? 0 : this.getIdFajla().hashCode());
		return result;
	}

}
