package rs.invado.wo.domain.uz;
// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

/**
 * UzDokumentUsloviPlacanja generated by hbm2java
 */
@Entity
@Table(name="UZ_DOKUMENT_USLOVI_PLACANJA"
    ,schema="DAREX"
)
public class UzDokumentUsloviPlacanja  implements java.io.Serializable {


     private UzDokumentUsloviPlacanjaId id;
     private BigDecimal procKassaSkonto;
     private String brojIzjave;
     private Date datumIzjave;
     private Byte vrstaKursneListe;
     private Date datumKursneListe;
     private Short idValute;
     private Boolean namenaRobe;
     private int brojDanaValute;
     private String pakovanje;
     private String idKorisnika;
     private String nacinPlacanja;
     private Short nacinIsporuke;
     private Integer procenatRabata;
     private Boolean kreiratiFakturu;
     private BigDecimal avans;
     private String stampaCene;
     private Short vrstaStavke;

    private UzDokument uzDokument;

    public UzDokumentUsloviPlacanja() {
    }

	
    public UzDokumentUsloviPlacanja(UzDokument uzDokument, int brojDanaValute) {
        this.uzDokument = uzDokument;
        this.brojDanaValute = brojDanaValute;
    }
    public UzDokumentUsloviPlacanja(UzDokument uzDokument, BigDecimal procKassaSkonto, String brojIzjave, Date datumIzjave, Byte vrstaKursneListe, Date datumKursneListe, Short idValute, Boolean namenaRobe, int brojDanaValute, String pakovanje, String idKorisnika, String nacinPlacanja, Short nacinIsporuke, Integer procenatRabata, Boolean kreiratiFakturu, BigDecimal avans, String stampaCene, Short vrstaStavke) {
       this.uzDokument = uzDokument;
       this.procKassaSkonto = procKassaSkonto;
       this.brojIzjave = brojIzjave;
       this.datumIzjave = datumIzjave;
       this.vrstaKursneListe = vrstaKursneListe;
       this.datumKursneListe = datumKursneListe;
       this.idValute = idValute;
       this.namenaRobe = namenaRobe;
       this.brojDanaValute = brojDanaValute;
       this.pakovanje = pakovanje;
       this.idKorisnika = idKorisnika;
       this.nacinPlacanja = nacinPlacanja;
       this.nacinIsporuke = nacinIsporuke;
       this.procenatRabata = procenatRabata;
       this.kreiratiFakturu = kreiratiFakturu;
       this.avans = avans;
       this.stampaCene = stampaCene;
       this.vrstaStavke = vrstaStavke;
    }
   
     @EmbeddedId


    @AttributeOverrides( {
        @AttributeOverride(name="idVd", column=@Column(name="ID_VD", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="idDokumenta", column=@Column(name="ID_DOKUMENTA", nullable=false, length=30) ) } )
    public UzDokumentUsloviPlacanjaId getId() {
        return this.id;
    }
    
    public void setId(UzDokumentUsloviPlacanjaId id) {
        this.id = id;
    }



    /*
    @OneToOne(fetch=FetchType.LAZY)
    @PrimaryKeyJoinColumn*/
    @Transient
    public UzDokument getUzDokument() {
        return uzDokument;
    }

    public void setUzDokument(UzDokument uzDokument) {
        this.uzDokument = uzDokument;
    }


    @Column(name="PROC_KASSA_SKONTO", precision=6, scale=3)
    public BigDecimal getProcKassaSkonto() {
        return this.procKassaSkonto;
    }
    
    public void setProcKassaSkonto(BigDecimal procKassaSkonto) {
        this.procKassaSkonto = procKassaSkonto;
    }

    
    @Column(name="BROJ_IZJAVE", length=15)
    public String getBrojIzjave() {
        return this.brojIzjave;
    }
    
    public void setBrojIzjave(String brojIzjave) {
        this.brojIzjave = brojIzjave;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_IZJAVE", length=7)
    public Date getDatumIzjave() {
        return this.datumIzjave;
    }
    
    public void setDatumIzjave(Date datumIzjave) {
        this.datumIzjave = datumIzjave;
    }

    
    @Column(name="VRSTA_KURSNE_LISTE#", precision=2, scale=0)
    public Byte getVrstaKursneListe() {
        return this.vrstaKursneListe;
    }
    
    public void setVrstaKursneListe(Byte vrstaKursneListe) {
        this.vrstaKursneListe = vrstaKursneListe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_KURSNE_LISTE#", length=7)
    public Date getDatumKursneListe() {
        return this.datumKursneListe;
    }
    
    public void setDatumKursneListe(Date datumKursneListe) {
        this.datumKursneListe = datumKursneListe;
    }

    
    @Column(name="ID_VALUTE", precision=3, scale=0)
    public Short getIdValute() {
        return this.idValute;
    }
    
    public void setIdValute(Short idValute) {
        this.idValute = idValute;
    }

    
    @Column(name="NAMENA_ROBE", precision=1, scale=0)
    public Boolean getNamenaRobe() {
        return this.namenaRobe;
    }
    
    public void setNamenaRobe(Boolean namenaRobe) {
        this.namenaRobe = namenaRobe;
    }

    
    @Column(name="BROJ_DANA_VALUTE", nullable=false, precision=3, scale=0)
    public int getBrojDanaValute() {
        return this.brojDanaValute;
    }
    
    public void setBrojDanaValute(int brojDanaValute) {
        this.brojDanaValute = brojDanaValute;
    }

    
    @Column(name="PAKOVANJE", length=200)
    public String getPakovanje() {
        return this.pakovanje;
    }
    
    public void setPakovanje(String pakovanje) {
        this.pakovanje = pakovanje;
    }

    
    @Column(name="ID_KORISNIKA", length=20)
    public String getIdKorisnika() {
        return this.idKorisnika;
    }
    
    public void setIdKorisnika(String idKorisnika) {
        this.idKorisnika = idKorisnika;
    }

    
    @Column(name="NACIN_PLACANJA", length=3)
    public String getNacinPlacanja() {
        return this.nacinPlacanja;
    }
    
    public void setNacinPlacanja(String nacinPlacanja) {
        this.nacinPlacanja = nacinPlacanja;
    }

    
    @Column(name="NACIN_ISPORUKE", precision=3, scale=0)
    public Short getNacinIsporuke() {
        return this.nacinIsporuke;
    }
    
    public void setNacinIsporuke(Short nacinIsporuke) {
        this.nacinIsporuke = nacinIsporuke;
    }

    
    @Column(name="PROCENAT_RABATA", precision=6, scale=0)
    public Integer getProcenatRabata() {
        return this.procenatRabata;
    }
    
    public void setProcenatRabata(Integer procenatRabata) {
        this.procenatRabata = procenatRabata;
    }

    
    @Column(name="KREIRATI_FAKTURU", precision=1, scale=0)
    public Boolean getKreiratiFakturu() {
        return this.kreiratiFakturu;
    }
    
    public void setKreiratiFakturu(Boolean kreiratiFakturu) {
        this.kreiratiFakturu = kreiratiFakturu;
    }

    
    @Column(name="AVANS", precision=20, scale=3)
    public BigDecimal getAvans() {
        return this.avans;
    }
    
    public void setAvans(BigDecimal avans) {
        this.avans = avans;
    }

    
    @Column(name="STAMPA_CENE", length=2)
    public String getStampaCene() {
        return this.stampaCene;
    }
    
    public void setStampaCene(String stampaCene) {
        this.stampaCene = stampaCene;
    }

    
    @Column(name="VRSTA_STAVKE#", precision=3, scale=0)
    public Short getVrstaStavke() {
        return this.vrstaStavke;
    }
    
    public void setVrstaStavke(Short vrstaStavke) {
        this.vrstaStavke = vrstaStavke;
    }




}


