package rs.invado.wo.domain.prod;

// Generated Dec 11, 2012 10:40:41 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import rs.invado.wo.domain.ocp.OcpProizvod;

/**
 * ProdStavkaCenovnika generated by hbm2java
 */
@Entity
@Table(name = "PROD_STAVKA_CENOVNIKA", schema = "DAREX")
public class ProdStavkaCenovnika implements java.io.Serializable {

	private ProdStavkaCenovnikaId id;
	private ProdCenovnik prodCenovnik;
	private BigDecimal cena;
	private OcpProizvod ocpProizvod;

	public ProdStavkaCenovnika() {
	}

	public ProdStavkaCenovnika(ProdStavkaCenovnikaId id,
			ProdCenovnik prodCenovnik) {
		this.id = id;
		this.prodCenovnik = prodCenovnik;
	}

	public ProdStavkaCenovnika(ProdStavkaCenovnikaId id,
			ProdCenovnik prodCenovnik, BigDecimal cena) {
		this.id = id;
		this.prodCenovnik = prodCenovnik;
		this.cena = cena;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "organizacionaJedinica#", column = @Column(name = "ORGANIZACIONA_JEDINICA#", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "idCenovnik", column = @Column(name = "ID_CENOVNIK", nullable = false, precision = 5, scale = 0)),
			@AttributeOverride(name = "idKlasaCene", column = @Column(name = "ID_KLASA_CENE", nullable = false, precision = 2, scale = 0)),
			@AttributeOverride(name = "proizvod", column = @Column(name = "PROIZVOD#", nullable = false, precision = 7, scale = 0)) })
	public ProdStavkaCenovnikaId getId() {
		return this.id;
	}

	public void setId(ProdStavkaCenovnikaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ORGANIZACIONA_JEDINICA#", referencedColumnName = "ORGANIZACIONA_JEDINICA#", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_CENOVNIK", referencedColumnName = "ID_CENOVNIK", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_KLASA_CENE", referencedColumnName = "ID_KLASA_CENE", nullable = false, insertable = false, updatable = false) })
	public ProdCenovnik getProdCenovnik() {
		return this.prodCenovnik;
	}

	public void setProdCenovnik(ProdCenovnik prodCenovnik) {
		this.prodCenovnik = prodCenovnik;
	}

	@Column(name = "CENA", precision = 16, scale = 4)
	public BigDecimal getCena() {
		return this.cena;
	}

	public void setCena(BigDecimal cena) {
		this.cena = cena;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="PROIZVOD#", referencedColumnName="PROIZVOD#", nullable=false, insertable=false, updatable=false)
	public OcpProizvod getOcpProizvod() {
		return ocpProizvod;
	}

	public void setOcpProizvod(OcpProizvod ocpProizvod) {
		this.ocpProizvod = ocpProizvod;
	}

}
