package rs.invado.wo.domain.prod;
// Generated Jan 20, 2013 9:50:58 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProdNacinPlacanja generated by hbm2java
 */
@Entity
@Table(name="PROD_NACIN_PLACANJA"
    ,schema="DAREX"
)
public class ProdNacinPlacanja  implements java.io.Serializable {


     private String nacin;
     private String naziv;
     private String opis;
     private Short nacinF;
     private Short vrstaStavke;

    public ProdNacinPlacanja() {
    }

	
    public ProdNacinPlacanja(String nacin, String naziv) {
        this.nacin = nacin;
        this.naziv = naziv;
    }
    public ProdNacinPlacanja(String nacin, String naziv, String opis, Short nacinF, Short vrstaStavke) {
       this.nacin = nacin;
       this.naziv = naziv;
       this.opis = opis;
       this.nacinF = nacinF;
       this.vrstaStavke = vrstaStavke;
    }
   
     @Id 

    
    @Column(name="NACIN#", unique=true, nullable=false, length=3)
    public String getNacin() {
        return this.nacin;
    }
    
    public void setNacin(String nacin) {
        this.nacin = nacin;
    }

    
    @Column(name="NAZIV", nullable=false, length=20)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="OPIS", length=2000)
    public String getOpis() {
        return this.opis;
    }
    
    public void setOpis(String opis) {
        this.opis = opis;
    }

    
    @Column(name="NACIN#_F", precision=3, scale=0)
    public Short getNacinF() {
        return this.nacinF;
    }
    
    public void setNacinF(Short nacinF) {
        this.nacinF = nacinF;
    }

    
    @Column(name="VRSTA_STAVKE#", precision=3, scale=0)
    public Short getVrstaStavke() {
        return this.vrstaStavke;
    }
    
    public void setVrstaStavke(Short vrstaStavke) {
        this.vrstaStavke = vrstaStavke;
    }




}


