package rs.invado.wo.domain.prod;
// Generated Jan 20, 2013 11:37:50 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * ProdFinDokument generated by hbm2java
 */
@Entity
@Table(name="PROD_FIN_DOKUMENT"
    ,schema="DAREX"
)
@NamedNativeQuery(name = "insertFinDokument", query = "{  ? = call wofakturisanje.kreiraj_fakturu_hib(:vdotp, :idotp)}",
        resultClass = ProdFinDokument.class, hints = { @javax.persistence.QueryHint(name = "org.hibernate.callable", value = "true") })
public class ProdFinDokument  implements java.io.Serializable {


     private ProdFinDokumentId id;
     private ProdFinDokument prodFinDokument;
     private short brojPoslednjeStavke;
     private String statusDok;
     private Date datumFormiranja;
     private Date datumDpo;
     private int radnik;
     private int poslovniPartnerPr;
     private int poslovniPartnerPl;
     private Integer idCenovnikPp;
     private Byte idKlasaCenePp;
     private Integer organizacionaJedinicaPp;
     private String nacinOtpreme;
     private BigDecimal procKassaSkonto;
     private String brojIzjave;
     private Date datumIzjave;
     private BigDecimal procNaturalniRabat;
     private String napomena;
     private String fleg;
     private Date datum;
     private BigDecimal vrednostZaUplatu;
     private Integer organizacionaJedinicaReal;
     private Integer radnikTp;
     private Short idOz;
     private Byte vrstaKursneListe;
     private Date datumKursneListe;
     private Short idValute;
     private Boolean namenaRobe;
     private Short brojDanaValute;
     private String pakovanje;
     private String idKorisnika;
     private Short vrstaAkcize;
     private String nacinPlacanja;
     private Short nacinIsporuke;
     private String reklama;
     private Integer radnikOverio;
     private String ugovorBroj;
     private Date datumIsporuke;
     private String ziroRacun;
     private Integer poslovniPartner;
     private BigDecimal periodId;
     private Integer opdokOrganizacionaJedinica;
     private Short opdokGodina;
     private Short opdokIdVd;
     private String opdokIdDokumenta;
     private String pdv;
     private Date datumFiskalnog;
     private Short brojDanaIsporuke;
     private Set prodStavkaFinDokumentas = new HashSet(0);
     private Set prodFinDokuments = new HashSet(0);

    public ProdFinDokument() {
    }

	
    public ProdFinDokument(ProdFinDokumentId id, short brojPoslednjeStavke, String statusDok, Date datumFormiranja, int radnik, int poslovniPartnerPr, int poslovniPartnerPl) {
        this.id = id;
        this.brojPoslednjeStavke = brojPoslednjeStavke;
        this.statusDok = statusDok;
        this.datumFormiranja = datumFormiranja;
        this.radnik = radnik;
        this.poslovniPartnerPr = poslovniPartnerPr;
        this.poslovniPartnerPl = poslovniPartnerPl;
    }
    public ProdFinDokument(ProdFinDokumentId id, ProdFinDokument prodFinDokument, short brojPoslednjeStavke, String statusDok, Date datumFormiranja, Date datumDpo, int radnik, int poslovniPartnerPr, int poslovniPartnerPl, Integer idCenovnikPp, Byte idKlasaCenePp, Integer organizacionaJedinicaPp, String nacinOtpreme, BigDecimal procKassaSkonto, String brojIzjave, Date datumIzjave, BigDecimal procNaturalniRabat, String napomena, String fleg, Date datum, BigDecimal vrednostZaUplatu, Integer organizacionaJedinicaReal, Integer radnikTp, Short idOz, Byte vrstaKursneListe, Date datumKursneListe, Short idValute, Boolean namenaRobe, Short brojDanaValute, String pakovanje, String idKorisnika, Short vrstaAkcize, String nacinPlacanja, Short nacinIsporuke, String reklama, Integer radnikOverio, String ugovorBroj, Date datumIsporuke, String ziroRacun, Integer poslovniPartner, BigDecimal periodId, Integer opdokOrganizacionaJedinica, Short opdokGodina, Short opdokIdVd, String opdokIdDokumenta, String pdv, Date datumFiskalnog, Short brojDanaIsporuke, Set prodStavkaFinDokumentas, Set prodFinDokuments) {
       this.id = id;
       this.prodFinDokument = prodFinDokument;
       this.brojPoslednjeStavke = brojPoslednjeStavke;
       this.statusDok = statusDok;
       this.datumFormiranja = datumFormiranja;
       this.datumDpo = datumDpo;
       this.radnik = radnik;
       this.poslovniPartnerPr = poslovniPartnerPr;
       this.poslovniPartnerPl = poslovniPartnerPl;
       this.idCenovnikPp = idCenovnikPp;
       this.idKlasaCenePp = idKlasaCenePp;
       this.organizacionaJedinicaPp = organizacionaJedinicaPp;
       this.nacinOtpreme = nacinOtpreme;
       this.procKassaSkonto = procKassaSkonto;
       this.brojIzjave = brojIzjave;
       this.datumIzjave = datumIzjave;
       this.procNaturalniRabat = procNaturalniRabat;
       this.napomena = napomena;
       this.fleg = fleg;
       this.datum = datum;
       this.vrednostZaUplatu = vrednostZaUplatu;
       this.organizacionaJedinicaReal = organizacionaJedinicaReal;
       this.radnikTp = radnikTp;
       this.idOz = idOz;
       this.vrstaKursneListe = vrstaKursneListe;
       this.datumKursneListe = datumKursneListe;
       this.idValute = idValute;
       this.namenaRobe = namenaRobe;
       this.brojDanaValute = brojDanaValute;
       this.pakovanje = pakovanje;
       this.idKorisnika = idKorisnika;
       this.vrstaAkcize = vrstaAkcize;
       this.nacinPlacanja = nacinPlacanja;
       this.nacinIsporuke = nacinIsporuke;
       this.reklama = reklama;
       this.radnikOverio = radnikOverio;
       this.ugovorBroj = ugovorBroj;
       this.datumIsporuke = datumIsporuke;
       this.ziroRacun = ziroRacun;
       this.poslovniPartner = poslovniPartner;
       this.periodId = periodId;
       this.opdokOrganizacionaJedinica = opdokOrganizacionaJedinica;
       this.opdokGodina = opdokGodina;
       this.opdokIdVd = opdokIdVd;
       this.opdokIdDokumenta = opdokIdDokumenta;
       this.pdv = pdv;
       this.datumFiskalnog = datumFiskalnog;
       this.brojDanaIsporuke = brojDanaIsporuke;
       this.prodStavkaFinDokumentas = prodStavkaFinDokumentas;
       this.prodFinDokuments = prodFinDokuments;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVd", column=@Column(name="ID_VD", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="organizacionaJedinica", column=@Column(name="ORGANIZACIONA_JEDINICA#", nullable=false, precision=5, scale=0) ),
        @AttributeOverride(name="godina", column=@Column(name="GODINA", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="idFinDokumenta", column=@Column(name="ID_FIN_DOKUMENTA", nullable=false, precision=5, scale=0) ) } )
    public ProdFinDokumentId getId() {
        return this.id;
    }
    
    public void setId(ProdFinDokumentId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_VD_PO", referencedColumnName="ID_VD"), 
        @JoinColumn(name="ORGANIZACIONA_JEDINICA#_PO", referencedColumnName="ORGANIZACIONA_JEDINICA#"), 
        @JoinColumn(name="GODINA_PO", referencedColumnName="GODINA"), 
        @JoinColumn(name="ID_FIN_DOKUMENTA_PO", referencedColumnName="ID_FIN_DOKUMENTA") } )
    public ProdFinDokument getProdFinDokument() {
        return this.prodFinDokument;
    }
    
    public void setProdFinDokument(ProdFinDokument prodFinDokument) {
        this.prodFinDokument = prodFinDokument;
    }

    
    @Column(name="BROJ_POSLEDNJE_STAVKE", nullable=false, precision=3, scale=0)
    public short getBrojPoslednjeStavke() {
        return this.brojPoslednjeStavke;
    }
    
    public void setBrojPoslednjeStavke(short brojPoslednjeStavke) {
        this.brojPoslednjeStavke = brojPoslednjeStavke;
    }

    
    @Column(name="STATUS_DOK", nullable=false, length=1)
    public String getStatusDok() {
        return this.statusDok;
    }
    
    public void setStatusDok(String statusDok) {
        this.statusDok = statusDok;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_FORMIRANJA", nullable=false, length=7)
    public Date getDatumFormiranja() {
        return this.datumFormiranja;
    }
    
    public void setDatumFormiranja(Date datumFormiranja) {
        this.datumFormiranja = datumFormiranja;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_DPO", length=7)
    public Date getDatumDpo() {
        return this.datumDpo;
    }
    
    public void setDatumDpo(Date datumDpo) {
        this.datumDpo = datumDpo;
    }

    
    @Column(name="RADNIK#", nullable=false, precision=6, scale=0)
    public int getRadnik() {
        return this.radnik;
    }
    
    public void setRadnik(int radnik) {
        this.radnik = radnik;
    }

    
    @Column(name="POSLOVNI_PARTNER#_PR", nullable=false, precision=7, scale=0)
    public int getPoslovniPartnerPr() {
        return this.poslovniPartnerPr;
    }
    
    public void setPoslovniPartnerPr(int poslovniPartnerPr) {
        this.poslovniPartnerPr = poslovniPartnerPr;
    }

    
    @Column(name="POSLOVNI_PARTNER#_PL", nullable=false, precision=7, scale=0)
    public int getPoslovniPartnerPl() {
        return this.poslovniPartnerPl;
    }
    
    public void setPoslovniPartnerPl(int poslovniPartnerPl) {
        this.poslovniPartnerPl = poslovniPartnerPl;
    }

    
    @Column(name="ID_CENOVNIK_PP", precision=5, scale=0)
    public Integer getIdCenovnikPp() {
        return this.idCenovnikPp;
    }
    
    public void setIdCenovnikPp(Integer idCenovnikPp) {
        this.idCenovnikPp = idCenovnikPp;
    }

    
    @Column(name="ID_KLASA_CENE_PP", precision=2, scale=0)
    public Byte getIdKlasaCenePp() {
        return this.idKlasaCenePp;
    }
    
    public void setIdKlasaCenePp(Byte idKlasaCenePp) {
        this.idKlasaCenePp = idKlasaCenePp;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#_PP", precision=5, scale=0)
    public Integer getOrganizacionaJedinicaPp() {
        return this.organizacionaJedinicaPp;
    }
    
    public void setOrganizacionaJedinicaPp(Integer organizacionaJedinicaPp) {
        this.organizacionaJedinicaPp = organizacionaJedinicaPp;
    }

    
    @Column(name="NACIN_OTPREME")
    public String getNacinOtpreme() {
        return this.nacinOtpreme;
    }
    
    public void setNacinOtpreme(String nacinOtpreme) {
        this.nacinOtpreme = nacinOtpreme;
    }

    
    @Column(name="PROC_KASSA_SKONTO", precision=6, scale=3)
    public BigDecimal getProcKassaSkonto() {
        return this.procKassaSkonto;
    }
    
    public void setProcKassaSkonto(BigDecimal procKassaSkonto) {
        this.procKassaSkonto = procKassaSkonto;
    }

    
    @Column(name="BROJ_IZJAVE", length=15)
    public String getBrojIzjave() {
        return this.brojIzjave;
    }
    
    public void setBrojIzjave(String brojIzjave) {
        this.brojIzjave = brojIzjave;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_IZJAVE", length=7)
    public Date getDatumIzjave() {
        return this.datumIzjave;
    }
    
    public void setDatumIzjave(Date datumIzjave) {
        this.datumIzjave = datumIzjave;
    }

    
    @Column(name="PROC_NATURALNI_RABAT", precision=6, scale=3)
    public BigDecimal getProcNaturalniRabat() {
        return this.procNaturalniRabat;
    }
    
    public void setProcNaturalniRabat(BigDecimal procNaturalniRabat) {
        this.procNaturalniRabat = procNaturalniRabat;
    }

    
    @Column(name="NAPOMENA", length=2000)
    public String getNapomena() {
        return this.napomena;
    }
    
    public void setNapomena(String napomena) {
        this.napomena = napomena;
    }

    
    @Column(name="FLEG", length=1)
    public String getFleg() {
        return this.fleg;
    }
    
    public void setFleg(String fleg) {
        this.fleg = fleg;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", length=7)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="VREDNOST_ZA_UPLATU", precision=20, scale=3)
    public BigDecimal getVrednostZaUplatu() {
        return this.vrednostZaUplatu;
    }
    
    public void setVrednostZaUplatu(BigDecimal vrednostZaUplatu) {
        this.vrednostZaUplatu = vrednostZaUplatu;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#_REAL", precision=5, scale=0)
    public Integer getOrganizacionaJedinicaReal() {
        return this.organizacionaJedinicaReal;
    }
    
    public void setOrganizacionaJedinicaReal(Integer organizacionaJedinicaReal) {
        this.organizacionaJedinicaReal = organizacionaJedinicaReal;
    }

    
    @Column(name="RADNIK#_TP", precision=6, scale=0)
    public Integer getRadnikTp() {
        return this.radnikTp;
    }
    
    public void setRadnikTp(Integer radnikTp) {
        this.radnikTp = radnikTp;
    }

    
    @Column(name="ID_OZ", precision=3, scale=0)
    public Short getIdOz() {
        return this.idOz;
    }
    
    public void setIdOz(Short idOz) {
        this.idOz = idOz;
    }

    
    @Column(name="VRSTA_KURSNE_LISTE#", precision=2, scale=0)
    public Byte getVrstaKursneListe() {
        return this.vrstaKursneListe;
    }
    
    public void setVrstaKursneListe(Byte vrstaKursneListe) {
        this.vrstaKursneListe = vrstaKursneListe;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_KURSNE_LISTE#", length=7)
    public Date getDatumKursneListe() {
        return this.datumKursneListe;
    }
    
    public void setDatumKursneListe(Date datumKursneListe) {
        this.datumKursneListe = datumKursneListe;
    }

    
    @Column(name="ID_VALUTE", precision=3, scale=0)
    public Short getIdValute() {
        return this.idValute;
    }
    
    public void setIdValute(Short idValute) {
        this.idValute = idValute;
    }

    
    @Column(name="NAMENA_ROBE", precision=1, scale=0)
    public Boolean getNamenaRobe() {
        return this.namenaRobe;
    }
    
    public void setNamenaRobe(Boolean namenaRobe) {
        this.namenaRobe = namenaRobe;
    }

    
    @Column(name="BROJ_DANA_VALUTE", precision=3, scale=0)
    public Short getBrojDanaValute() {
        return this.brojDanaValute;
    }
    
    public void setBrojDanaValute(Short brojDanaValute) {
        this.brojDanaValute = brojDanaValute;
    }

    
    @Column(name="PAKOVANJE", length=200)
    public String getPakovanje() {
        return this.pakovanje;
    }
    
    public void setPakovanje(String pakovanje) {
        this.pakovanje = pakovanje;
    }

    
    @Column(name="ID_KORISNIKA", length=20)
    public String getIdKorisnika() {
        return this.idKorisnika;
    }
    
    public void setIdKorisnika(String idKorisnika) {
        this.idKorisnika = idKorisnika;
    }

    
    @Column(name="VRSTA_AKCIZE", precision=3, scale=0)
    public Short getVrstaAkcize() {
        return this.vrstaAkcize;
    }
    
    public void setVrstaAkcize(Short vrstaAkcize) {
        this.vrstaAkcize = vrstaAkcize;
    }

    
    @Column(name="NACIN_PLACANJA", length=3)
    public String getNacinPlacanja() {
        return this.nacinPlacanja;
    }
    
    public void setNacinPlacanja(String nacinPlacanja) {
        this.nacinPlacanja = nacinPlacanja;
    }

    
    @Column(name="NACIN_ISPORUKE", precision=3, scale=0)
    public Short getNacinIsporuke() {
        return this.nacinIsporuke;
    }
    
    public void setNacinIsporuke(Short nacinIsporuke) {
        this.nacinIsporuke = nacinIsporuke;
    }

    
    @Column(name="REKLAMA", length=200)
    public String getReklama() {
        return this.reklama;
    }
    
    public void setReklama(String reklama) {
        this.reklama = reklama;
    }

    
    @Column(name="RADNIK#_OVERIO", precision=6, scale=0)
    public Integer getRadnikOverio() {
        return this.radnikOverio;
    }
    
    public void setRadnikOverio(Integer radnikOverio) {
        this.radnikOverio = radnikOverio;
    }

    
    @Column(name="UGOVOR_BROJ", length=100)
    public String getUgovorBroj() {
        return this.ugovorBroj;
    }
    
    public void setUgovorBroj(String ugovorBroj) {
        this.ugovorBroj = ugovorBroj;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_ISPORUKE", length=7)
    public Date getDatumIsporuke() {
        return this.datumIsporuke;
    }
    
    public void setDatumIsporuke(Date datumIsporuke) {
        this.datumIsporuke = datumIsporuke;
    }

    
    @Column(name="ZIRO_RACUN#", length=40)
    public String getZiroRacun() {
        return this.ziroRacun;
    }
    
    public void setZiroRacun(String ziroRacun) {
        this.ziroRacun = ziroRacun;
    }

    
    @Column(name="POSLOVNI_PARTNER#", precision=7, scale=0)
    public Integer getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(Integer poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }

    
    @Column(name="PERIOD_ID", precision=22, scale=0)
    public BigDecimal getPeriodId() {
        return this.periodId;
    }
    
    public void setPeriodId(BigDecimal periodId) {
        this.periodId = periodId;
    }

    
    @Column(name="OPDOK_ORGANIZACIONA_JEDINICA#", precision=5, scale=0)
    public Integer getOpdokOrganizacionaJedinica() {
        return this.opdokOrganizacionaJedinica;
    }
    
    public void setOpdokOrganizacionaJedinica(Integer opdokOrganizacionaJedinica) {
        this.opdokOrganizacionaJedinica = opdokOrganizacionaJedinica;
    }

    
    @Column(name="OPDOK_GODINA", precision=4, scale=0)
    public Short getOpdokGodina() {
        return this.opdokGodina;
    }
    
    public void setOpdokGodina(Short opdokGodina) {
        this.opdokGodina = opdokGodina;
    }

    
    @Column(name="OPDOK_ID_VD", precision=3, scale=0)
    public Short getOpdokIdVd() {
        return this.opdokIdVd;
    }
    
    public void setOpdokIdVd(Short opdokIdVd) {
        this.opdokIdVd = opdokIdVd;
    }

    
    @Column(name="OPDOK_ID_DOKUMENTA", length=30)
    public String getOpdokIdDokumenta() {
        return this.opdokIdDokumenta;
    }
    
    public void setOpdokIdDokumenta(String opdokIdDokumenta) {
        this.opdokIdDokumenta = opdokIdDokumenta;
    }

    
    @Column(name="PDV", length=2)
    public String getPdv() {
        return this.pdv;
    }
    
    public void setPdv(String pdv) {
        this.pdv = pdv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_FISKALNOG", length=7)
    public Date getDatumFiskalnog() {
        return this.datumFiskalnog;
    }
    
    public void setDatumFiskalnog(Date datumFiskalnog) {
        this.datumFiskalnog = datumFiskalnog;
    }

    
    @Column(name="BROJ_DANA_ISPORUKE", precision=3, scale=0)
    public Short getBrojDanaIsporuke() {
        return this.brojDanaIsporuke;
    }
    
    public void setBrojDanaIsporuke(Short brojDanaIsporuke) {
        this.brojDanaIsporuke = brojDanaIsporuke;
    }

@OneToMany(targetEntity = ProdStavkaFinDokumenta.class, fetch=FetchType.LAZY, mappedBy="prodFinDokument")
    public Set<ProdStavkaFinDokumenta> getProdStavkaFinDokumentas() {
        return this.prodStavkaFinDokumentas;
    }
    
    public void setProdStavkaFinDokumentas(Set prodStavkaFinDokumentas) {
        this.prodStavkaFinDokumentas = prodStavkaFinDokumentas;
    }

@OneToMany(targetEntity = ProdFinDokument.class, fetch=FetchType.LAZY, mappedBy="prodFinDokument")
    public Set<ProdFinDokument> getProdFinDokuments() {
        return this.prodFinDokuments;
    }
    
    public void setProdFinDokuments(Set prodFinDokuments) {
        this.prodFinDokuments = prodFinDokuments;
    }




}


