package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcpAtribut generated by hbm2java
 */
@Entity
@Table(name="OCP_ATRIBUT"
    ,schema="DAREX"
)
public class OcpAtribut  implements java.io.Serializable {


     private int atribut;
     private OcpKlasifikacija ocpKlasifikacija;
     private String naziv;
     private String tipPodatka;
     private Short duzina;
     private String formatMaska;
     private String defaultVrednost;
     private String vrOd;
     private String vrDo;
     private String ukljucujeOd;
     private String ukljucujeDo;
     private String imaHijerarhiju;
     private String imaDiskretneVr;
     private Short jedinicaMere;
     private Integer atributGp;
     private String prefiksUNazivu;
     private Byte redosledUNazivu;

    public OcpAtribut() {
    }

	
    public OcpAtribut(int atribut) {
        this.atribut = atribut;
    }
    public OcpAtribut(int atribut, OcpKlasifikacija ocpKlasifikacija, String naziv, String tipPodatka, Short duzina, String formatMaska, String defaultVrednost, String vrOd, String vrDo, String ukljucujeOd, String ukljucujeDo, String imaHijerarhiju, String imaDiskretneVr, Short jedinicaMere, Integer atributGp, String prefiksUNazivu, Byte redosledUNazivu) {
       this.atribut = atribut;
       this.ocpKlasifikacija = ocpKlasifikacija;
       this.naziv = naziv;
       this.tipPodatka = tipPodatka;
       this.duzina = duzina;
       this.formatMaska = formatMaska;
       this.defaultVrednost = defaultVrednost;
       this.vrOd = vrOd;
       this.vrDo = vrDo;
       this.ukljucujeOd = ukljucujeOd;
       this.ukljucujeDo = ukljucujeDo;
       this.imaHijerarhiju = imaHijerarhiju;
       this.imaDiskretneVr = imaDiskretneVr;
       this.jedinicaMere = jedinicaMere;
       this.atributGp = atributGp;
       this.prefiksUNazivu = prefiksUNazivu;
       this.redosledUNazivu = redosledUNazivu;
    }
   
     @Id
    @Column(name="ATRIBUT#", unique=true, nullable=false, precision=6, scale=0)
    public int getAtribut() {
        return this.atribut;
    }
    
    public void setAtribut(int atribut) {
        this.atribut = atribut;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="VRSTA_KLASIFIKACIJE#", referencedColumnName="VRSTA_KLASIFIKACIJE#"), 
        @JoinColumn(name="KLASIFIKACIJA#", referencedColumnName="KLASIFIKACIJA#") } )
    public OcpKlasifikacija getOcpKlasifikacija() {
        return this.ocpKlasifikacija;
    }
    
    public void setOcpKlasifikacija(OcpKlasifikacija ocpKlasifikacija) {
        this.ocpKlasifikacija = ocpKlasifikacija;
    }

    
    @Column(name="NAZIV", length=60)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="TIP_PODATKA", length=10)
    public String getTipPodatka() {
        return this.tipPodatka;
    }
    
    public void setTipPodatka(String tipPodatka) {
        this.tipPodatka = tipPodatka;
    }

    
    @Column(name="DUZINA", precision=4, scale=0)
    public Short getDuzina() {
        return this.duzina;
    }
    
    public void setDuzina(Short duzina) {
        this.duzina = duzina;
    }

    
    @Column(name="FORMAT_MASKA", length=30)
    public String getFormatMaska() {
        return this.formatMaska;
    }
    
    public void setFormatMaska(String formatMaska) {
        this.formatMaska = formatMaska;
    }

    
    @Column(name="DEFAULT_VREDNOST", length=30)
    public String getDefaultVrednost() {
        return this.defaultVrednost;
    }
    
    public void setDefaultVrednost(String defaultVrednost) {
        this.defaultVrednost = defaultVrednost;
    }

    
    @Column(name="VR_OD", length=30)
    public String getVrOd() {
        return this.vrOd;
    }
    
    public void setVrOd(String vrOd) {
        this.vrOd = vrOd;
    }

    
    @Column(name="VR_DO", length=30)
    public String getVrDo() {
        return this.vrDo;
    }
    
    public void setVrDo(String vrDo) {
        this.vrDo = vrDo;
    }

    
    @Column(name="UKLJUCUJE_OD", length=1)
    public String getUkljucujeOd() {
        return this.ukljucujeOd;
    }
    
    public void setUkljucujeOd(String ukljucujeOd) {
        this.ukljucujeOd = ukljucujeOd;
    }

    
    @Column(name="UKLJUCUJE_DO", length=1)
    public String getUkljucujeDo() {
        return this.ukljucujeDo;
    }
    
    public void setUkljucujeDo(String ukljucujeDo) {
        this.ukljucujeDo = ukljucujeDo;
    }

    
    @Column(name="IMA_HIJERARHIJU", length=1)
    public String getImaHijerarhiju() {
        return this.imaHijerarhiju;
    }
    
    public void setImaHijerarhiju(String imaHijerarhiju) {
        this.imaHijerarhiju = imaHijerarhiju;
    }

    
    @Column(name="IMA_DISKRETNE_VR", length=1)
    public String getImaDiskretneVr() {
        return this.imaDiskretneVr;
    }
    
    public void setImaDiskretneVr(String imaDiskretneVr) {
        this.imaDiskretneVr = imaDiskretneVr;
    }

    
    @Column(name="JEDINICA_MERE#", precision=3, scale=0)
    public Short getJedinicaMere() {
        return this.jedinicaMere;
    }
    
    public void setJedinicaMere(Short jedinicaMere) {
        this.jedinicaMere = jedinicaMere;
    }

    
    @Column(name="ATRIBUT#_GP", precision=6, scale=0)
    public Integer getAtributGp() {
        return this.atributGp;
    }
    
    public void setAtributGp(Integer atributGp) {
        this.atributGp = atributGp;
    }

    
    @Column(name="PREFIKS_U_NAZIVU", length=1)
    public String getPrefiksUNazivu() {
        return this.prefiksUNazivu;
    }
    
    public void setPrefiksUNazivu(String prefiksUNazivu) {
        this.prefiksUNazivu = prefiksUNazivu;
    }

    
    @Column(name="REDOSLED_U_NAZIVU", precision=2, scale=0)
    public Byte getRedosledUNazivu() {
        return this.redosledUNazivu;
    }
    
    public void setRedosledUNazivu(Byte redosledUNazivu) {
        this.redosledUNazivu = redosledUNazivu;
    }




}


