package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import org.w3c.dom.stylesheets.LinkStyle;

import javax.persistence.*;
import java.util.ArrayList;
import java.util.List;

/**
 * OcpJedinicaMere generated by hbm2java
 */
@Entity
@Table(name = "OCP_JEDINICA_MERE", schema = "DAREX")
public class OcpJedinicaMere implements java.io.Serializable {

	private int idJediniceMere;
	private String jmZaDruguDonjuGranicu;
	private String jmZaDruguGornjuGranicu;
	private String jmZaPrvuDonjuGranicu;
	private String jmZaPrvuGornjuGranicu;
	private String nazivJediniceMere;
	private String skrOznakaSlozeneJm;
	private String skracenaOznaka;
	private String zaokruzi;



    public OcpJedinicaMere() {
	}

	public OcpJedinicaMere(int idJediniceMere, String nazivJediniceMere,
			String skracenaOznaka) {
		this.idJediniceMere = idJediniceMere;
		this.nazivJediniceMere = nazivJediniceMere;
		this.skracenaOznaka = skracenaOznaka;
	}

	public OcpJedinicaMere(int idJediniceMere, String jmZaDruguDonjuGranicu,
			String jmZaDruguGornjuGranicu, String jmZaPrvuDonjuGranicu,
			String jmZaPrvuGornjuGranicu, String nazivJediniceMere,
			String skrOznakaSlozeneJm, String skracenaOznaka, String zaokruzi) {
		this.idJediniceMere = idJediniceMere;
		this.jmZaDruguDonjuGranicu = jmZaDruguDonjuGranicu;
		this.jmZaDruguGornjuGranicu = jmZaDruguGornjuGranicu;
		this.jmZaPrvuDonjuGranicu = jmZaPrvuDonjuGranicu;
		this.jmZaPrvuGornjuGranicu = jmZaPrvuGornjuGranicu;
		this.nazivJediniceMere = nazivJediniceMere;
		this.skrOznakaSlozeneJm = skrOznakaSlozeneJm;
		this.skracenaOznaka = skracenaOznaka;
		this.zaokruzi = zaokruzi;
	}

	@Id
	@Column(name = "ID_JEDINICE_MERE", unique = true, nullable = false, precision = 5, scale = 0)
	public int getIdJediniceMere() {
		return this.idJediniceMere;
	}

	public void setIdJediniceMere(int idJediniceMere) {
		this.idJediniceMere = idJediniceMere;
	}

	@Column(name = "JM_ZA_DRUGU_DONJU_GRANICU", length = 28)
	public String getJmZaDruguDonjuGranicu() {
		return this.jmZaDruguDonjuGranicu;
	}

	public void setJmZaDruguDonjuGranicu(String jmZaDruguDonjuGranicu) {
		this.jmZaDruguDonjuGranicu = jmZaDruguDonjuGranicu;
	}

	@Column(name = "JM_ZA_DRUGU_GORNJU_GRANICU", length = 28)
	public String getJmZaDruguGornjuGranicu() {
		return this.jmZaDruguGornjuGranicu;
	}

	public void setJmZaDruguGornjuGranicu(String jmZaDruguGornjuGranicu) {
		this.jmZaDruguGornjuGranicu = jmZaDruguGornjuGranicu;
	}

	@Column(name = "JM_ZA_PRVU_DONJU_GRANICU", length = 28)
	public String getJmZaPrvuDonjuGranicu() {
		return this.jmZaPrvuDonjuGranicu;
	}

	public void setJmZaPrvuDonjuGranicu(String jmZaPrvuDonjuGranicu) {
		this.jmZaPrvuDonjuGranicu = jmZaPrvuDonjuGranicu;
	}

	@Column(name = "JM_ZA_PRVU_GORNJU_GRANICU", length = 28)
	public String getJmZaPrvuGornjuGranicu() {
		return this.jmZaPrvuGornjuGranicu;
	}

	public void setJmZaPrvuGornjuGranicu(String jmZaPrvuGornjuGranicu) {
		this.jmZaPrvuGornjuGranicu = jmZaPrvuGornjuGranicu;
	}

	@Column(name = "NAZIV_JEDINICE_MERE", nullable = false, length = 120)
	public String getNazivJediniceMere() {
		return this.nazivJediniceMere;
	}

	public void setNazivJediniceMere(String nazivJediniceMere) {
		this.nazivJediniceMere = nazivJediniceMere;
	}

	@Column(name = "SKR_OZNAKA_SLOZENE_JM", length = 40)
	public String getSkrOznakaSlozeneJm() {
		return this.skrOznakaSlozeneJm;
	}

	public void setSkrOznakaSlozeneJm(String skrOznakaSlozeneJm) {
		this.skrOznakaSlozeneJm = skrOznakaSlozeneJm;
	}

	@Column(name = "SKRACENA_OZNAKA", nullable = false, length = 40)
	public String getSkracenaOznaka() {
        if (this.skracenaOznaka != null) return this.skracenaOznaka.toLowerCase();
		return this.skracenaOznaka;
	}

	public void setSkracenaOznaka(String skracenaOznaka) {
		this.skracenaOznaka = skracenaOznaka;
	}

	@Column(name = "ZAOKRUZI", length = 8)
	public String getZaokruzi() {
		return this.zaokruzi;
	}

	public void setZaokruzi(String zaokruzi) {
		this.zaokruzi = zaokruzi;
	}



}
