package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * OcpKlasifikacijaPp generated by hbm2java
 */
@Entity
@Table(name = "OCP_KLASIFIKACIJA_PP", schema = "DAREX")
public class OcpKlasifikacijaPp implements java.io.Serializable {

	private OcpKlasifikacijaPpId id;
	private OcpKlasifikacija ocpKlasifikacija;

	public OcpKlasifikacijaPp() {
	}

	public OcpKlasifikacijaPp(OcpKlasifikacijaPpId id,
			OcpKlasifikacija ocpKlasifikacija) {
		this.id = id;
		this.ocpKlasifikacija = ocpKlasifikacija;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "vrstaKlasifikacije", column = @Column(name = "VRSTA_KLASIFIKACIJE#", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "klasifikacija", column = @Column(name = "KLASIFIKACIJA#", nullable = false, length = 15)),
			@AttributeOverride(name = "poslovniPartner", column = @Column(name = "POSLOVNI_PARTNER#", nullable = false, precision = 7, scale = 0)) })
	public OcpKlasifikacijaPpId getId() {
		return this.id;
	}

	public void setId(OcpKlasifikacijaPpId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "VRSTA_KLASIFIKACIJE#", referencedColumnName = "VRSTA_KLASIFIKACIJE#", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "KLASIFIKACIJA#", referencedColumnName = "KLASIFIKACIJA#", nullable = false, insertable = false, updatable = false) })
	public OcpKlasifikacija getOcpKlasifikacija() {
		return this.ocpKlasifikacija;
	}

	public void setOcpKlasifikacija(OcpKlasifikacija ocpKlasifikacija) {
		this.ocpKlasifikacija = ocpKlasifikacija;
	}

}
