package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.*;

/**
 * OcpKlasifikacijaProizvoda generated by hbm2java
 */
@Entity
@Table(name = "OCP_KLASIFIKACIJA_PROIZVODA", schema = "DAREX", uniqueConstraints = @UniqueConstraint(columnNames = {
		"VRSTA_KLASIFIKACIJE#", "PROIZVOD#" }))
public class OcpKlasifikacijaProizvoda implements java.io.Serializable {

	private OcpKlasifikacijaProizvodaId id;
	private OcpProizvod ocpProizvod ;
	private OcpKlasifikacija ocpKlasifikacija;
    private List<OcpVrAtrProizvod> vrAtrProizvod = new ArrayList<OcpVrAtrProizvod>();

	public OcpKlasifikacijaProizvoda() {
	}

	public OcpKlasifikacijaProizvoda(OcpKlasifikacijaProizvodaId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "vrstaKlasifikacije", column = @Column(name = "VRSTA_KLASIFIKACIJE#", nullable = false, precision = 6, scale = 0)),
			@AttributeOverride(name = "klasifikacija", column = @Column(name = "KLASIFIKACIJA#", nullable = false, length = 15)),
			@AttributeOverride(name = "proizvod", column = @Column(name = "PROIZVOD#", nullable = false, precision = 7, scale = 0)) })
	public OcpKlasifikacijaProizvodaId getId() {
		return this.id;
	}

	public void setId(OcpKlasifikacijaProizvodaId id) {
		this.id = id;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumn(name="PROIZVOD#", referencedColumnName="PROIZVOD#", nullable=false, updatable=false, insertable=false)
	public OcpProizvod getOcpProizvod() {
		return ocpProizvod;
	}

	public void setOcpProizvod(OcpProizvod ocpProizvod) {
		this.ocpProizvod = ocpProizvod;
	}

	@ManyToOne(fetch=FetchType.LAZY)
	@JoinColumns({
		@JoinColumn(name="KLASIFIKACIJA#", referencedColumnName="KLASIFIKACIJA#", nullable=false, updatable=false, insertable=false),
		@JoinColumn(name="VRSTA_KLASIFIKACIJE#",referencedColumnName="VRSTA_KLASIFIKACIJE#", nullable=false, insertable=false, updatable=false)
	})
	public OcpKlasifikacija getOcpKlasifikacija() {
		return ocpKlasifikacija;
	}

	public void setOcpKlasifikacija(OcpKlasifikacija ocpKlasifikacija) {
		this.ocpKlasifikacija = ocpKlasifikacija;
	}


    @OneToMany(targetEntity = OcpVrAtrProizvod.class, fetch = FetchType.LAZY, mappedBy = "ocpKlasifikacijaProizvoda")
    public List<OcpVrAtrProizvod> getVrAtrProizvod() {
        return vrAtrProizvod;
    }

    public void setVrAtrProizvod(List<OcpVrAtrProizvod> vrAtrProizvod) {
        this.vrAtrProizvod = vrAtrProizvod;
    }

}
