package rs.invado.wo.domain.ocp;
// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OcpLiceZaKontaktId generated by hbm2java
 */
@Embeddable
public class OcpLiceZaKontaktId  implements java.io.Serializable {


     private int poslovniPartner;
     private short rbr;

    public OcpLiceZaKontaktId() {
    }

    public OcpLiceZaKontaktId(int poslovniPartner, short rbr) {
       this.poslovniPartner = poslovniPartner;
       this.rbr = rbr;
    }
   


    @Column(name="POSLOVNI_PARTNER#", nullable=false, precision=7, scale=0)
    public int getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(int poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }


    @Column(name="RBR", nullable=false, precision=4, scale=0)
    public short getRbr() {
        return this.rbr;
    }
    
    public void setRbr(short rbr) {
        this.rbr = rbr;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof OcpLiceZaKontaktId) ) return false;
		 OcpLiceZaKontaktId castOther = ( OcpLiceZaKontaktId ) other; 
         
		 return (this.getPoslovniPartner()==castOther.getPoslovniPartner())
 && (this.getRbr()==castOther.getRbr());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPoslovniPartner();
         result = 37 * result + this.getRbr();
         return result;
   }   


}


