package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcpProizvodJeVrste generated by hbm2java
 */
@Entity
@Table(name = "OCP_PROIZVOD_JE_VRSTE", schema = "DAREX")
public class OcpProizvodJeVrste implements java.io.Serializable {

	private OcpProizvodJeVrsteId id;

	public OcpProizvodJeVrste() {
	}

	public OcpProizvodJeVrste(OcpProizvodJeVrsteId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "proizvod", column = @Column(name = "PROIZVOD#", nullable = false, precision = 7, scale = 0)),
			@AttributeOverride(name = "vrstaProizvoda", column = @Column(name = "VRSTA_PROIZVODA#", nullable = false, precision = 2, scale = 0)) })
	public OcpProizvodJeVrsteId getId() {
		return this.id;
	}

	public void setId(OcpProizvodJeVrsteId id) {
		this.id = id;
	}

}
