package rs.invado.wo.domain.ocp;

// Generated Dec 9, 2012 6:19:17 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * OcpVpNaVd generated by hbm2java
 */
@Entity
@Table(name = "OCP_VP_NA_VD", schema = "DAREX")
public class OcpVpNaVd implements java.io.Serializable {

	private OcpVpNaVdId id;
	private String mapProizvod;

	public OcpVpNaVd() {
	}

	public OcpVpNaVd(OcpVpNaVdId id) {
		this.id = id;
	}

	public OcpVpNaVd(OcpVpNaVdId id, String mapProizvod) {
		this.id = id;
		this.mapProizvod = mapProizvod;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "vrstaStavke", column = @Column(name = "VRSTA_STAVKE#", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "idVd", column = @Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "vrstaProizvoda", column = @Column(name = "VRSTA_PROIZVODA#", nullable = false, precision = 2, scale = 0)) })
	public OcpVpNaVdId getId() {
		return this.id;
	}

	public void setId(OcpVpNaVdId id) {
		this.id = id;
	}

	@Column(name = "MAP_PROIZVOD", length = 2)
	public String getMapProizvod() {
		return this.mapProizvod;
	}

	public void setMapProizvod(String mapProizvod) {
		this.mapProizvod = mapProizvod;
	}

}
