package rs.invado.wo.domain.uz;

// Generated Jan 1, 2013 5:03:16 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * UzSklNaVdId generated by hbm2java
 */
@Embeddable
public class UzSklNaVdId implements java.io.Serializable {

	private short idVd;
	private short idSkladista;

	public UzSklNaVdId() {
	}

	public UzSklNaVdId(short idVd, short idSkladista) {
		this.idVd = idVd;
		this.idSkladista = idSkladista;
	}

	@Column(name = "ID_VD", nullable = false, precision = 3, scale = 0)
	public short getIdVd() {
		return this.idVd;
	}

	public void setIdVd(short idVd) {
		this.idVd = idVd;
	}

	@Column(name = "ID_SKLADISTA", nullable = false, precision = 3, scale = 0)
	public short getIdSkladista() {
		return this.idSkladista;
	}

	public void setIdSkladista(short idSkladista) {
		this.idSkladista = idSkladista;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UzSklNaVdId))
			return false;
		UzSklNaVdId castOther = (UzSklNaVdId) other;

		return (this.getIdVd() == castOther.getIdVd())
				&& (this.getIdSkladista() == castOther.getIdSkladista());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdVd();
		result = 37 * result + this.getIdSkladista();
		return result;
	}

}
