package rs.invado.wo.domain.prod;
// Generated Jan 20, 2013 11:37:50 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdFinDokumentId generated by hbm2java
 */
@Embeddable
public class ProdFinDokumentId  implements java.io.Serializable {


     private short idVd;
     private int organizacionaJedinica;
     private short godina;
     private int idFinDokumenta;

    public ProdFinDokumentId() {
    }

    public ProdFinDokumentId(short idVd, int organizacionaJedinica, short godina, int idFinDokumenta) {
       this.idVd = idVd;
       this.organizacionaJedinica = organizacionaJedinica;
       this.godina = godina;
       this.idFinDokumenta = idFinDokumenta;
    }
   


    @Column(name="ID_VD", nullable=false, precision=3, scale=0)
    public short getIdVd() {
        return this.idVd;
    }
    
    public void setIdVd(short idVd) {
        this.idVd = idVd;
    }


    @Column(name="ORGANIZACIONA_JEDINICA#", nullable=false, precision=5, scale=0)
    public int getOrganizacionaJedinica() {
        return this.organizacionaJedinica;
    }
    
    public void setOrganizacionaJedinica(int organizacionaJedinica) {
        this.organizacionaJedinica = organizacionaJedinica;
    }


    @Column(name="GODINA", nullable=false, precision=4, scale=0)
    public short getGodina() {
        return this.godina;
    }
    
    public void setGodina(short godina) {
        this.godina = godina;
    }


    @Column(name="ID_FIN_DOKUMENTA", nullable=false, precision=5, scale=0)
    public int getIdFinDokumenta() {
        return this.idFinDokumenta;
    }
    
    public void setIdFinDokumenta(int idFinDokumenta) {
        this.idFinDokumenta = idFinDokumenta;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdFinDokumentId) ) return false;
		 ProdFinDokumentId castOther = ( ProdFinDokumentId ) other; 
         
		 return (this.getIdVd()==castOther.getIdVd())
 && (this.getOrganizacionaJedinica()==castOther.getOrganizacionaJedinica())
 && (this.getGodina()==castOther.getGodina())
 && (this.getIdFinDokumenta()==castOther.getIdFinDokumenta());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdVd();
         result = 37 * result + this.getOrganizacionaJedinica();
         result = 37 * result + this.getGodina();
         result = 37 * result + this.getIdFinDokumenta();
         return result;
   }   


}


