package rs.invado.wo.domain.prod;
// Generated Jan 20, 2013 9:55:29 PM by Hibernate Tools 3.4.0.CR1


import rs.invado.wo.domain.ocp.OcpValuta;

import java.util.Date;
import javax.persistence.*;

/**
 * ProdKlasaCene generated by hbm2java
 */
@Entity
@Table(name="PROD_KLASA_CENE"
    ,schema="DAREX"
)
public class ProdKlasaCene  implements java.io.Serializable {


     private ProdKlasaCeneId id;
     private String naziv;
     private String status;
     private int radnik;
     private Date datum;
     private String rabat;
     private Integer idCenovnik;
     private OcpValuta ocpValuta;

    public ProdKlasaCene() {
    }

	
    public ProdKlasaCene(ProdKlasaCeneId id, int radnik) {
        this.id = id;
        this.radnik = radnik;
    }
    public ProdKlasaCene(ProdKlasaCeneId id, String naziv, String status, int radnik, Date datum, String rabat, Integer idCenovnik, OcpValuta idValute) {
       this.id = id;
       this.naziv = naziv;
       this.status = status;
       this.radnik = radnik;
       this.datum = datum;
       this.rabat = rabat;
       this.idCenovnik = idCenovnik;
       this.ocpValuta = idValute;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="organizacionaJedinica#", column=@Column(name="ORGANIZACIONA_JEDINICA#", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="idKlasaCene", column=@Column(name="ID_KLASA_CENE", nullable=false, precision=2, scale=0) ) } )
    public ProdKlasaCeneId getId() {
        return this.id;
    }
    
    public void setId(ProdKlasaCeneId id) {
        this.id = id;
    }

    
    @Column(name="NAZIV", length=40)
    public String getNaziv() {
        return this.naziv;
    }
    
    public void setNaziv(String naziv) {
        this.naziv = naziv;
    }

    
    @Column(name="STATUS", length=1)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="RADNIK#", nullable=false, precision=6, scale=0)
    public int getRadnik() {
        return this.radnik;
    }
    
    public void setRadnik(int radnik) {
        this.radnik = radnik;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", length=7)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="RABAT", length=1)
    public String getRabat() {
        return this.rabat;
    }
    
    public void setRabat(String rabat) {
        this.rabat = rabat;
    }

    
    @Column(name="ID_CENOVNIK", precision=5, scale=0)
    public Integer getIdCenovnik() {
        return this.idCenovnik;
    }
    
    public void setIdCenovnik(Integer idCenovnik) {
        this.idCenovnik = idCenovnik;
    }

    
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_VALUTE", referencedColumnName = "ID_VALUTE", insertable = false, updatable =  false)
    public OcpValuta getOcpValuta() {
        return ocpValuta;
    }

    public void setOcpValuta(OcpValuta ocpValuta) {
        this.ocpValuta = ocpValuta;
    }
}


