package rs.invado.wo.domain.prod;
// Generated Jan 7, 2013 9:06:09 PM by Hibernate Tools 3.4.0.CR1


import rs.invado.wo.domain.ocp.OcpPoslovniPartner;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;

/**
 * ProdPpRabat generated by hbm2java
 */
@Entity
@Table(name="PROD_PP_RABAT"
    ,schema="DAREX"
)
public class ProdPpRabat  implements java.io.Serializable {


     private int id;
     private OcpPoslovniPartner poslovniPartner;
     private short maxRokPlacanja;
     private BigDecimal ugovorniRabat;
     private Date datumOd;
     private Date datumDo;
     private Date datumUnosa;
     private int radnikUneo;
     private Date datumOvere;
     private Integer radnikOverio;
     private Short idVd;
     private String napomena;
     private String menica;
     private String ovlascenje;
     private String sveURedu;
     private String ugovorDp;
     private Integer organizacionaJedinica;
     private BigDecimal creditLimit;
     private Short valuta;
     private Integer idTipCl;
     private Set prodPpRabatStavkas = new HashSet(0);

    public ProdPpRabat() {
    }

	
    public ProdPpRabat(int id, OcpPoslovniPartner poslovniPartner, short maxRokPlacanja, BigDecimal ugovorniRabat, Date datumOd, Date datumUnosa, int radnikUneo) {
        this.id = id;
        this.poslovniPartner = poslovniPartner;
        this.maxRokPlacanja = maxRokPlacanja;
        this.ugovorniRabat = ugovorniRabat;
        this.datumOd = datumOd;
        this.datumUnosa = datumUnosa;
        this.radnikUneo = radnikUneo;
    }
    public ProdPpRabat(int id, OcpPoslovniPartner poslovniPartner, short maxRokPlacanja, BigDecimal ugovorniRabat, Date datumOd, Date datumDo, Date datumUnosa, int radnikUneo, Date datumOvere, Integer radnikOverio, Short idVd, String napomena, String menica, String ovlascenje, String sveURedu, String ugovorDp, Integer organizacionaJedinica, BigDecimal creditLimit, Short valuta, Integer idTipCl, Set prodPpRabatStavkas) {
       this.id = id;
       this.poslovniPartner = poslovniPartner;
       this.maxRokPlacanja = maxRokPlacanja;
       this.ugovorniRabat = ugovorniRabat;
       this.datumOd = datumOd;
       this.datumDo = datumDo;
       this.datumUnosa = datumUnosa;
       this.radnikUneo = radnikUneo;
       this.datumOvere = datumOvere;
       this.radnikOverio = radnikOverio;
       this.idVd = idVd;
       this.napomena = napomena;
       this.menica = menica;
       this.ovlascenje = ovlascenje;
       this.sveURedu = sveURedu;
       this.ugovorDp = ugovorDp;
       this.organizacionaJedinica = organizacionaJedinica;
       this.creditLimit = creditLimit;
       this.valuta = valuta;
       this.idTipCl = idTipCl;
       this.prodPpRabatStavkas = prodPpRabatStavkas;
    }
   
     @Id 

    
    @Column(name="ID", unique=true, nullable=false, precision=7, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }


    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "POSLOVNI_PARTNER#" , referencedColumnName = "POSLOVNI_PARTNER#", insertable =  true, updatable = true)
    public OcpPoslovniPartner getPoslovniPartner() {
        return this.poslovniPartner;
    }
    
    public void setPoslovniPartner(OcpPoslovniPartner poslovniPartner) {
        this.poslovniPartner = poslovniPartner;
    }

    
    @Column(name="MAX_ROK_PLACANJA", nullable=false, precision=3, scale=0)
    public short getMaxRokPlacanja() {
        return this.maxRokPlacanja;
    }
    
    public void setMaxRokPlacanja(short maxRokPlacanja) {
        this.maxRokPlacanja = maxRokPlacanja;
    }

    
    @Column(name="UGOVORNI_RABAT", nullable=false, precision=18, scale=3)
    public BigDecimal getUgovorniRabat() {
        return this.ugovorniRabat;
    }
    
    public void setUgovorniRabat(BigDecimal ugovorniRabat) {
        this.ugovorniRabat = ugovorniRabat;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_OD", nullable=false, length=7)
    public Date getDatumOd() {
        return this.datumOd;
    }
    
    public void setDatumOd(Date datumOd) {
        this.datumOd = datumOd;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_DO", length=7)
    public Date getDatumDo() {
        return this.datumDo;
    }
    
    public void setDatumDo(Date datumDo) {
        this.datumDo = datumDo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_UNOSA", nullable=false, length=7)
    public Date getDatumUnosa() {
        return this.datumUnosa;
    }
    
    public void setDatumUnosa(Date datumUnosa) {
        this.datumUnosa = datumUnosa;
    }

    
    @Column(name="RADNIK#_UNEO", nullable=false, precision=6, scale=0)
    public int getRadnikUneo() {
        return this.radnikUneo;
    }
    
    public void setRadnikUneo(int radnikUneo) {
        this.radnikUneo = radnikUneo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM_OVERE", length=7)
    public Date getDatumOvere() {
        return this.datumOvere;
    }
    
    public void setDatumOvere(Date datumOvere) {
        this.datumOvere = datumOvere;
    }

    
    @Column(name="RADNIK#_OVERIO", precision=6, scale=0)
    public Integer getRadnikOverio() {
        return this.radnikOverio;
    }
    
    public void setRadnikOverio(Integer radnikOverio) {
        this.radnikOverio = radnikOverio;
    }

    
    @Column(name="ID_VD", precision=3, scale=0)
    public Short getIdVd() {
        return this.idVd;
    }
    
    public void setIdVd(Short idVd) {
        this.idVd = idVd;
    }

    
    @Column(name="NAPOMENA")
    public String getNapomena() {
        return this.napomena;
    }
    
    public void setNapomena(String napomena) {
        this.napomena = napomena;
    }

    
    @Column(name="MENICA")
    public String getMenica() {
        return this.menica;
    }
    
    public void setMenica(String menica) {
        this.menica = menica;
    }

    
    @Column(name="OVLASCENJE")
    public String getOvlascenje() {
        return this.ovlascenje;
    }
    
    public void setOvlascenje(String ovlascenje) {
        this.ovlascenje = ovlascenje;
    }

    
    @Column(name="SVE_U_REDU", length=2)
    public String getSveURedu() {
        return this.sveURedu;
    }
    
    public void setSveURedu(String sveURedu) {
        this.sveURedu = sveURedu;
    }

    
    @Column(name="UGOVOR_DP")
    public String getUgovorDp() {
        return this.ugovorDp;
    }
    
    public void setUgovorDp(String ugovorDp) {
        this.ugovorDp = ugovorDp;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#", precision=5, scale=0)
    public Integer getOrganizacionaJedinica() {
        return this.organizacionaJedinica;
    }
    
    public void setOrganizacionaJedinica(Integer organizacionaJedinica) {
        this.organizacionaJedinica = organizacionaJedinica;
    }

    
    @Column(name="CREDIT_LIMIT", precision=18, scale=3)
    public BigDecimal getCreditLimit() {
        return this.creditLimit;
    }
    
    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    
    @Column(name="VALUTA", precision=3, scale=0)
    public Short getValuta() {
        return this.valuta;
    }
    
    public void setValuta(Short valuta) {
        this.valuta = valuta;
    }

    
    @Column(name="ID_TIP_CL", precision=5, scale=0)
    public Integer getIdTipCl() {
        return this.idTipCl;
    }
    
    public void setIdTipCl(Integer idTipCl) {
        this.idTipCl = idTipCl;
    }

@OneToMany(targetEntity = ProdPpRabatStavka.class, fetch=FetchType.LAZY, mappedBy="prodPpRabat")
    public Set getProdPpRabatStavkas() {
        return this.prodPpRabatStavkas;
    }
    
    public void setProdPpRabatStavkas(Set prodPpRabatStavkas) {
        this.prodPpRabatStavkas = prodPpRabatStavkas;
    }




}


