package rs.invado.wo.domain.prod;
// Generated Jan 20, 2013 11:37:50 PM by Hibernate Tools 3.4.0.CR1


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdStavkaFinDokumenta generated by hbm2java
 */
@Entity
@Table(name="PROD_STAVKA_FIN_DOKUMENTA"
    ,schema="DAREX"
)
public class ProdStavkaFinDokumenta  implements java.io.Serializable {


     private ProdStavkaFinDokumentaId id;
     private ProdFinDokument prodFinDokument;
     private Integer proizvod;
     private Short idJediniceMere;
     private BigDecimal kolicina;
     private BigDecimal jedinicnaCena;
     private BigDecimal vrednost;
     private BigDecimal procentRabata;
     private short vrstaStavke;
     private BigDecimal vrednostRabata;
     private Integer organizacionaJedinicaPr;
     private Short idVdPo;
     private Integer organizacionaJedinicaPo;
     private Short godinaPo;
     private Integer idFinDokumentaPo;
     private Short rbStavkeFindokPo;
     private BigDecimal deviznaVrednost;
     private BigDecimal akciza;
     private BigDecimal procenatNaplate;
     private BigDecimal otpremljenaVrednost;
     private BigDecimal iznosPoreza;
     private BigDecimal procenatPoreza;
     private Short poreskaKlasa;
     private Date datum;
     private String clanZakona;
     private BigDecimal preostaliIznos;
     private BigDecimal ruc;
     private BigDecimal deviznaCena;

    public ProdStavkaFinDokumenta() {
    }

	
    public ProdStavkaFinDokumenta(ProdStavkaFinDokumentaId id, ProdFinDokument prodFinDokument, BigDecimal vrednost, short vrstaStavke) {
        this.id = id;
        this.prodFinDokument = prodFinDokument;
        this.vrednost = vrednost;
        this.vrstaStavke = vrstaStavke;
    }
    public ProdStavkaFinDokumenta(ProdStavkaFinDokumentaId id, ProdFinDokument prodFinDokument, Integer proizvod, Short idJediniceMere, BigDecimal kolicina, BigDecimal jedinicnaCena, BigDecimal vrednost, BigDecimal procentRabata, short vrstaStavke, BigDecimal vrednostRabata, Integer organizacionaJedinicaPr, Short idVdPo, Integer organizacionaJedinicaPo, Short godinaPo, Integer idFinDokumentaPo, Short rbStavkeFindokPo, BigDecimal deviznaVrednost, BigDecimal akciza, BigDecimal procenatNaplate, BigDecimal otpremljenaVrednost, BigDecimal iznosPoreza, BigDecimal procenatPoreza, Short poreskaKlasa, Date datum, String clanZakona, BigDecimal preostaliIznos, BigDecimal ruc, BigDecimal deviznaCena) {
       this.id = id;
       this.prodFinDokument = prodFinDokument;
       this.proizvod = proizvod;
       this.idJediniceMere = idJediniceMere;
       this.kolicina = kolicina;
       this.jedinicnaCena = jedinicnaCena;
       this.vrednost = vrednost;
       this.procentRabata = procentRabata;
       this.vrstaStavke = vrstaStavke;
       this.vrednostRabata = vrednostRabata;
       this.organizacionaJedinicaPr = organizacionaJedinicaPr;
       this.idVdPo = idVdPo;
       this.organizacionaJedinicaPo = organizacionaJedinicaPo;
       this.godinaPo = godinaPo;
       this.idFinDokumentaPo = idFinDokumentaPo;
       this.rbStavkeFindokPo = rbStavkeFindokPo;
       this.deviznaVrednost = deviznaVrednost;
       this.akciza = akciza;
       this.procenatNaplate = procenatNaplate;
       this.otpremljenaVrednost = otpremljenaVrednost;
       this.iznosPoreza = iznosPoreza;
       this.procenatPoreza = procenatPoreza;
       this.poreskaKlasa = poreskaKlasa;
       this.datum = datum;
       this.clanZakona = clanZakona;
       this.preostaliIznos = preostaliIznos;
       this.ruc = ruc;
       this.deviznaCena = deviznaCena;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idVd", column=@Column(name="ID_VD", nullable=false, precision=3, scale=0) ), 
        @AttributeOverride(name="organizacionaJedinica", column=@Column(name="ORGANIZACIONA_JEDINICA#", nullable=false, precision=5, scale=0) ),
        @AttributeOverride(name="godina", column=@Column(name="GODINA", nullable=false, precision=4, scale=0) ), 
        @AttributeOverride(name="idFinDokumenta", column=@Column(name="ID_FIN_DOKUMENTA", nullable=false, precision=5, scale=0) ), 
        @AttributeOverride(name="rbStavkeFindok", column=@Column(name="RB_STAVKE_FINDOK", nullable=false, precision=3, scale=0) ) } )
    public ProdStavkaFinDokumentaId getId() {
        return this.id;
    }
    
    public void setId(ProdStavkaFinDokumentaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="ID_VD", referencedColumnName="ID_VD", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ORGANIZACIONA_JEDINICA#", referencedColumnName="ORGANIZACIONA_JEDINICA#", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="GODINA", referencedColumnName="GODINA", nullable=false, insertable=false, updatable=false), 
        @JoinColumn(name="ID_FIN_DOKUMENTA", referencedColumnName="ID_FIN_DOKUMENTA", nullable=false, insertable=false, updatable=false) } )
    public ProdFinDokument getProdFinDokument() {
        return this.prodFinDokument;
    }
    
    public void setProdFinDokument(ProdFinDokument prodFinDokument) {
        this.prodFinDokument = prodFinDokument;
    }

    
    @Column(name="PROIZVOD#", precision=7, scale=0)
    public Integer getProizvod() {
        return this.proizvod;
    }
    
    public void setProizvod(Integer proizvod) {
        this.proizvod = proizvod;
    }

    
    @Column(name="ID_JEDINICE_MERE", precision=3, scale=0)
    public Short getIdJediniceMere() {
        return this.idJediniceMere;
    }
    
    public void setIdJediniceMere(Short idJediniceMere) {
        this.idJediniceMere = idJediniceMere;
    }

    
    @Column(name="KOLICINA", precision=18, scale=3)
    public BigDecimal getKolicina() {
        return this.kolicina;
    }
    
    public void setKolicina(BigDecimal kolicina) {
        this.kolicina = kolicina;
    }

    
    @Column(name="JEDINICNA_CENA", precision=18, scale=4)
    public BigDecimal getJedinicnaCena() {
        return this.jedinicnaCena;
    }
    
    public void setJedinicnaCena(BigDecimal jedinicnaCena) {
        this.jedinicnaCena = jedinicnaCena;
    }

    
    @Column(name="VREDNOST", nullable=false, precision=21, scale=4)
    public BigDecimal getVrednost() {
        return this.vrednost;
    }
    
    public void setVrednost(BigDecimal vrednost) {
        this.vrednost = vrednost;
    }

    
    @Column(name="PROCENT_RABATA", precision=6, scale=3)
    public BigDecimal getProcentRabata() {
        return this.procentRabata;
    }
    
    public void setProcentRabata(BigDecimal procentRabata) {
        this.procentRabata = procentRabata;
    }

    
    @Column(name="VRSTA_STAVKE#", nullable=false, precision=3, scale=0)
    public short getVrstaStavke() {
        return this.vrstaStavke;
    }
    
    public void setVrstaStavke(short vrstaStavke) {
        this.vrstaStavke = vrstaStavke;
    }

    
    @Column(name="VREDNOST_RABATA", precision=18, scale=3)
    public BigDecimal getVrednostRabata() {
        return this.vrednostRabata;
    }
    
    public void setVrednostRabata(BigDecimal vrednostRabata) {
        this.vrednostRabata = vrednostRabata;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#_PR", precision=5, scale=0)
    public Integer getOrganizacionaJedinicaPr() {
        return this.organizacionaJedinicaPr;
    }
    
    public void setOrganizacionaJedinicaPr(Integer organizacionaJedinicaPr) {
        this.organizacionaJedinicaPr = organizacionaJedinicaPr;
    }

    
    @Column(name="ID_VD_PO", precision=3, scale=0)
    public Short getIdVdPo() {
        return this.idVdPo;
    }
    
    public void setIdVdPo(Short idVdPo) {
        this.idVdPo = idVdPo;
    }

    
    @Column(name="ORGANIZACIONA_JEDINICA#_PO", precision=5, scale=0)
    public Integer getOrganizacionaJedinicaPo() {
        return this.organizacionaJedinicaPo;
    }
    
    public void setOrganizacionaJedinicaPo(Integer organizacionaJedinicaPo) {
        this.organizacionaJedinicaPo = organizacionaJedinicaPo;
    }

    
    @Column(name="GODINA_PO", precision=4, scale=0)
    public Short getGodinaPo() {
        return this.godinaPo;
    }
    
    public void setGodinaPo(Short godinaPo) {
        this.godinaPo = godinaPo;
    }

    
    @Column(name="ID_FIN_DOKUMENTA_PO", precision=5, scale=0)
    public Integer getIdFinDokumentaPo() {
        return this.idFinDokumentaPo;
    }
    
    public void setIdFinDokumentaPo(Integer idFinDokumentaPo) {
        this.idFinDokumentaPo = idFinDokumentaPo;
    }

    
    @Column(name="RB_STAVKE_FINDOK_PO", precision=3, scale=0)
    public Short getRbStavkeFindokPo() {
        return this.rbStavkeFindokPo;
    }
    
    public void setRbStavkeFindokPo(Short rbStavkeFindokPo) {
        this.rbStavkeFindokPo = rbStavkeFindokPo;
    }

    
    @Column(name="DEVIZNA_VREDNOST", precision=20, scale=3)
    public BigDecimal getDeviznaVrednost() {
        return this.deviznaVrednost;
    }
    
    public void setDeviznaVrednost(BigDecimal deviznaVrednost) {
        this.deviznaVrednost = deviznaVrednost;
    }

    
    @Column(name="AKCIZA", precision=20, scale=3)
    public BigDecimal getAkciza() {
        return this.akciza;
    }
    
    public void setAkciza(BigDecimal akciza) {
        this.akciza = akciza;
    }

    
    @Column(name="PROCENAT_NAPLATE", precision=5)
    public BigDecimal getProcenatNaplate() {
        return this.procenatNaplate;
    }
    
    public void setProcenatNaplate(BigDecimal procenatNaplate) {
        this.procenatNaplate = procenatNaplate;
    }

    
    @Column(name="OTPREMLJENA_VREDNOST", precision=20, scale=3)
    public BigDecimal getOtpremljenaVrednost() {
        return this.otpremljenaVrednost;
    }
    
    public void setOtpremljenaVrednost(BigDecimal otpremljenaVrednost) {
        this.otpremljenaVrednost = otpremljenaVrednost;
    }

    
    @Column(name="IZNOS_POREZA", precision=20, scale=3)
    public BigDecimal getIznosPoreza() {
        return this.iznosPoreza;
    }
    
    public void setIznosPoreza(BigDecimal iznosPoreza) {
        this.iznosPoreza = iznosPoreza;
    }

    
    @Column(name="PROCENAT_POREZA", precision=6)
    public BigDecimal getProcenatPoreza() {
        return this.procenatPoreza;
    }
    
    public void setProcenatPoreza(BigDecimal procenatPoreza) {
        this.procenatPoreza = procenatPoreza;
    }

    
    @Column(name="PORESKA_KLASA#", precision=3, scale=0)
    public Short getPoreskaKlasa() {
        return this.poreskaKlasa;
    }
    
    public void setPoreskaKlasa(Short poreskaKlasa) {
        this.poreskaKlasa = poreskaKlasa;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="DATUM", length=7)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="CLAN_ZAKONA", length=60)
    public String getClanZakona() {
        return this.clanZakona;
    }
    
    public void setClanZakona(String clanZakona) {
        this.clanZakona = clanZakona;
    }

    
    @Column(name="PREOSTALI_IZNOS", precision=18, scale=3)
    public BigDecimal getPreostaliIznos() {
        return this.preostaliIznos;
    }
    
    public void setPreostaliIznos(BigDecimal preostaliIznos) {
        this.preostaliIznos = preostaliIznos;
    }

    
    @Column(name="RUC", precision=18, scale=3)
    public BigDecimal getRuc() {
        return this.ruc;
    }
    
    public void setRuc(BigDecimal ruc) {
        this.ruc = ruc;
    }

    
    @Column(name="DEVIZNA_CENA", precision=18, scale=4)
    public BigDecimal getDeviznaCena() {
        return this.deviznaCena;
    }
    
    public void setDeviznaCena(BigDecimal deviznaCena) {
        this.deviznaCena = deviznaCena;
    }




}


