package rs.invado.wo.domain.prod;
// Generated Dec 11, 2012 10:40:41 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ProdCenovnikId generated by hbm2java
 */
@Embeddable
public class ProdCenovnikId  implements java.io.Serializable {


     private int organizacionaJedinica;
     private int idCenovnik;
     private int idKlasaCene;

    public ProdCenovnikId() {
    }

    public ProdCenovnikId(int organizacionaJedinica, int idCenovnik, int idKlasaCene) {
       this.organizacionaJedinica = organizacionaJedinica;
       this.idCenovnik = idCenovnik;
       this.idKlasaCene = idKlasaCene;
    }
   


    @Column(name="ORGANIZACIONA_JEDINICA#", nullable=false, precision=5, scale=0)
    public int getOrganizacionaJedinica() {
        return this.organizacionaJedinica;
    }
    
    public void setOrganizacionaJedinica(int organizacionaJedinica) {
        this.organizacionaJedinica = organizacionaJedinica;
    }


    @Column(name="ID_CENOVNIK", nullable=false, precision=5, scale=0)
    public int getIdCenovnik() {
        return this.idCenovnik;
    }
    
    public void setIdCenovnik(int idCenovnik) {
        this.idCenovnik = idCenovnik;
    }


    @Column(name="ID_KLASA_CENE", nullable=false, precision=2, scale=0)
    public int getIdKlasaCene() {
        return this.idKlasaCene;
    }
    
    public void setIdKlasaCene(int idKlasaCene) {
        this.idKlasaCene = idKlasaCene;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdCenovnikId) ) return false;
		 ProdCenovnikId castOther = ( ProdCenovnikId ) other; 
         
		 return (this.getOrganizacionaJedinica()==castOther.getOrganizacionaJedinica())
 && (this.getIdCenovnik()==castOther.getIdCenovnik())
 && (this.getIdKlasaCene()==castOther.getIdKlasaCene());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getOrganizacionaJedinica();
         result = 37 * result + this.getIdCenovnik();
         result = 37 * result + this.getIdKlasaCene();
         return result;
   }   


}


