package rs.invado.wo.domain.wo;

// Generated Mar 6, 2013 10:35:50 PM by Hibernate Tools 3.4.0.CR1

import org.hibernate.annotations.ManyToAny;

import javax.persistence.*;

/**
 * WoUserHasRight generated by hbm2java
 */
@Entity
@Table(name = "WO_USER_HAS_RIGHT", schema = "DAREX")
public class WoUserHasRight implements java.io.Serializable {

	private WoUserHasRightId id;
    private Boolean value;
    private WoUser woUser;

	public WoUserHasRight() {
	}

	public WoUserHasRight(WoUserHasRightId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "userId", column = @Column(name = "USER_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "rigthId", column = @Column(name = "RIGTH_ID", precision = 22, scale = 0)),
			@AttributeOverride(name = "value", column = @Column(name = "VALUE", precision = 1, scale = 0)) })
	public WoUserHasRightId getId() {
		return this.id;
	}

	public void setId(WoUserHasRightId id) {
		this.id = id;
	}

    @Column(name = "VALUE", precision = 1, scale = 0)
    public Boolean getValue() {
        return this.value;
    }

    public void setValue(Boolean value) {
        this.value = value;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "USER_ID", referencedColumnName = "id", nullable = false, insertable = false, updatable = false)
    public WoUser getWoUser() {
        return woUser;
    }

    public void setWoUser(WoUser woUser) {
        this.woUser = woUser;
    }
}
